package com.zhixin.rd.rkjc.web.entity.qk;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Bxdry implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.N_XH
     *
     * @mbggenerated
     */
    private BigDecimal nXh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_XDRYLY
     *
     * @mbggenerated
     */
    private String cXdryly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.N_YWXH
     *
     * @mbggenerated
     */
    private BigDecimal nYwxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_TNAME
     *
     * @mbggenerated
     */
    private String cTname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_RYBH
     *
     * @mbggenerated
     */
    private String cRybh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_XM
     *
     * @mbggenerated
     */
    private String cXm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_CH
     *
     * @mbggenerated
     */
    private String cCh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_XB
     *
     * @mbggenerated
     */
    private String cXb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_MZ
     *
     * @mbggenerated
     */
    private String cMz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.D_CS
     *
     * @mbggenerated
     */
    private Date dCs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.N_SG
     *
     * @mbggenerated
     */
    private Short nSg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_GJ
     *
     * @mbggenerated
     */
    private String cGj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_SFZJZL
     *
     * @mbggenerated
     */
    private String cSfzjzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_SFZHM
     *
     * @mbggenerated
     */
    private String cSfzhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_18SFZHM
     *
     * @mbggenerated
     */
    private String c18sfzhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_WHCD
     *
     * @mbggenerated
     */
    private String cWhcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_FWCS
     *
     * @mbggenerated
     */
    private String cFwcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_HJSZD
     *
     * @mbggenerated
     */
    private String cHjszd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_HJPCS
     *
     * @mbggenerated
     */
    private String cHjpcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_HJSZDXZ
     *
     * @mbggenerated
     */
    private String cHjszdxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_SJJZD
     *
     * @mbggenerated
     */
    private String cSjjzd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_SJPCS
     *
     * @mbggenerated
     */
    private String cSjpcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_SJJZDXZ
     *
     * @mbggenerated
     */
    private String cSjjzdxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_JYQK
     *
     * @mbggenerated
     */
    private String cJyqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_XDHGST
     *
     * @mbggenerated
     */
    private String cXdhgst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_DNA
     *
     * @mbggenerated
     */
    private String cDna;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.N_YXX
     *
     * @mbggenerated
     */
    private Short nYxx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_ACTION
     *
     * @mbggenerated
     */
    private String cAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_TSTAMP
     *
     * @mbggenerated
     */
    private String cTstamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_XGBSDW
     *
     * @mbggenerated
     */
    private String cXgbsdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_CCBZ
     *
     * @mbggenerated
     */
    private String cCcbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_NCCBZ
     *
     * @mbggenerated
     */
    private String cNccbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_DWDM
     *
     * @mbggenerated
     */
    private String cDwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_DJR
     *
     * @mbggenerated
     */
    private String cDjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.D_DJ
     *
     * @mbggenerated
     */
    private Date dDj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.N_SF828K
     *
     * @mbggenerated
     */
    private Short nSf828k;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_BH
     *
     * @mbggenerated
     */
    private String cBh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.N_YXH
     *
     * @mbggenerated
     */
    private BigDecimal nYxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.INOUTBZ
     *
     * @mbggenerated
     */
    private String inoutbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_GSDW
     *
     * @mbggenerated
     */
    private String cGsdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_HY
     *
     * @mbggenerated
     */
    private String cHy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_CYZK
     *
     * @mbggenerated
     */
    private String cCyzk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_XDRY.C_RYBS
     *
     * @mbggenerated
     */
    private String cRybs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table B_XDRY
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.N_XH
     *
     * @return the value of B_XDRY.N_XH
     *
     * @mbggenerated
     */
    public BigDecimal getnXh() {
        return nXh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.N_XH
     *
     * @param nXh the value for B_XDRY.N_XH
     *
     * @mbggenerated
     */
    public void setnXh(BigDecimal nXh) {
        this.nXh = nXh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_XDRYLY
     *
     * @return the value of B_XDRY.C_XDRYLY
     *
     * @mbggenerated
     */
    public String getcXdryly() {
        return cXdryly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_XDRYLY
     *
     * @param cXdryly the value for B_XDRY.C_XDRYLY
     *
     * @mbggenerated
     */
    public void setcXdryly(String cXdryly) {
        this.cXdryly = cXdryly == null ? null : cXdryly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.N_YWXH
     *
     * @return the value of B_XDRY.N_YWXH
     *
     * @mbggenerated
     */
    public BigDecimal getnYwxh() {
        return nYwxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.N_YWXH
     *
     * @param nYwxh the value for B_XDRY.N_YWXH
     *
     * @mbggenerated
     */
    public void setnYwxh(BigDecimal nYwxh) {
        this.nYwxh = nYwxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_TNAME
     *
     * @return the value of B_XDRY.C_TNAME
     *
     * @mbggenerated
     */
    public String getcTname() {
        return cTname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_TNAME
     *
     * @param cTname the value for B_XDRY.C_TNAME
     *
     * @mbggenerated
     */
    public void setcTname(String cTname) {
        this.cTname = cTname == null ? null : cTname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_RYBH
     *
     * @return the value of B_XDRY.C_RYBH
     *
     * @mbggenerated
     */
    public String getcRybh() {
        return cRybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_RYBH
     *
     * @param cRybh the value for B_XDRY.C_RYBH
     *
     * @mbggenerated
     */
    public void setcRybh(String cRybh) {
        this.cRybh = cRybh == null ? null : cRybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_XM
     *
     * @return the value of B_XDRY.C_XM
     *
     * @mbggenerated
     */
    public String getcXm() {
        return cXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_XM
     *
     * @param cXm the value for B_XDRY.C_XM
     *
     * @mbggenerated
     */
    public void setcXm(String cXm) {
        this.cXm = cXm == null ? null : cXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_CH
     *
     * @return the value of B_XDRY.C_CH
     *
     * @mbggenerated
     */
    public String getcCh() {
        return cCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_CH
     *
     * @param cCh the value for B_XDRY.C_CH
     *
     * @mbggenerated
     */
    public void setcCh(String cCh) {
        this.cCh = cCh == null ? null : cCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_XB
     *
     * @return the value of B_XDRY.C_XB
     *
     * @mbggenerated
     */
    public String getcXb() {
        return cXb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_XB
     *
     * @param cXb the value for B_XDRY.C_XB
     *
     * @mbggenerated
     */
    public void setcXb(String cXb) {
        this.cXb = cXb == null ? null : cXb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_MZ
     *
     * @return the value of B_XDRY.C_MZ
     *
     * @mbggenerated
     */
    public String getcMz() {
        return cMz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_MZ
     *
     * @param cMz the value for B_XDRY.C_MZ
     *
     * @mbggenerated
     */
    public void setcMz(String cMz) {
        this.cMz = cMz == null ? null : cMz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.D_CS
     *
     * @return the value of B_XDRY.D_CS
     *
     * @mbggenerated
     */
    public Date getdCs() {
        return dCs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.D_CS
     *
     * @param dCs the value for B_XDRY.D_CS
     *
     * @mbggenerated
     */
    public void setdCs(Date dCs) {
        this.dCs = dCs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.N_SG
     *
     * @return the value of B_XDRY.N_SG
     *
     * @mbggenerated
     */
    public Short getnSg() {
        return nSg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.N_SG
     *
     * @param nSg the value for B_XDRY.N_SG
     *
     * @mbggenerated
     */
    public void setnSg(Short nSg) {
        this.nSg = nSg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_GJ
     *
     * @return the value of B_XDRY.C_GJ
     *
     * @mbggenerated
     */
    public String getcGj() {
        return cGj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_GJ
     *
     * @param cGj the value for B_XDRY.C_GJ
     *
     * @mbggenerated
     */
    public void setcGj(String cGj) {
        this.cGj = cGj == null ? null : cGj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_SFZJZL
     *
     * @return the value of B_XDRY.C_SFZJZL
     *
     * @mbggenerated
     */
    public String getcSfzjzl() {
        return cSfzjzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_SFZJZL
     *
     * @param cSfzjzl the value for B_XDRY.C_SFZJZL
     *
     * @mbggenerated
     */
    public void setcSfzjzl(String cSfzjzl) {
        this.cSfzjzl = cSfzjzl == null ? null : cSfzjzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_SFZHM
     *
     * @return the value of B_XDRY.C_SFZHM
     *
     * @mbggenerated
     */
    public String getcSfzhm() {
        return cSfzhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_SFZHM
     *
     * @param cSfzhm the value for B_XDRY.C_SFZHM
     *
     * @mbggenerated
     */
    public void setcSfzhm(String cSfzhm) {
        this.cSfzhm = cSfzhm == null ? null : cSfzhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_18SFZHM
     *
     * @return the value of B_XDRY.C_18SFZHM
     *
     * @mbggenerated
     */
    public String getC18sfzhm() {
        return c18sfzhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_18SFZHM
     *
     * @param c18sfzhm the value for B_XDRY.C_18SFZHM
     *
     * @mbggenerated
     */
    public void setC18sfzhm(String c18sfzhm) {
        this.c18sfzhm = c18sfzhm == null ? null : c18sfzhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_WHCD
     *
     * @return the value of B_XDRY.C_WHCD
     *
     * @mbggenerated
     */
    public String getcWhcd() {
        return cWhcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_WHCD
     *
     * @param cWhcd the value for B_XDRY.C_WHCD
     *
     * @mbggenerated
     */
    public void setcWhcd(String cWhcd) {
        this.cWhcd = cWhcd == null ? null : cWhcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_FWCS
     *
     * @return the value of B_XDRY.C_FWCS
     *
     * @mbggenerated
     */
    public String getcFwcs() {
        return cFwcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_FWCS
     *
     * @param cFwcs the value for B_XDRY.C_FWCS
     *
     * @mbggenerated
     */
    public void setcFwcs(String cFwcs) {
        this.cFwcs = cFwcs == null ? null : cFwcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_HJSZD
     *
     * @return the value of B_XDRY.C_HJSZD
     *
     * @mbggenerated
     */
    public String getcHjszd() {
        return cHjszd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_HJSZD
     *
     * @param cHjszd the value for B_XDRY.C_HJSZD
     *
     * @mbggenerated
     */
    public void setcHjszd(String cHjszd) {
        this.cHjszd = cHjszd == null ? null : cHjszd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_HJPCS
     *
     * @return the value of B_XDRY.C_HJPCS
     *
     * @mbggenerated
     */
    public String getcHjpcs() {
        return cHjpcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_HJPCS
     *
     * @param cHjpcs the value for B_XDRY.C_HJPCS
     *
     * @mbggenerated
     */
    public void setcHjpcs(String cHjpcs) {
        this.cHjpcs = cHjpcs == null ? null : cHjpcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_HJSZDXZ
     *
     * @return the value of B_XDRY.C_HJSZDXZ
     *
     * @mbggenerated
     */
    public String getcHjszdxz() {
        return cHjszdxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_HJSZDXZ
     *
     * @param cHjszdxz the value for B_XDRY.C_HJSZDXZ
     *
     * @mbggenerated
     */
    public void setcHjszdxz(String cHjszdxz) {
        this.cHjszdxz = cHjszdxz == null ? null : cHjszdxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_SJJZD
     *
     * @return the value of B_XDRY.C_SJJZD
     *
     * @mbggenerated
     */
    public String getcSjjzd() {
        return cSjjzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_SJJZD
     *
     * @param cSjjzd the value for B_XDRY.C_SJJZD
     *
     * @mbggenerated
     */
    public void setcSjjzd(String cSjjzd) {
        this.cSjjzd = cSjjzd == null ? null : cSjjzd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_SJPCS
     *
     * @return the value of B_XDRY.C_SJPCS
     *
     * @mbggenerated
     */
    public String getcSjpcs() {
        return cSjpcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_SJPCS
     *
     * @param cSjpcs the value for B_XDRY.C_SJPCS
     *
     * @mbggenerated
     */
    public void setcSjpcs(String cSjpcs) {
        this.cSjpcs = cSjpcs == null ? null : cSjpcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_SJJZDXZ
     *
     * @return the value of B_XDRY.C_SJJZDXZ
     *
     * @mbggenerated
     */
    public String getcSjjzdxz() {
        return cSjjzdxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_SJJZDXZ
     *
     * @param cSjjzdxz the value for B_XDRY.C_SJJZDXZ
     *
     * @mbggenerated
     */
    public void setcSjjzdxz(String cSjjzdxz) {
        this.cSjjzdxz = cSjjzdxz == null ? null : cSjjzdxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_JYQK
     *
     * @return the value of B_XDRY.C_JYQK
     *
     * @mbggenerated
     */
    public String getcJyqk() {
        return cJyqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_JYQK
     *
     * @param cJyqk the value for B_XDRY.C_JYQK
     *
     * @mbggenerated
     */
    public void setcJyqk(String cJyqk) {
        this.cJyqk = cJyqk == null ? null : cJyqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_XDHGST
     *
     * @return the value of B_XDRY.C_XDHGST
     *
     * @mbggenerated
     */
    public String getcXdhgst() {
        return cXdhgst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_XDHGST
     *
     * @param cXdhgst the value for B_XDRY.C_XDHGST
     *
     * @mbggenerated
     */
    public void setcXdhgst(String cXdhgst) {
        this.cXdhgst = cXdhgst == null ? null : cXdhgst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_DNA
     *
     * @return the value of B_XDRY.C_DNA
     *
     * @mbggenerated
     */
    public String getcDna() {
        return cDna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_DNA
     *
     * @param cDna the value for B_XDRY.C_DNA
     *
     * @mbggenerated
     */
    public void setcDna(String cDna) {
        this.cDna = cDna == null ? null : cDna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.N_YXX
     *
     * @return the value of B_XDRY.N_YXX
     *
     * @mbggenerated
     */
    public Short getnYxx() {
        return nYxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.N_YXX
     *
     * @param nYxx the value for B_XDRY.N_YXX
     *
     * @mbggenerated
     */
    public void setnYxx(Short nYxx) {
        this.nYxx = nYxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_ACTION
     *
     * @return the value of B_XDRY.C_ACTION
     *
     * @mbggenerated
     */
    public String getcAction() {
        return cAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_ACTION
     *
     * @param cAction the value for B_XDRY.C_ACTION
     *
     * @mbggenerated
     */
    public void setcAction(String cAction) {
        this.cAction = cAction == null ? null : cAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_TSTAMP
     *
     * @return the value of B_XDRY.C_TSTAMP
     *
     * @mbggenerated
     */
    public String getcTstamp() {
        return cTstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_TSTAMP
     *
     * @param cTstamp the value for B_XDRY.C_TSTAMP
     *
     * @mbggenerated
     */
    public void setcTstamp(String cTstamp) {
        this.cTstamp = cTstamp == null ? null : cTstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_XGBSDW
     *
     * @return the value of B_XDRY.C_XGBSDW
     *
     * @mbggenerated
     */
    public String getcXgbsdw() {
        return cXgbsdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_XGBSDW
     *
     * @param cXgbsdw the value for B_XDRY.C_XGBSDW
     *
     * @mbggenerated
     */
    public void setcXgbsdw(String cXgbsdw) {
        this.cXgbsdw = cXgbsdw == null ? null : cXgbsdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_CCBZ
     *
     * @return the value of B_XDRY.C_CCBZ
     *
     * @mbggenerated
     */
    public String getcCcbz() {
        return cCcbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_CCBZ
     *
     * @param cCcbz the value for B_XDRY.C_CCBZ
     *
     * @mbggenerated
     */
    public void setcCcbz(String cCcbz) {
        this.cCcbz = cCcbz == null ? null : cCcbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_NCCBZ
     *
     * @return the value of B_XDRY.C_NCCBZ
     *
     * @mbggenerated
     */
    public String getcNccbz() {
        return cNccbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_NCCBZ
     *
     * @param cNccbz the value for B_XDRY.C_NCCBZ
     *
     * @mbggenerated
     */
    public void setcNccbz(String cNccbz) {
        this.cNccbz = cNccbz == null ? null : cNccbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_DWDM
     *
     * @return the value of B_XDRY.C_DWDM
     *
     * @mbggenerated
     */
    public String getcDwdm() {
        return cDwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_DWDM
     *
     * @param cDwdm the value for B_XDRY.C_DWDM
     *
     * @mbggenerated
     */
    public void setcDwdm(String cDwdm) {
        this.cDwdm = cDwdm == null ? null : cDwdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_DJR
     *
     * @return the value of B_XDRY.C_DJR
     *
     * @mbggenerated
     */
    public String getcDjr() {
        return cDjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_DJR
     *
     * @param cDjr the value for B_XDRY.C_DJR
     *
     * @mbggenerated
     */
    public void setcDjr(String cDjr) {
        this.cDjr = cDjr == null ? null : cDjr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.D_DJ
     *
     * @return the value of B_XDRY.D_DJ
     *
     * @mbggenerated
     */
    public Date getdDj() {
        return dDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.D_DJ
     *
     * @param dDj the value for B_XDRY.D_DJ
     *
     * @mbggenerated
     */
    public void setdDj(Date dDj) {
        this.dDj = dDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.N_SF828K
     *
     * @return the value of B_XDRY.N_SF828K
     *
     * @mbggenerated
     */
    public Short getnSf828k() {
        return nSf828k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.N_SF828K
     *
     * @param nSf828k the value for B_XDRY.N_SF828K
     *
     * @mbggenerated
     */
    public void setnSf828k(Short nSf828k) {
        this.nSf828k = nSf828k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_BH
     *
     * @return the value of B_XDRY.C_BH
     *
     * @mbggenerated
     */
    public String getcBh() {
        return cBh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_BH
     *
     * @param cBh the value for B_XDRY.C_BH
     *
     * @mbggenerated
     */
    public void setcBh(String cBh) {
        this.cBh = cBh == null ? null : cBh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.N_YXH
     *
     * @return the value of B_XDRY.N_YXH
     *
     * @mbggenerated
     */
    public BigDecimal getnYxh() {
        return nYxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.N_YXH
     *
     * @param nYxh the value for B_XDRY.N_YXH
     *
     * @mbggenerated
     */
    public void setnYxh(BigDecimal nYxh) {
        this.nYxh = nYxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.INOUTBZ
     *
     * @return the value of B_XDRY.INOUTBZ
     *
     * @mbggenerated
     */
    public String getInoutbz() {
        return inoutbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.INOUTBZ
     *
     * @param inoutbz the value for B_XDRY.INOUTBZ
     *
     * @mbggenerated
     */
    public void setInoutbz(String inoutbz) {
        this.inoutbz = inoutbz == null ? null : inoutbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_GSDW
     *
     * @return the value of B_XDRY.C_GSDW
     *
     * @mbggenerated
     */
    public String getcGsdw() {
        return cGsdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_GSDW
     *
     * @param cGsdw the value for B_XDRY.C_GSDW
     *
     * @mbggenerated
     */
    public void setcGsdw(String cGsdw) {
        this.cGsdw = cGsdw == null ? null : cGsdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_HY
     *
     * @return the value of B_XDRY.C_HY
     *
     * @mbggenerated
     */
    public String getcHy() {
        return cHy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_HY
     *
     * @param cHy the value for B_XDRY.C_HY
     *
     * @mbggenerated
     */
    public void setcHy(String cHy) {
        this.cHy = cHy == null ? null : cHy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_CYZK
     *
     * @return the value of B_XDRY.C_CYZK
     *
     * @mbggenerated
     */
    public String getcCyzk() {
        return cCyzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_CYZK
     *
     * @param cCyzk the value for B_XDRY.C_CYZK
     *
     * @mbggenerated
     */
    public void setcCyzk(String cCyzk) {
        this.cCyzk = cCyzk == null ? null : cCyzk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_XDRY.C_RYBS
     *
     * @return the value of B_XDRY.C_RYBS
     *
     * @mbggenerated
     */
    public String getcRybs() {
        return cRybs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_XDRY.C_RYBS
     *
     * @param cRybs the value for B_XDRY.C_RYBS
     *
     * @mbggenerated
     */
    public void setcRybs(String cRybs) {
        this.cRybs = cRybs == null ? null : cRybs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_XDRY
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Bxdry other = (Bxdry) that;
        return (this.getnXh() == null ? other.getnXh() == null : this.getnXh().equals(other.getnXh()))
            && (this.getcXdryly() == null ? other.getcXdryly() == null : this.getcXdryly().equals(other.getcXdryly()))
            && (this.getnYwxh() == null ? other.getnYwxh() == null : this.getnYwxh().equals(other.getnYwxh()))
            && (this.getcTname() == null ? other.getcTname() == null : this.getcTname().equals(other.getcTname()))
            && (this.getcRybh() == null ? other.getcRybh() == null : this.getcRybh().equals(other.getcRybh()))
            && (this.getcXm() == null ? other.getcXm() == null : this.getcXm().equals(other.getcXm()))
            && (this.getcCh() == null ? other.getcCh() == null : this.getcCh().equals(other.getcCh()))
            && (this.getcXb() == null ? other.getcXb() == null : this.getcXb().equals(other.getcXb()))
            && (this.getcMz() == null ? other.getcMz() == null : this.getcMz().equals(other.getcMz()))
            && (this.getdCs() == null ? other.getdCs() == null : this.getdCs().equals(other.getdCs()))
            && (this.getnSg() == null ? other.getnSg() == null : this.getnSg().equals(other.getnSg()))
            && (this.getcGj() == null ? other.getcGj() == null : this.getcGj().equals(other.getcGj()))
            && (this.getcSfzjzl() == null ? other.getcSfzjzl() == null : this.getcSfzjzl().equals(other.getcSfzjzl()))
            && (this.getcSfzhm() == null ? other.getcSfzhm() == null : this.getcSfzhm().equals(other.getcSfzhm()))
            && (this.getC18sfzhm() == null ? other.getC18sfzhm() == null : this.getC18sfzhm().equals(other.getC18sfzhm()))
            && (this.getcWhcd() == null ? other.getcWhcd() == null : this.getcWhcd().equals(other.getcWhcd()))
            && (this.getcFwcs() == null ? other.getcFwcs() == null : this.getcFwcs().equals(other.getcFwcs()))
            && (this.getcHjszd() == null ? other.getcHjszd() == null : this.getcHjszd().equals(other.getcHjszd()))
            && (this.getcHjpcs() == null ? other.getcHjpcs() == null : this.getcHjpcs().equals(other.getcHjpcs()))
            && (this.getcHjszdxz() == null ? other.getcHjszdxz() == null : this.getcHjszdxz().equals(other.getcHjszdxz()))
            && (this.getcSjjzd() == null ? other.getcSjjzd() == null : this.getcSjjzd().equals(other.getcSjjzd()))
            && (this.getcSjpcs() == null ? other.getcSjpcs() == null : this.getcSjpcs().equals(other.getcSjpcs()))
            && (this.getcSjjzdxz() == null ? other.getcSjjzdxz() == null : this.getcSjjzdxz().equals(other.getcSjjzdxz()))
            && (this.getcJyqk() == null ? other.getcJyqk() == null : this.getcJyqk().equals(other.getcJyqk()))
            && (this.getcXdhgst() == null ? other.getcXdhgst() == null : this.getcXdhgst().equals(other.getcXdhgst()))
            && (this.getcDna() == null ? other.getcDna() == null : this.getcDna().equals(other.getcDna()))
            && (this.getnYxx() == null ? other.getnYxx() == null : this.getnYxx().equals(other.getnYxx()))
            && (this.getcAction() == null ? other.getcAction() == null : this.getcAction().equals(other.getcAction()))
            && (this.getcTstamp() == null ? other.getcTstamp() == null : this.getcTstamp().equals(other.getcTstamp()))
            && (this.getcXgbsdw() == null ? other.getcXgbsdw() == null : this.getcXgbsdw().equals(other.getcXgbsdw()))
            && (this.getcCcbz() == null ? other.getcCcbz() == null : this.getcCcbz().equals(other.getcCcbz()))
            && (this.getcNccbz() == null ? other.getcNccbz() == null : this.getcNccbz().equals(other.getcNccbz()))
            && (this.getcDwdm() == null ? other.getcDwdm() == null : this.getcDwdm().equals(other.getcDwdm()))
            && (this.getcDjr() == null ? other.getcDjr() == null : this.getcDjr().equals(other.getcDjr()))
            && (this.getdDj() == null ? other.getdDj() == null : this.getdDj().equals(other.getdDj()))
            && (this.getnSf828k() == null ? other.getnSf828k() == null : this.getnSf828k().equals(other.getnSf828k()))
            && (this.getcBh() == null ? other.getcBh() == null : this.getcBh().equals(other.getcBh()))
            && (this.getnYxh() == null ? other.getnYxh() == null : this.getnYxh().equals(other.getnYxh()))
            && (this.getInoutbz() == null ? other.getInoutbz() == null : this.getInoutbz().equals(other.getInoutbz()))
            && (this.getcGsdw() == null ? other.getcGsdw() == null : this.getcGsdw().equals(other.getcGsdw()))
            && (this.getcHy() == null ? other.getcHy() == null : this.getcHy().equals(other.getcHy()))
            && (this.getcCyzk() == null ? other.getcCyzk() == null : this.getcCyzk().equals(other.getcCyzk()))
            && (this.getcRybs() == null ? other.getcRybs() == null : this.getcRybs().equals(other.getcRybs()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_XDRY
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getnXh() == null) ? 0 : getnXh().hashCode());
        result = prime * result + ((getcXdryly() == null) ? 0 : getcXdryly().hashCode());
        result = prime * result + ((getnYwxh() == null) ? 0 : getnYwxh().hashCode());
        result = prime * result + ((getcTname() == null) ? 0 : getcTname().hashCode());
        result = prime * result + ((getcRybh() == null) ? 0 : getcRybh().hashCode());
        result = prime * result + ((getcXm() == null) ? 0 : getcXm().hashCode());
        result = prime * result + ((getcCh() == null) ? 0 : getcCh().hashCode());
        result = prime * result + ((getcXb() == null) ? 0 : getcXb().hashCode());
        result = prime * result + ((getcMz() == null) ? 0 : getcMz().hashCode());
        result = prime * result + ((getdCs() == null) ? 0 : getdCs().hashCode());
        result = prime * result + ((getnSg() == null) ? 0 : getnSg().hashCode());
        result = prime * result + ((getcGj() == null) ? 0 : getcGj().hashCode());
        result = prime * result + ((getcSfzjzl() == null) ? 0 : getcSfzjzl().hashCode());
        result = prime * result + ((getcSfzhm() == null) ? 0 : getcSfzhm().hashCode());
        result = prime * result + ((getC18sfzhm() == null) ? 0 : getC18sfzhm().hashCode());
        result = prime * result + ((getcWhcd() == null) ? 0 : getcWhcd().hashCode());
        result = prime * result + ((getcFwcs() == null) ? 0 : getcFwcs().hashCode());
        result = prime * result + ((getcHjszd() == null) ? 0 : getcHjszd().hashCode());
        result = prime * result + ((getcHjpcs() == null) ? 0 : getcHjpcs().hashCode());
        result = prime * result + ((getcHjszdxz() == null) ? 0 : getcHjszdxz().hashCode());
        result = prime * result + ((getcSjjzd() == null) ? 0 : getcSjjzd().hashCode());
        result = prime * result + ((getcSjpcs() == null) ? 0 : getcSjpcs().hashCode());
        result = prime * result + ((getcSjjzdxz() == null) ? 0 : getcSjjzdxz().hashCode());
        result = prime * result + ((getcJyqk() == null) ? 0 : getcJyqk().hashCode());
        result = prime * result + ((getcXdhgst() == null) ? 0 : getcXdhgst().hashCode());
        result = prime * result + ((getcDna() == null) ? 0 : getcDna().hashCode());
        result = prime * result + ((getnYxx() == null) ? 0 : getnYxx().hashCode());
        result = prime * result + ((getcAction() == null) ? 0 : getcAction().hashCode());
        result = prime * result + ((getcTstamp() == null) ? 0 : getcTstamp().hashCode());
        result = prime * result + ((getcXgbsdw() == null) ? 0 : getcXgbsdw().hashCode());
        result = prime * result + ((getcCcbz() == null) ? 0 : getcCcbz().hashCode());
        result = prime * result + ((getcNccbz() == null) ? 0 : getcNccbz().hashCode());
        result = prime * result + ((getcDwdm() == null) ? 0 : getcDwdm().hashCode());
        result = prime * result + ((getcDjr() == null) ? 0 : getcDjr().hashCode());
        result = prime * result + ((getdDj() == null) ? 0 : getdDj().hashCode());
        result = prime * result + ((getnSf828k() == null) ? 0 : getnSf828k().hashCode());
        result = prime * result + ((getcBh() == null) ? 0 : getcBh().hashCode());
        result = prime * result + ((getnYxh() == null) ? 0 : getnYxh().hashCode());
        result = prime * result + ((getInoutbz() == null) ? 0 : getInoutbz().hashCode());
        result = prime * result + ((getcGsdw() == null) ? 0 : getcGsdw().hashCode());
        result = prime * result + ((getcHy() == null) ? 0 : getcHy().hashCode());
        result = prime * result + ((getcCyzk() == null) ? 0 : getcCyzk().hashCode());
        result = prime * result + ((getcRybs() == null) ? 0 : getcRybs().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_XDRY
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nXh=").append(nXh);
        sb.append(", cXdryly=").append(cXdryly);
        sb.append(", nYwxh=").append(nYwxh);
        sb.append(", cTname=").append(cTname);
        sb.append(", cRybh=").append(cRybh);
        sb.append(", cXm=").append(cXm);
        sb.append(", cCh=").append(cCh);
        sb.append(", cXb=").append(cXb);
        sb.append(", cMz=").append(cMz);
        sb.append(", dCs=").append(dCs);
        sb.append(", nSg=").append(nSg);
        sb.append(", cGj=").append(cGj);
        sb.append(", cSfzjzl=").append(cSfzjzl);
        sb.append(", cSfzhm=").append(cSfzhm);
        sb.append(", c18sfzhm=").append(c18sfzhm);
        sb.append(", cWhcd=").append(cWhcd);
        sb.append(", cFwcs=").append(cFwcs);
        sb.append(", cHjszd=").append(cHjszd);
        sb.append(", cHjpcs=").append(cHjpcs);
        sb.append(", cHjszdxz=").append(cHjszdxz);
        sb.append(", cSjjzd=").append(cSjjzd);
        sb.append(", cSjpcs=").append(cSjpcs);
        sb.append(", cSjjzdxz=").append(cSjjzdxz);
        sb.append(", cJyqk=").append(cJyqk);
        sb.append(", cXdhgst=").append(cXdhgst);
        sb.append(", cDna=").append(cDna);
        sb.append(", nYxx=").append(nYxx);
        sb.append(", cAction=").append(cAction);
        sb.append(", cTstamp=").append(cTstamp);
        sb.append(", cXgbsdw=").append(cXgbsdw);
        sb.append(", cCcbz=").append(cCcbz);
        sb.append(", cNccbz=").append(cNccbz);
        sb.append(", cDwdm=").append(cDwdm);
        sb.append(", cDjr=").append(cDjr);
        sb.append(", dDj=").append(dDj);
        sb.append(", nSf828k=").append(nSf828k);
        sb.append(", cBh=").append(cBh);
        sb.append(", nYxh=").append(nYxh);
        sb.append(", inoutbz=").append(inoutbz);
        sb.append(", cGsdw=").append(cGsdw);
        sb.append(", cHy=").append(cHy);
        sb.append(", cCyzk=").append(cCyzk);
        sb.append(", cRybs=").append(cRybs);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}