package com.zhixin.rd.rkjc.web.entity.qk;

public class JzptAjxyrclxx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.RR_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String rrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.AJ_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String ajId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.DEAL_CODE
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String dealCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.DEAL_DATE
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String dealDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.DEAL_UNIT
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String dealUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.LCFS
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String lcfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.MM_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String mmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.RR_STATE
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String rrState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.RR_STATE_TIME
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String rrStateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.SAAQMS
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String saaqms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.ZZ_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String zzId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.SBBS
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String sbbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.SBLX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String sblx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.RKSJ
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String rksj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.RSKSJ
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String rsksj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZPT_AJXYRCLXX.DEAL_RESULT
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    private String dealResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.RR_ID
     *
     * @return the value of JZPT_AJXYRCLXX.RR_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getRrId() {
        return rrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.RR_ID
     *
     * @param rrId the value for JZPT_AJXYRCLXX.RR_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setRrId(String rrId) {
        this.rrId = rrId == null ? null : rrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.AJ_ID
     *
     * @return the value of JZPT_AJXYRCLXX.AJ_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getAjId() {
        return ajId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.AJ_ID
     *
     * @param ajId the value for JZPT_AJXYRCLXX.AJ_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setAjId(String ajId) {
        this.ajId = ajId == null ? null : ajId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.DEAL_CODE
     *
     * @return the value of JZPT_AJXYRCLXX.DEAL_CODE
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getDealCode() {
        return dealCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.DEAL_CODE
     *
     * @param dealCode the value for JZPT_AJXYRCLXX.DEAL_CODE
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setDealCode(String dealCode) {
        this.dealCode = dealCode == null ? null : dealCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.DEAL_DATE
     *
     * @return the value of JZPT_AJXYRCLXX.DEAL_DATE
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getDealDate() {
        return dealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.DEAL_DATE
     *
     * @param dealDate the value for JZPT_AJXYRCLXX.DEAL_DATE
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setDealDate(String dealDate) {
        this.dealDate = dealDate == null ? null : dealDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.DEAL_UNIT
     *
     * @return the value of JZPT_AJXYRCLXX.DEAL_UNIT
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getDealUnit() {
        return dealUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.DEAL_UNIT
     *
     * @param dealUnit the value for JZPT_AJXYRCLXX.DEAL_UNIT
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setDealUnit(String dealUnit) {
        this.dealUnit = dealUnit == null ? null : dealUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.LCFS
     *
     * @return the value of JZPT_AJXYRCLXX.LCFS
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getLcfs() {
        return lcfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.LCFS
     *
     * @param lcfs the value for JZPT_AJXYRCLXX.LCFS
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setLcfs(String lcfs) {
        this.lcfs = lcfs == null ? null : lcfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.MM_ID
     *
     * @return the value of JZPT_AJXYRCLXX.MM_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getMmId() {
        return mmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.MM_ID
     *
     * @param mmId the value for JZPT_AJXYRCLXX.MM_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setMmId(String mmId) {
        this.mmId = mmId == null ? null : mmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.RR_STATE
     *
     * @return the value of JZPT_AJXYRCLXX.RR_STATE
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getRrState() {
        return rrState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.RR_STATE
     *
     * @param rrState the value for JZPT_AJXYRCLXX.RR_STATE
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setRrState(String rrState) {
        this.rrState = rrState == null ? null : rrState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.RR_STATE_TIME
     *
     * @return the value of JZPT_AJXYRCLXX.RR_STATE_TIME
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getRrStateTime() {
        return rrStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.RR_STATE_TIME
     *
     * @param rrStateTime the value for JZPT_AJXYRCLXX.RR_STATE_TIME
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setRrStateTime(String rrStateTime) {
        this.rrStateTime = rrStateTime == null ? null : rrStateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.SAAQMS
     *
     * @return the value of JZPT_AJXYRCLXX.SAAQMS
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getSaaqms() {
        return saaqms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.SAAQMS
     *
     * @param saaqms the value for JZPT_AJXYRCLXX.SAAQMS
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setSaaqms(String saaqms) {
        this.saaqms = saaqms == null ? null : saaqms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.ZZ_ID
     *
     * @return the value of JZPT_AJXYRCLXX.ZZ_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getZzId() {
        return zzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.ZZ_ID
     *
     * @param zzId the value for JZPT_AJXYRCLXX.ZZ_ID
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setZzId(String zzId) {
        this.zzId = zzId == null ? null : zzId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.SBBS
     *
     * @return the value of JZPT_AJXYRCLXX.SBBS
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getSbbs() {
        return sbbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.SBBS
     *
     * @param sbbs the value for JZPT_AJXYRCLXX.SBBS
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setSbbs(String sbbs) {
        this.sbbs = sbbs == null ? null : sbbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.SBLX
     *
     * @return the value of JZPT_AJXYRCLXX.SBLX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getSblx() {
        return sblx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.SBLX
     *
     * @param sblx the value for JZPT_AJXYRCLXX.SBLX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setSblx(String sblx) {
        this.sblx = sblx == null ? null : sblx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.RKSJ
     *
     * @return the value of JZPT_AJXYRCLXX.RKSJ
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getRksj() {
        return rksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.RKSJ
     *
     * @param rksj the value for JZPT_AJXYRCLXX.RKSJ
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setRksj(String rksj) {
        this.rksj = rksj == null ? null : rksj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.RSKSJ
     *
     * @return the value of JZPT_AJXYRCLXX.RSKSJ
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getRsksj() {
        return rsksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.RSKSJ
     *
     * @param rsksj the value for JZPT_AJXYRCLXX.RSKSJ
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setRsksj(String rsksj) {
        this.rsksj = rsksj == null ? null : rsksj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZPT_AJXYRCLXX.DEAL_RESULT
     *
     * @return the value of JZPT_AJXYRCLXX.DEAL_RESULT
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getDealResult() {
        return dealResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZPT_AJXYRCLXX.DEAL_RESULT
     *
     * @param dealResult the value for JZPT_AJXYRCLXX.DEAL_RESULT
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setDealResult(String dealResult) {
        this.dealResult = dealResult == null ? null : dealResult.trim();
    }
}