package com.zhixin.rd.rkjc.web.entity.qk;

import java.util.ArrayList;
import java.util.List;

public class JzptAjxyrclxxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public JzptAjxyrclxxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRrIdIsNull() {
            addCriterion("RR_ID is null");
            return (Criteria) this;
        }

        public Criteria andRrIdIsNotNull() {
            addCriterion("RR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRrIdEqualTo(String value) {
            addCriterion("RR_ID =", value, "rrId");
            return (Criteria) this;
        }

        public Criteria andRrIdNotEqualTo(String value) {
            addCriterion("RR_ID <>", value, "rrId");
            return (Criteria) this;
        }

        public Criteria andRrIdGreaterThan(String value) {
            addCriterion("RR_ID >", value, "rrId");
            return (Criteria) this;
        }

        public Criteria andRrIdGreaterThanOrEqualTo(String value) {
            addCriterion("RR_ID >=", value, "rrId");
            return (Criteria) this;
        }

        public Criteria andRrIdLessThan(String value) {
            addCriterion("RR_ID <", value, "rrId");
            return (Criteria) this;
        }

        public Criteria andRrIdLessThanOrEqualTo(String value) {
            addCriterion("RR_ID <=", value, "rrId");
            return (Criteria) this;
        }

        public Criteria andRrIdLike(String value) {
            addCriterion("RR_ID like", value, "rrId");
            return (Criteria) this;
        }

        public Criteria andRrIdNotLike(String value) {
            addCriterion("RR_ID not like", value, "rrId");
            return (Criteria) this;
        }

        public Criteria andRrIdIn(List<String> values) {
            addCriterion("RR_ID in", values, "rrId");
            return (Criteria) this;
        }

        public Criteria andRrIdNotIn(List<String> values) {
            addCriterion("RR_ID not in", values, "rrId");
            return (Criteria) this;
        }

        public Criteria andRrIdBetween(String value1, String value2) {
            addCriterion("RR_ID between", value1, value2, "rrId");
            return (Criteria) this;
        }

        public Criteria andRrIdNotBetween(String value1, String value2) {
            addCriterion("RR_ID not between", value1, value2, "rrId");
            return (Criteria) this;
        }

        public Criteria andAjIdIsNull() {
            addCriterion("AJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andAjIdIsNotNull() {
            addCriterion("AJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAjIdEqualTo(String value) {
            addCriterion("AJ_ID =", value, "ajId");
            return (Criteria) this;
        }

        public Criteria andAjIdNotEqualTo(String value) {
            addCriterion("AJ_ID <>", value, "ajId");
            return (Criteria) this;
        }

        public Criteria andAjIdGreaterThan(String value) {
            addCriterion("AJ_ID >", value, "ajId");
            return (Criteria) this;
        }

        public Criteria andAjIdGreaterThanOrEqualTo(String value) {
            addCriterion("AJ_ID >=", value, "ajId");
            return (Criteria) this;
        }

        public Criteria andAjIdLessThan(String value) {
            addCriterion("AJ_ID <", value, "ajId");
            return (Criteria) this;
        }

        public Criteria andAjIdLessThanOrEqualTo(String value) {
            addCriterion("AJ_ID <=", value, "ajId");
            return (Criteria) this;
        }

        public Criteria andAjIdLike(String value) {
            addCriterion("AJ_ID like", value, "ajId");
            return (Criteria) this;
        }

        public Criteria andAjIdNotLike(String value) {
            addCriterion("AJ_ID not like", value, "ajId");
            return (Criteria) this;
        }

        public Criteria andAjIdIn(List<String> values) {
            addCriterion("AJ_ID in", values, "ajId");
            return (Criteria) this;
        }

        public Criteria andAjIdNotIn(List<String> values) {
            addCriterion("AJ_ID not in", values, "ajId");
            return (Criteria) this;
        }

        public Criteria andAjIdBetween(String value1, String value2) {
            addCriterion("AJ_ID between", value1, value2, "ajId");
            return (Criteria) this;
        }

        public Criteria andAjIdNotBetween(String value1, String value2) {
            addCriterion("AJ_ID not between", value1, value2, "ajId");
            return (Criteria) this;
        }

        public Criteria andDealCodeIsNull() {
            addCriterion("DEAL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andDealCodeIsNotNull() {
            addCriterion("DEAL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andDealCodeEqualTo(String value) {
            addCriterion("DEAL_CODE =", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeNotEqualTo(String value) {
            addCriterion("DEAL_CODE <>", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeGreaterThan(String value) {
            addCriterion("DEAL_CODE >", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeGreaterThanOrEqualTo(String value) {
            addCriterion("DEAL_CODE >=", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeLessThan(String value) {
            addCriterion("DEAL_CODE <", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeLessThanOrEqualTo(String value) {
            addCriterion("DEAL_CODE <=", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeLike(String value) {
            addCriterion("DEAL_CODE like", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeNotLike(String value) {
            addCriterion("DEAL_CODE not like", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeIn(List<String> values) {
            addCriterion("DEAL_CODE in", values, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeNotIn(List<String> values) {
            addCriterion("DEAL_CODE not in", values, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeBetween(String value1, String value2) {
            addCriterion("DEAL_CODE between", value1, value2, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeNotBetween(String value1, String value2) {
            addCriterion("DEAL_CODE not between", value1, value2, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealDateIsNull() {
            addCriterion("DEAL_DATE is null");
            return (Criteria) this;
        }

        public Criteria andDealDateIsNotNull() {
            addCriterion("DEAL_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andDealDateEqualTo(String value) {
            addCriterion("DEAL_DATE =", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotEqualTo(String value) {
            addCriterion("DEAL_DATE <>", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateGreaterThan(String value) {
            addCriterion("DEAL_DATE >", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateGreaterThanOrEqualTo(String value) {
            addCriterion("DEAL_DATE >=", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateLessThan(String value) {
            addCriterion("DEAL_DATE <", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateLessThanOrEqualTo(String value) {
            addCriterion("DEAL_DATE <=", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateLike(String value) {
            addCriterion("DEAL_DATE like", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotLike(String value) {
            addCriterion("DEAL_DATE not like", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateIn(List<String> values) {
            addCriterion("DEAL_DATE in", values, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotIn(List<String> values) {
            addCriterion("DEAL_DATE not in", values, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateBetween(String value1, String value2) {
            addCriterion("DEAL_DATE between", value1, value2, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotBetween(String value1, String value2) {
            addCriterion("DEAL_DATE not between", value1, value2, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealUnitIsNull() {
            addCriterion("DEAL_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andDealUnitIsNotNull() {
            addCriterion("DEAL_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andDealUnitEqualTo(String value) {
            addCriterion("DEAL_UNIT =", value, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andDealUnitNotEqualTo(String value) {
            addCriterion("DEAL_UNIT <>", value, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andDealUnitGreaterThan(String value) {
            addCriterion("DEAL_UNIT >", value, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andDealUnitGreaterThanOrEqualTo(String value) {
            addCriterion("DEAL_UNIT >=", value, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andDealUnitLessThan(String value) {
            addCriterion("DEAL_UNIT <", value, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andDealUnitLessThanOrEqualTo(String value) {
            addCriterion("DEAL_UNIT <=", value, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andDealUnitLike(String value) {
            addCriterion("DEAL_UNIT like", value, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andDealUnitNotLike(String value) {
            addCriterion("DEAL_UNIT not like", value, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andDealUnitIn(List<String> values) {
            addCriterion("DEAL_UNIT in", values, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andDealUnitNotIn(List<String> values) {
            addCriterion("DEAL_UNIT not in", values, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andDealUnitBetween(String value1, String value2) {
            addCriterion("DEAL_UNIT between", value1, value2, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andDealUnitNotBetween(String value1, String value2) {
            addCriterion("DEAL_UNIT not between", value1, value2, "dealUnit");
            return (Criteria) this;
        }

        public Criteria andLcfsIsNull() {
            addCriterion("LCFS is null");
            return (Criteria) this;
        }

        public Criteria andLcfsIsNotNull() {
            addCriterion("LCFS is not null");
            return (Criteria) this;
        }

        public Criteria andLcfsEqualTo(String value) {
            addCriterion("LCFS =", value, "lcfs");
            return (Criteria) this;
        }

        public Criteria andLcfsNotEqualTo(String value) {
            addCriterion("LCFS <>", value, "lcfs");
            return (Criteria) this;
        }

        public Criteria andLcfsGreaterThan(String value) {
            addCriterion("LCFS >", value, "lcfs");
            return (Criteria) this;
        }

        public Criteria andLcfsGreaterThanOrEqualTo(String value) {
            addCriterion("LCFS >=", value, "lcfs");
            return (Criteria) this;
        }

        public Criteria andLcfsLessThan(String value) {
            addCriterion("LCFS <", value, "lcfs");
            return (Criteria) this;
        }

        public Criteria andLcfsLessThanOrEqualTo(String value) {
            addCriterion("LCFS <=", value, "lcfs");
            return (Criteria) this;
        }

        public Criteria andLcfsLike(String value) {
            addCriterion("LCFS like", value, "lcfs");
            return (Criteria) this;
        }

        public Criteria andLcfsNotLike(String value) {
            addCriterion("LCFS not like", value, "lcfs");
            return (Criteria) this;
        }

        public Criteria andLcfsIn(List<String> values) {
            addCriterion("LCFS in", values, "lcfs");
            return (Criteria) this;
        }

        public Criteria andLcfsNotIn(List<String> values) {
            addCriterion("LCFS not in", values, "lcfs");
            return (Criteria) this;
        }

        public Criteria andLcfsBetween(String value1, String value2) {
            addCriterion("LCFS between", value1, value2, "lcfs");
            return (Criteria) this;
        }

        public Criteria andLcfsNotBetween(String value1, String value2) {
            addCriterion("LCFS not between", value1, value2, "lcfs");
            return (Criteria) this;
        }

        public Criteria andMmIdIsNull() {
            addCriterion("MM_ID is null");
            return (Criteria) this;
        }

        public Criteria andMmIdIsNotNull() {
            addCriterion("MM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMmIdEqualTo(String value) {
            addCriterion("MM_ID =", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdNotEqualTo(String value) {
            addCriterion("MM_ID <>", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdGreaterThan(String value) {
            addCriterion("MM_ID >", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdGreaterThanOrEqualTo(String value) {
            addCriterion("MM_ID >=", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdLessThan(String value) {
            addCriterion("MM_ID <", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdLessThanOrEqualTo(String value) {
            addCriterion("MM_ID <=", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdLike(String value) {
            addCriterion("MM_ID like", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdNotLike(String value) {
            addCriterion("MM_ID not like", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdIn(List<String> values) {
            addCriterion("MM_ID in", values, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdNotIn(List<String> values) {
            addCriterion("MM_ID not in", values, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdBetween(String value1, String value2) {
            addCriterion("MM_ID between", value1, value2, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdNotBetween(String value1, String value2) {
            addCriterion("MM_ID not between", value1, value2, "mmId");
            return (Criteria) this;
        }

        public Criteria andRrStateIsNull() {
            addCriterion("RR_STATE is null");
            return (Criteria) this;
        }

        public Criteria andRrStateIsNotNull() {
            addCriterion("RR_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andRrStateEqualTo(String value) {
            addCriterion("RR_STATE =", value, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateNotEqualTo(String value) {
            addCriterion("RR_STATE <>", value, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateGreaterThan(String value) {
            addCriterion("RR_STATE >", value, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateGreaterThanOrEqualTo(String value) {
            addCriterion("RR_STATE >=", value, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateLessThan(String value) {
            addCriterion("RR_STATE <", value, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateLessThanOrEqualTo(String value) {
            addCriterion("RR_STATE <=", value, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateLike(String value) {
            addCriterion("RR_STATE like", value, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateNotLike(String value) {
            addCriterion("RR_STATE not like", value, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateIn(List<String> values) {
            addCriterion("RR_STATE in", values, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateNotIn(List<String> values) {
            addCriterion("RR_STATE not in", values, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateBetween(String value1, String value2) {
            addCriterion("RR_STATE between", value1, value2, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateNotBetween(String value1, String value2) {
            addCriterion("RR_STATE not between", value1, value2, "rrState");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeIsNull() {
            addCriterion("RR_STATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeIsNotNull() {
            addCriterion("RR_STATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeEqualTo(String value) {
            addCriterion("RR_STATE_TIME =", value, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeNotEqualTo(String value) {
            addCriterion("RR_STATE_TIME <>", value, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeGreaterThan(String value) {
            addCriterion("RR_STATE_TIME >", value, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("RR_STATE_TIME >=", value, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeLessThan(String value) {
            addCriterion("RR_STATE_TIME <", value, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeLessThanOrEqualTo(String value) {
            addCriterion("RR_STATE_TIME <=", value, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeLike(String value) {
            addCriterion("RR_STATE_TIME like", value, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeNotLike(String value) {
            addCriterion("RR_STATE_TIME not like", value, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeIn(List<String> values) {
            addCriterion("RR_STATE_TIME in", values, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeNotIn(List<String> values) {
            addCriterion("RR_STATE_TIME not in", values, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeBetween(String value1, String value2) {
            addCriterion("RR_STATE_TIME between", value1, value2, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andRrStateTimeNotBetween(String value1, String value2) {
            addCriterion("RR_STATE_TIME not between", value1, value2, "rrStateTime");
            return (Criteria) this;
        }

        public Criteria andSaaqmsIsNull() {
            addCriterion("SAAQMS is null");
            return (Criteria) this;
        }

        public Criteria andSaaqmsIsNotNull() {
            addCriterion("SAAQMS is not null");
            return (Criteria) this;
        }

        public Criteria andSaaqmsEqualTo(String value) {
            addCriterion("SAAQMS =", value, "saaqms");
            return (Criteria) this;
        }

        public Criteria andSaaqmsNotEqualTo(String value) {
            addCriterion("SAAQMS <>", value, "saaqms");
            return (Criteria) this;
        }

        public Criteria andSaaqmsGreaterThan(String value) {
            addCriterion("SAAQMS >", value, "saaqms");
            return (Criteria) this;
        }

        public Criteria andSaaqmsGreaterThanOrEqualTo(String value) {
            addCriterion("SAAQMS >=", value, "saaqms");
            return (Criteria) this;
        }

        public Criteria andSaaqmsLessThan(String value) {
            addCriterion("SAAQMS <", value, "saaqms");
            return (Criteria) this;
        }

        public Criteria andSaaqmsLessThanOrEqualTo(String value) {
            addCriterion("SAAQMS <=", value, "saaqms");
            return (Criteria) this;
        }

        public Criteria andSaaqmsLike(String value) {
            addCriterion("SAAQMS like", value, "saaqms");
            return (Criteria) this;
        }

        public Criteria andSaaqmsNotLike(String value) {
            addCriterion("SAAQMS not like", value, "saaqms");
            return (Criteria) this;
        }

        public Criteria andSaaqmsIn(List<String> values) {
            addCriterion("SAAQMS in", values, "saaqms");
            return (Criteria) this;
        }

        public Criteria andSaaqmsNotIn(List<String> values) {
            addCriterion("SAAQMS not in", values, "saaqms");
            return (Criteria) this;
        }

        public Criteria andSaaqmsBetween(String value1, String value2) {
            addCriterion("SAAQMS between", value1, value2, "saaqms");
            return (Criteria) this;
        }

        public Criteria andSaaqmsNotBetween(String value1, String value2) {
            addCriterion("SAAQMS not between", value1, value2, "saaqms");
            return (Criteria) this;
        }

        public Criteria andZzIdIsNull() {
            addCriterion("ZZ_ID is null");
            return (Criteria) this;
        }

        public Criteria andZzIdIsNotNull() {
            addCriterion("ZZ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andZzIdEqualTo(String value) {
            addCriterion("ZZ_ID =", value, "zzId");
            return (Criteria) this;
        }

        public Criteria andZzIdNotEqualTo(String value) {
            addCriterion("ZZ_ID <>", value, "zzId");
            return (Criteria) this;
        }

        public Criteria andZzIdGreaterThan(String value) {
            addCriterion("ZZ_ID >", value, "zzId");
            return (Criteria) this;
        }

        public Criteria andZzIdGreaterThanOrEqualTo(String value) {
            addCriterion("ZZ_ID >=", value, "zzId");
            return (Criteria) this;
        }

        public Criteria andZzIdLessThan(String value) {
            addCriterion("ZZ_ID <", value, "zzId");
            return (Criteria) this;
        }

        public Criteria andZzIdLessThanOrEqualTo(String value) {
            addCriterion("ZZ_ID <=", value, "zzId");
            return (Criteria) this;
        }

        public Criteria andZzIdLike(String value) {
            addCriterion("ZZ_ID like", value, "zzId");
            return (Criteria) this;
        }

        public Criteria andZzIdNotLike(String value) {
            addCriterion("ZZ_ID not like", value, "zzId");
            return (Criteria) this;
        }

        public Criteria andZzIdIn(List<String> values) {
            addCriterion("ZZ_ID in", values, "zzId");
            return (Criteria) this;
        }

        public Criteria andZzIdNotIn(List<String> values) {
            addCriterion("ZZ_ID not in", values, "zzId");
            return (Criteria) this;
        }

        public Criteria andZzIdBetween(String value1, String value2) {
            addCriterion("ZZ_ID between", value1, value2, "zzId");
            return (Criteria) this;
        }

        public Criteria andZzIdNotBetween(String value1, String value2) {
            addCriterion("ZZ_ID not between", value1, value2, "zzId");
            return (Criteria) this;
        }

        public Criteria andSbbsIsNull() {
            addCriterion("SBBS is null");
            return (Criteria) this;
        }

        public Criteria andSbbsIsNotNull() {
            addCriterion("SBBS is not null");
            return (Criteria) this;
        }

        public Criteria andSbbsEqualTo(String value) {
            addCriterion("SBBS =", value, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSbbsNotEqualTo(String value) {
            addCriterion("SBBS <>", value, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSbbsGreaterThan(String value) {
            addCriterion("SBBS >", value, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSbbsGreaterThanOrEqualTo(String value) {
            addCriterion("SBBS >=", value, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSbbsLessThan(String value) {
            addCriterion("SBBS <", value, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSbbsLessThanOrEqualTo(String value) {
            addCriterion("SBBS <=", value, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSbbsLike(String value) {
            addCriterion("SBBS like", value, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSbbsNotLike(String value) {
            addCriterion("SBBS not like", value, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSbbsIn(List<String> values) {
            addCriterion("SBBS in", values, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSbbsNotIn(List<String> values) {
            addCriterion("SBBS not in", values, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSbbsBetween(String value1, String value2) {
            addCriterion("SBBS between", value1, value2, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSbbsNotBetween(String value1, String value2) {
            addCriterion("SBBS not between", value1, value2, "sbbs");
            return (Criteria) this;
        }

        public Criteria andSblxIsNull() {
            addCriterion("SBLX is null");
            return (Criteria) this;
        }

        public Criteria andSblxIsNotNull() {
            addCriterion("SBLX is not null");
            return (Criteria) this;
        }

        public Criteria andSblxEqualTo(String value) {
            addCriterion("SBLX =", value, "sblx");
            return (Criteria) this;
        }

        public Criteria andSblxNotEqualTo(String value) {
            addCriterion("SBLX <>", value, "sblx");
            return (Criteria) this;
        }

        public Criteria andSblxGreaterThan(String value) {
            addCriterion("SBLX >", value, "sblx");
            return (Criteria) this;
        }

        public Criteria andSblxGreaterThanOrEqualTo(String value) {
            addCriterion("SBLX >=", value, "sblx");
            return (Criteria) this;
        }

        public Criteria andSblxLessThan(String value) {
            addCriterion("SBLX <", value, "sblx");
            return (Criteria) this;
        }

        public Criteria andSblxLessThanOrEqualTo(String value) {
            addCriterion("SBLX <=", value, "sblx");
            return (Criteria) this;
        }

        public Criteria andSblxLike(String value) {
            addCriterion("SBLX like", value, "sblx");
            return (Criteria) this;
        }

        public Criteria andSblxNotLike(String value) {
            addCriterion("SBLX not like", value, "sblx");
            return (Criteria) this;
        }

        public Criteria andSblxIn(List<String> values) {
            addCriterion("SBLX in", values, "sblx");
            return (Criteria) this;
        }

        public Criteria andSblxNotIn(List<String> values) {
            addCriterion("SBLX not in", values, "sblx");
            return (Criteria) this;
        }

        public Criteria andSblxBetween(String value1, String value2) {
            addCriterion("SBLX between", value1, value2, "sblx");
            return (Criteria) this;
        }

        public Criteria andSblxNotBetween(String value1, String value2) {
            addCriterion("SBLX not between", value1, value2, "sblx");
            return (Criteria) this;
        }

        public Criteria andRksjIsNull() {
            addCriterion("RKSJ is null");
            return (Criteria) this;
        }

        public Criteria andRksjIsNotNull() {
            addCriterion("RKSJ is not null");
            return (Criteria) this;
        }

        public Criteria andRksjEqualTo(String value) {
            addCriterion("RKSJ =", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotEqualTo(String value) {
            addCriterion("RKSJ <>", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjGreaterThan(String value) {
            addCriterion("RKSJ >", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjGreaterThanOrEqualTo(String value) {
            addCriterion("RKSJ >=", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjLessThan(String value) {
            addCriterion("RKSJ <", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjLessThanOrEqualTo(String value) {
            addCriterion("RKSJ <=", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjLike(String value) {
            addCriterion("RKSJ like", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotLike(String value) {
            addCriterion("RKSJ not like", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjIn(List<String> values) {
            addCriterion("RKSJ in", values, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotIn(List<String> values) {
            addCriterion("RKSJ not in", values, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjBetween(String value1, String value2) {
            addCriterion("RKSJ between", value1, value2, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotBetween(String value1, String value2) {
            addCriterion("RKSJ not between", value1, value2, "rksj");
            return (Criteria) this;
        }

        public Criteria andRsksjIsNull() {
            addCriterion("RSKSJ is null");
            return (Criteria) this;
        }

        public Criteria andRsksjIsNotNull() {
            addCriterion("RSKSJ is not null");
            return (Criteria) this;
        }

        public Criteria andRsksjEqualTo(String value) {
            addCriterion("RSKSJ =", value, "rsksj");
            return (Criteria) this;
        }

        public Criteria andRsksjNotEqualTo(String value) {
            addCriterion("RSKSJ <>", value, "rsksj");
            return (Criteria) this;
        }

        public Criteria andRsksjGreaterThan(String value) {
            addCriterion("RSKSJ >", value, "rsksj");
            return (Criteria) this;
        }

        public Criteria andRsksjGreaterThanOrEqualTo(String value) {
            addCriterion("RSKSJ >=", value, "rsksj");
            return (Criteria) this;
        }

        public Criteria andRsksjLessThan(String value) {
            addCriterion("RSKSJ <", value, "rsksj");
            return (Criteria) this;
        }

        public Criteria andRsksjLessThanOrEqualTo(String value) {
            addCriterion("RSKSJ <=", value, "rsksj");
            return (Criteria) this;
        }

        public Criteria andRsksjLike(String value) {
            addCriterion("RSKSJ like", value, "rsksj");
            return (Criteria) this;
        }

        public Criteria andRsksjNotLike(String value) {
            addCriterion("RSKSJ not like", value, "rsksj");
            return (Criteria) this;
        }

        public Criteria andRsksjIn(List<String> values) {
            addCriterion("RSKSJ in", values, "rsksj");
            return (Criteria) this;
        }

        public Criteria andRsksjNotIn(List<String> values) {
            addCriterion("RSKSJ not in", values, "rsksj");
            return (Criteria) this;
        }

        public Criteria andRsksjBetween(String value1, String value2) {
            addCriterion("RSKSJ between", value1, value2, "rsksj");
            return (Criteria) this;
        }

        public Criteria andRsksjNotBetween(String value1, String value2) {
            addCriterion("RSKSJ not between", value1, value2, "rsksj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated do_not_delete_during_merge Sat Aug 12 20:14:43 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JZPT_AJXYRCLXX
     *
     * @mbg.generated Sat Aug 12 20:14:43 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}