package com.zhixin.rd.rkjc.web.entity.qk;

import java.io.Serializable;
import java.util.Date;

public class QgZtryJbxx implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.CSRQ_SX
     *
     * @mbggenerated
     */
    private Date csrqSx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.CSRQ_XX
     *
     * @mbggenerated
     */
    private Date csrqXx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SFZH
     *
     * @mbggenerated
     */
    private String sfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.TPRQ
     *
     * @mbggenerated
     */
    private Date tprq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.LASJ
     *
     * @mbggenerated
     */
    private Date lasj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.DJ_RQ
     *
     * @mbggenerated
     */
    private Date djRq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.LRSJ
     *
     * @mbggenerated
     */
    private Date lrsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.XGSJ
     *
     * @mbggenerated
     */
    private Date xgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SCSJ
     *
     * @mbggenerated
     */
    private Date scsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.RBKSJ_DJ
     *
     * @mbggenerated
     */
    private Date rbksjDj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.RBKSJ_CX
     *
     * @mbggenerated
     */
    private Date rbksjCx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.RBKSJ_SC
     *
     * @mbggenerated
     */
    private Date rbksjSc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SBSJ
     *
     * @mbggenerated
     */
    private Date sbsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.JRYBH
     *
     * @mbggenerated
     */
    private String jrybh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.XB_DM
     *
     * @mbggenerated
     */
    private String xbDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.MZ_DM
     *
     * @mbggenerated
     */
    private String mzDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.JG_QH
     *
     * @mbggenerated
     */
    private String jgQh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.ZWBH
     *
     * @mbggenerated
     */
    private String zwbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.TPFX_QH
     *
     * @mbggenerated
     */
    private String tpfxQh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.LA_DWQH
     *
     * @mbggenerated
     */
    private String laDwqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.LA_DWDM
     *
     * @mbggenerated
     */
    private String laDwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.LA_DWXT_DM
     *
     * @mbggenerated
     */
    private String laDwxtDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.ZB_DWQH
     *
     * @mbggenerated
     */
    private String zbDwqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.ZB_DWDM
     *
     * @mbggenerated
     */
    private String zbDwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.DBJB_DM
     *
     * @mbggenerated
     */
    private String dbjbDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.BLYY
     *
     * @mbggenerated
     */
    private String blyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.BLBS
     *
     * @mbggenerated
     */
    private String blbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SP
     *
     * @mbggenerated
     */
    private String sp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.LR_DWDM
     *
     * @mbggenerated
     */
    private String lrDwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.XG_DWDM
     *
     * @mbggenerated
     */
    private String xgDwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SC_DWXC
     *
     * @mbggenerated
     */
    private String scDwxc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SC_DWXT_DM
     *
     * @mbggenerated
     */
    private String scDwxtDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SC_SPR
     *
     * @mbggenerated
     */
    private String scSpr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SY_DWDM
     *
     * @mbggenerated
     */
    private String syDwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.RYID
     *
     * @mbggenerated
     */
    private String ryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.RYBH
     *
     * @mbggenerated
     */
    private String rybh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.XM
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.KY_DM
     *
     * @mbggenerated
     */
    private String kyDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.ZY_DM
     *
     * @mbggenerated
     */
    private String zyDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.HJD_QH
     *
     * @mbggenerated
     */
    private String hjdQh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.HJD_XZ
     *
     * @mbggenerated
     */
    private String hjdXz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.XZD_QH
     *
     * @mbggenerated
     */
    private String xzdQh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.XZD_XZ
     *
     * @mbggenerated
     */
    private String xzdXz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.JG_XZ
     *
     * @mbggenerated
     */
    private String jgXz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.DNA
     *
     * @mbggenerated
     */
    private String dna;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.RYFJXX
     *
     * @mbggenerated
     */
    private String ryfjxx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.AJBH
     *
     * @mbggenerated
     */
    private String ajbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.AJLB_DM
     *
     * @mbggenerated
     */
    private String ajlbDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.ZTLX_DM
     *
     * @mbggenerated
     */
    private String ztlxDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.JYAQ
     *
     * @mbggenerated
     */
    private String jyaq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.LA_DWXC
     *
     * @mbggenerated
     */
    private String laDwxc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.ZB_DWXC
     *
     * @mbggenerated
     */
    private String zbDwxc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.ZB_LXR
     *
     * @mbggenerated
     */
    private String zbLxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.ZB_LXFS
     *
     * @mbggenerated
     */
    private String zbLxfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.DJ_TBR
     *
     * @mbggenerated
     */
    private String djTbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.DJ_SPR
     *
     * @mbggenerated
     */
    private String djSpr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.TJLBH
     *
     * @mbggenerated
     */
    private String tjlbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SPYY
     *
     * @mbggenerated
     */
    private String spyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.LRR
     *
     * @mbggenerated
     */
    private String lrr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.XGR
     *
     * @mbggenerated
     */
    private String xgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SC_DWDM
     *
     * @mbggenerated
     */
    private String scDwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SCR
     *
     * @mbggenerated
     */
    private String scr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.ZKBZ
     *
     * @mbggenerated
     */
    private String zkbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.SG
     *
     * @mbggenerated
     */
    private Long sg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QG_ZTRY_JBXX.JJ
     *
     * @mbggenerated
     */
    private Long jj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QG_ZTRY_JBXX
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.CSRQ_SX
     *
     * @return the value of QG_ZTRY_JBXX.CSRQ_SX
     *
     * @mbggenerated
     */
    public Date getCsrqSx() {
        return csrqSx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.CSRQ_SX
     *
     * @param csrqSx the value for QG_ZTRY_JBXX.CSRQ_SX
     *
     * @mbggenerated
     */
    public void setCsrqSx(Date csrqSx) {
        this.csrqSx = csrqSx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.CSRQ_XX
     *
     * @return the value of QG_ZTRY_JBXX.CSRQ_XX
     *
     * @mbggenerated
     */
    public Date getCsrqXx() {
        return csrqXx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.CSRQ_XX
     *
     * @param csrqXx the value for QG_ZTRY_JBXX.CSRQ_XX
     *
     * @mbggenerated
     */
    public void setCsrqXx(Date csrqXx) {
        this.csrqXx = csrqXx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SFZH
     *
     * @return the value of QG_ZTRY_JBXX.SFZH
     *
     * @mbggenerated
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SFZH
     *
     * @param sfzh the value for QG_ZTRY_JBXX.SFZH
     *
     * @mbggenerated
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.TPRQ
     *
     * @return the value of QG_ZTRY_JBXX.TPRQ
     *
     * @mbggenerated
     */
    public Date getTprq() {
        return tprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.TPRQ
     *
     * @param tprq the value for QG_ZTRY_JBXX.TPRQ
     *
     * @mbggenerated
     */
    public void setTprq(Date tprq) {
        this.tprq = tprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.LASJ
     *
     * @return the value of QG_ZTRY_JBXX.LASJ
     *
     * @mbggenerated
     */
    public Date getLasj() {
        return lasj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.LASJ
     *
     * @param lasj the value for QG_ZTRY_JBXX.LASJ
     *
     * @mbggenerated
     */
    public void setLasj(Date lasj) {
        this.lasj = lasj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.DJ_RQ
     *
     * @return the value of QG_ZTRY_JBXX.DJ_RQ
     *
     * @mbggenerated
     */
    public Date getDjRq() {
        return djRq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.DJ_RQ
     *
     * @param djRq the value for QG_ZTRY_JBXX.DJ_RQ
     *
     * @mbggenerated
     */
    public void setDjRq(Date djRq) {
        this.djRq = djRq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.LRSJ
     *
     * @return the value of QG_ZTRY_JBXX.LRSJ
     *
     * @mbggenerated
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.LRSJ
     *
     * @param lrsj the value for QG_ZTRY_JBXX.LRSJ
     *
     * @mbggenerated
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.XGSJ
     *
     * @return the value of QG_ZTRY_JBXX.XGSJ
     *
     * @mbggenerated
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.XGSJ
     *
     * @param xgsj the value for QG_ZTRY_JBXX.XGSJ
     *
     * @mbggenerated
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SCSJ
     *
     * @return the value of QG_ZTRY_JBXX.SCSJ
     *
     * @mbggenerated
     */
    public Date getScsj() {
        return scsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SCSJ
     *
     * @param scsj the value for QG_ZTRY_JBXX.SCSJ
     *
     * @mbggenerated
     */
    public void setScsj(Date scsj) {
        this.scsj = scsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.RBKSJ_DJ
     *
     * @return the value of QG_ZTRY_JBXX.RBKSJ_DJ
     *
     * @mbggenerated
     */
    public Date getRbksjDj() {
        return rbksjDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.RBKSJ_DJ
     *
     * @param rbksjDj the value for QG_ZTRY_JBXX.RBKSJ_DJ
     *
     * @mbggenerated
     */
    public void setRbksjDj(Date rbksjDj) {
        this.rbksjDj = rbksjDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.RBKSJ_CX
     *
     * @return the value of QG_ZTRY_JBXX.RBKSJ_CX
     *
     * @mbggenerated
     */
    public Date getRbksjCx() {
        return rbksjCx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.RBKSJ_CX
     *
     * @param rbksjCx the value for QG_ZTRY_JBXX.RBKSJ_CX
     *
     * @mbggenerated
     */
    public void setRbksjCx(Date rbksjCx) {
        this.rbksjCx = rbksjCx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.RBKSJ_SC
     *
     * @return the value of QG_ZTRY_JBXX.RBKSJ_SC
     *
     * @mbggenerated
     */
    public Date getRbksjSc() {
        return rbksjSc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.RBKSJ_SC
     *
     * @param rbksjSc the value for QG_ZTRY_JBXX.RBKSJ_SC
     *
     * @mbggenerated
     */
    public void setRbksjSc(Date rbksjSc) {
        this.rbksjSc = rbksjSc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SBSJ
     *
     * @return the value of QG_ZTRY_JBXX.SBSJ
     *
     * @mbggenerated
     */
    public Date getSbsj() {
        return sbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SBSJ
     *
     * @param sbsj the value for QG_ZTRY_JBXX.SBSJ
     *
     * @mbggenerated
     */
    public void setSbsj(Date sbsj) {
        this.sbsj = sbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.JRYBH
     *
     * @return the value of QG_ZTRY_JBXX.JRYBH
     *
     * @mbggenerated
     */
    public String getJrybh() {
        return jrybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.JRYBH
     *
     * @param jrybh the value for QG_ZTRY_JBXX.JRYBH
     *
     * @mbggenerated
     */
    public void setJrybh(String jrybh) {
        this.jrybh = jrybh == null ? null : jrybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.XB_DM
     *
     * @return the value of QG_ZTRY_JBXX.XB_DM
     *
     * @mbggenerated
     */
    public String getXbDm() {
        return xbDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.XB_DM
     *
     * @param xbDm the value for QG_ZTRY_JBXX.XB_DM
     *
     * @mbggenerated
     */
    public void setXbDm(String xbDm) {
        this.xbDm = xbDm == null ? null : xbDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.MZ_DM
     *
     * @return the value of QG_ZTRY_JBXX.MZ_DM
     *
     * @mbggenerated
     */
    public String getMzDm() {
        return mzDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.MZ_DM
     *
     * @param mzDm the value for QG_ZTRY_JBXX.MZ_DM
     *
     * @mbggenerated
     */
    public void setMzDm(String mzDm) {
        this.mzDm = mzDm == null ? null : mzDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.JG_QH
     *
     * @return the value of QG_ZTRY_JBXX.JG_QH
     *
     * @mbggenerated
     */
    public String getJgQh() {
        return jgQh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.JG_QH
     *
     * @param jgQh the value for QG_ZTRY_JBXX.JG_QH
     *
     * @mbggenerated
     */
    public void setJgQh(String jgQh) {
        this.jgQh = jgQh == null ? null : jgQh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.ZWBH
     *
     * @return the value of QG_ZTRY_JBXX.ZWBH
     *
     * @mbggenerated
     */
    public String getZwbh() {
        return zwbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.ZWBH
     *
     * @param zwbh the value for QG_ZTRY_JBXX.ZWBH
     *
     * @mbggenerated
     */
    public void setZwbh(String zwbh) {
        this.zwbh = zwbh == null ? null : zwbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.TPFX_QH
     *
     * @return the value of QG_ZTRY_JBXX.TPFX_QH
     *
     * @mbggenerated
     */
    public String getTpfxQh() {
        return tpfxQh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.TPFX_QH
     *
     * @param tpfxQh the value for QG_ZTRY_JBXX.TPFX_QH
     *
     * @mbggenerated
     */
    public void setTpfxQh(String tpfxQh) {
        this.tpfxQh = tpfxQh == null ? null : tpfxQh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.LA_DWQH
     *
     * @return the value of QG_ZTRY_JBXX.LA_DWQH
     *
     * @mbggenerated
     */
    public String getLaDwqh() {
        return laDwqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.LA_DWQH
     *
     * @param laDwqh the value for QG_ZTRY_JBXX.LA_DWQH
     *
     * @mbggenerated
     */
    public void setLaDwqh(String laDwqh) {
        this.laDwqh = laDwqh == null ? null : laDwqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.LA_DWDM
     *
     * @return the value of QG_ZTRY_JBXX.LA_DWDM
     *
     * @mbggenerated
     */
    public String getLaDwdm() {
        return laDwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.LA_DWDM
     *
     * @param laDwdm the value for QG_ZTRY_JBXX.LA_DWDM
     *
     * @mbggenerated
     */
    public void setLaDwdm(String laDwdm) {
        this.laDwdm = laDwdm == null ? null : laDwdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.LA_DWXT_DM
     *
     * @return the value of QG_ZTRY_JBXX.LA_DWXT_DM
     *
     * @mbggenerated
     */
    public String getLaDwxtDm() {
        return laDwxtDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.LA_DWXT_DM
     *
     * @param laDwxtDm the value for QG_ZTRY_JBXX.LA_DWXT_DM
     *
     * @mbggenerated
     */
    public void setLaDwxtDm(String laDwxtDm) {
        this.laDwxtDm = laDwxtDm == null ? null : laDwxtDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.ZB_DWQH
     *
     * @return the value of QG_ZTRY_JBXX.ZB_DWQH
     *
     * @mbggenerated
     */
    public String getZbDwqh() {
        return zbDwqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.ZB_DWQH
     *
     * @param zbDwqh the value for QG_ZTRY_JBXX.ZB_DWQH
     *
     * @mbggenerated
     */
    public void setZbDwqh(String zbDwqh) {
        this.zbDwqh = zbDwqh == null ? null : zbDwqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.ZB_DWDM
     *
     * @return the value of QG_ZTRY_JBXX.ZB_DWDM
     *
     * @mbggenerated
     */
    public String getZbDwdm() {
        return zbDwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.ZB_DWDM
     *
     * @param zbDwdm the value for QG_ZTRY_JBXX.ZB_DWDM
     *
     * @mbggenerated
     */
    public void setZbDwdm(String zbDwdm) {
        this.zbDwdm = zbDwdm == null ? null : zbDwdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.DBJB_DM
     *
     * @return the value of QG_ZTRY_JBXX.DBJB_DM
     *
     * @mbggenerated
     */
    public String getDbjbDm() {
        return dbjbDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.DBJB_DM
     *
     * @param dbjbDm the value for QG_ZTRY_JBXX.DBJB_DM
     *
     * @mbggenerated
     */
    public void setDbjbDm(String dbjbDm) {
        this.dbjbDm = dbjbDm == null ? null : dbjbDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.BLYY
     *
     * @return the value of QG_ZTRY_JBXX.BLYY
     *
     * @mbggenerated
     */
    public String getBlyy() {
        return blyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.BLYY
     *
     * @param blyy the value for QG_ZTRY_JBXX.BLYY
     *
     * @mbggenerated
     */
    public void setBlyy(String blyy) {
        this.blyy = blyy == null ? null : blyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.BLBS
     *
     * @return the value of QG_ZTRY_JBXX.BLBS
     *
     * @mbggenerated
     */
    public String getBlbs() {
        return blbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.BLBS
     *
     * @param blbs the value for QG_ZTRY_JBXX.BLBS
     *
     * @mbggenerated
     */
    public void setBlbs(String blbs) {
        this.blbs = blbs == null ? null : blbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SP
     *
     * @return the value of QG_ZTRY_JBXX.SP
     *
     * @mbggenerated
     */
    public String getSp() {
        return sp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SP
     *
     * @param sp the value for QG_ZTRY_JBXX.SP
     *
     * @mbggenerated
     */
    public void setSp(String sp) {
        this.sp = sp == null ? null : sp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.LR_DWDM
     *
     * @return the value of QG_ZTRY_JBXX.LR_DWDM
     *
     * @mbggenerated
     */
    public String getLrDwdm() {
        return lrDwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.LR_DWDM
     *
     * @param lrDwdm the value for QG_ZTRY_JBXX.LR_DWDM
     *
     * @mbggenerated
     */
    public void setLrDwdm(String lrDwdm) {
        this.lrDwdm = lrDwdm == null ? null : lrDwdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.XG_DWDM
     *
     * @return the value of QG_ZTRY_JBXX.XG_DWDM
     *
     * @mbggenerated
     */
    public String getXgDwdm() {
        return xgDwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.XG_DWDM
     *
     * @param xgDwdm the value for QG_ZTRY_JBXX.XG_DWDM
     *
     * @mbggenerated
     */
    public void setXgDwdm(String xgDwdm) {
        this.xgDwdm = xgDwdm == null ? null : xgDwdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SC_DWXC
     *
     * @return the value of QG_ZTRY_JBXX.SC_DWXC
     *
     * @mbggenerated
     */
    public String getScDwxc() {
        return scDwxc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SC_DWXC
     *
     * @param scDwxc the value for QG_ZTRY_JBXX.SC_DWXC
     *
     * @mbggenerated
     */
    public void setScDwxc(String scDwxc) {
        this.scDwxc = scDwxc == null ? null : scDwxc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SC_DWXT_DM
     *
     * @return the value of QG_ZTRY_JBXX.SC_DWXT_DM
     *
     * @mbggenerated
     */
    public String getScDwxtDm() {
        return scDwxtDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SC_DWXT_DM
     *
     * @param scDwxtDm the value for QG_ZTRY_JBXX.SC_DWXT_DM
     *
     * @mbggenerated
     */
    public void setScDwxtDm(String scDwxtDm) {
        this.scDwxtDm = scDwxtDm == null ? null : scDwxtDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SC_SPR
     *
     * @return the value of QG_ZTRY_JBXX.SC_SPR
     *
     * @mbggenerated
     */
    public String getScSpr() {
        return scSpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SC_SPR
     *
     * @param scSpr the value for QG_ZTRY_JBXX.SC_SPR
     *
     * @mbggenerated
     */
    public void setScSpr(String scSpr) {
        this.scSpr = scSpr == null ? null : scSpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SY_DWDM
     *
     * @return the value of QG_ZTRY_JBXX.SY_DWDM
     *
     * @mbggenerated
     */
    public String getSyDwdm() {
        return syDwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SY_DWDM
     *
     * @param syDwdm the value for QG_ZTRY_JBXX.SY_DWDM
     *
     * @mbggenerated
     */
    public void setSyDwdm(String syDwdm) {
        this.syDwdm = syDwdm == null ? null : syDwdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.RYID
     *
     * @return the value of QG_ZTRY_JBXX.RYID
     *
     * @mbggenerated
     */
    public String getRyid() {
        return ryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.RYID
     *
     * @param ryid the value for QG_ZTRY_JBXX.RYID
     *
     * @mbggenerated
     */
    public void setRyid(String ryid) {
        this.ryid = ryid == null ? null : ryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.RYBH
     *
     * @return the value of QG_ZTRY_JBXX.RYBH
     *
     * @mbggenerated
     */
    public String getRybh() {
        return rybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.RYBH
     *
     * @param rybh the value for QG_ZTRY_JBXX.RYBH
     *
     * @mbggenerated
     */
    public void setRybh(String rybh) {
        this.rybh = rybh == null ? null : rybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.XM
     *
     * @return the value of QG_ZTRY_JBXX.XM
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.XM
     *
     * @param xm the value for QG_ZTRY_JBXX.XM
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.KY_DM
     *
     * @return the value of QG_ZTRY_JBXX.KY_DM
     *
     * @mbggenerated
     */
    public String getKyDm() {
        return kyDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.KY_DM
     *
     * @param kyDm the value for QG_ZTRY_JBXX.KY_DM
     *
     * @mbggenerated
     */
    public void setKyDm(String kyDm) {
        this.kyDm = kyDm == null ? null : kyDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.ZY_DM
     *
     * @return the value of QG_ZTRY_JBXX.ZY_DM
     *
     * @mbggenerated
     */
    public String getZyDm() {
        return zyDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.ZY_DM
     *
     * @param zyDm the value for QG_ZTRY_JBXX.ZY_DM
     *
     * @mbggenerated
     */
    public void setZyDm(String zyDm) {
        this.zyDm = zyDm == null ? null : zyDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.HJD_QH
     *
     * @return the value of QG_ZTRY_JBXX.HJD_QH
     *
     * @mbggenerated
     */
    public String getHjdQh() {
        return hjdQh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.HJD_QH
     *
     * @param hjdQh the value for QG_ZTRY_JBXX.HJD_QH
     *
     * @mbggenerated
     */
    public void setHjdQh(String hjdQh) {
        this.hjdQh = hjdQh == null ? null : hjdQh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.HJD_XZ
     *
     * @return the value of QG_ZTRY_JBXX.HJD_XZ
     *
     * @mbggenerated
     */
    public String getHjdXz() {
        return hjdXz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.HJD_XZ
     *
     * @param hjdXz the value for QG_ZTRY_JBXX.HJD_XZ
     *
     * @mbggenerated
     */
    public void setHjdXz(String hjdXz) {
        this.hjdXz = hjdXz == null ? null : hjdXz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.XZD_QH
     *
     * @return the value of QG_ZTRY_JBXX.XZD_QH
     *
     * @mbggenerated
     */
    public String getXzdQh() {
        return xzdQh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.XZD_QH
     *
     * @param xzdQh the value for QG_ZTRY_JBXX.XZD_QH
     *
     * @mbggenerated
     */
    public void setXzdQh(String xzdQh) {
        this.xzdQh = xzdQh == null ? null : xzdQh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.XZD_XZ
     *
     * @return the value of QG_ZTRY_JBXX.XZD_XZ
     *
     * @mbggenerated
     */
    public String getXzdXz() {
        return xzdXz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.XZD_XZ
     *
     * @param xzdXz the value for QG_ZTRY_JBXX.XZD_XZ
     *
     * @mbggenerated
     */
    public void setXzdXz(String xzdXz) {
        this.xzdXz = xzdXz == null ? null : xzdXz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.JG_XZ
     *
     * @return the value of QG_ZTRY_JBXX.JG_XZ
     *
     * @mbggenerated
     */
    public String getJgXz() {
        return jgXz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.JG_XZ
     *
     * @param jgXz the value for QG_ZTRY_JBXX.JG_XZ
     *
     * @mbggenerated
     */
    public void setJgXz(String jgXz) {
        this.jgXz = jgXz == null ? null : jgXz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.DNA
     *
     * @return the value of QG_ZTRY_JBXX.DNA
     *
     * @mbggenerated
     */
    public String getDna() {
        return dna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.DNA
     *
     * @param dna the value for QG_ZTRY_JBXX.DNA
     *
     * @mbggenerated
     */
    public void setDna(String dna) {
        this.dna = dna == null ? null : dna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.RYFJXX
     *
     * @return the value of QG_ZTRY_JBXX.RYFJXX
     *
     * @mbggenerated
     */
    public String getRyfjxx() {
        return ryfjxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.RYFJXX
     *
     * @param ryfjxx the value for QG_ZTRY_JBXX.RYFJXX
     *
     * @mbggenerated
     */
    public void setRyfjxx(String ryfjxx) {
        this.ryfjxx = ryfjxx == null ? null : ryfjxx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.AJBH
     *
     * @return the value of QG_ZTRY_JBXX.AJBH
     *
     * @mbggenerated
     */
    public String getAjbh() {
        return ajbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.AJBH
     *
     * @param ajbh the value for QG_ZTRY_JBXX.AJBH
     *
     * @mbggenerated
     */
    public void setAjbh(String ajbh) {
        this.ajbh = ajbh == null ? null : ajbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.AJLB_DM
     *
     * @return the value of QG_ZTRY_JBXX.AJLB_DM
     *
     * @mbggenerated
     */
    public String getAjlbDm() {
        return ajlbDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.AJLB_DM
     *
     * @param ajlbDm the value for QG_ZTRY_JBXX.AJLB_DM
     *
     * @mbggenerated
     */
    public void setAjlbDm(String ajlbDm) {
        this.ajlbDm = ajlbDm == null ? null : ajlbDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.ZTLX_DM
     *
     * @return the value of QG_ZTRY_JBXX.ZTLX_DM
     *
     * @mbggenerated
     */
    public String getZtlxDm() {
        return ztlxDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.ZTLX_DM
     *
     * @param ztlxDm the value for QG_ZTRY_JBXX.ZTLX_DM
     *
     * @mbggenerated
     */
    public void setZtlxDm(String ztlxDm) {
        this.ztlxDm = ztlxDm == null ? null : ztlxDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.JYAQ
     *
     * @return the value of QG_ZTRY_JBXX.JYAQ
     *
     * @mbggenerated
     */
    public String getJyaq() {
        return jyaq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.JYAQ
     *
     * @param jyaq the value for QG_ZTRY_JBXX.JYAQ
     *
     * @mbggenerated
     */
    public void setJyaq(String jyaq) {
        this.jyaq = jyaq == null ? null : jyaq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.LA_DWXC
     *
     * @return the value of QG_ZTRY_JBXX.LA_DWXC
     *
     * @mbggenerated
     */
    public String getLaDwxc() {
        return laDwxc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.LA_DWXC
     *
     * @param laDwxc the value for QG_ZTRY_JBXX.LA_DWXC
     *
     * @mbggenerated
     */
    public void setLaDwxc(String laDwxc) {
        this.laDwxc = laDwxc == null ? null : laDwxc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.ZB_DWXC
     *
     * @return the value of QG_ZTRY_JBXX.ZB_DWXC
     *
     * @mbggenerated
     */
    public String getZbDwxc() {
        return zbDwxc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.ZB_DWXC
     *
     * @param zbDwxc the value for QG_ZTRY_JBXX.ZB_DWXC
     *
     * @mbggenerated
     */
    public void setZbDwxc(String zbDwxc) {
        this.zbDwxc = zbDwxc == null ? null : zbDwxc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.ZB_LXR
     *
     * @return the value of QG_ZTRY_JBXX.ZB_LXR
     *
     * @mbggenerated
     */
    public String getZbLxr() {
        return zbLxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.ZB_LXR
     *
     * @param zbLxr the value for QG_ZTRY_JBXX.ZB_LXR
     *
     * @mbggenerated
     */
    public void setZbLxr(String zbLxr) {
        this.zbLxr = zbLxr == null ? null : zbLxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.ZB_LXFS
     *
     * @return the value of QG_ZTRY_JBXX.ZB_LXFS
     *
     * @mbggenerated
     */
    public String getZbLxfs() {
        return zbLxfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.ZB_LXFS
     *
     * @param zbLxfs the value for QG_ZTRY_JBXX.ZB_LXFS
     *
     * @mbggenerated
     */
    public void setZbLxfs(String zbLxfs) {
        this.zbLxfs = zbLxfs == null ? null : zbLxfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.DJ_TBR
     *
     * @return the value of QG_ZTRY_JBXX.DJ_TBR
     *
     * @mbggenerated
     */
    public String getDjTbr() {
        return djTbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.DJ_TBR
     *
     * @param djTbr the value for QG_ZTRY_JBXX.DJ_TBR
     *
     * @mbggenerated
     */
    public void setDjTbr(String djTbr) {
        this.djTbr = djTbr == null ? null : djTbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.DJ_SPR
     *
     * @return the value of QG_ZTRY_JBXX.DJ_SPR
     *
     * @mbggenerated
     */
    public String getDjSpr() {
        return djSpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.DJ_SPR
     *
     * @param djSpr the value for QG_ZTRY_JBXX.DJ_SPR
     *
     * @mbggenerated
     */
    public void setDjSpr(String djSpr) {
        this.djSpr = djSpr == null ? null : djSpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.TJLBH
     *
     * @return the value of QG_ZTRY_JBXX.TJLBH
     *
     * @mbggenerated
     */
    public String getTjlbh() {
        return tjlbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.TJLBH
     *
     * @param tjlbh the value for QG_ZTRY_JBXX.TJLBH
     *
     * @mbggenerated
     */
    public void setTjlbh(String tjlbh) {
        this.tjlbh = tjlbh == null ? null : tjlbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SPYY
     *
     * @return the value of QG_ZTRY_JBXX.SPYY
     *
     * @mbggenerated
     */
    public String getSpyy() {
        return spyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SPYY
     *
     * @param spyy the value for QG_ZTRY_JBXX.SPYY
     *
     * @mbggenerated
     */
    public void setSpyy(String spyy) {
        this.spyy = spyy == null ? null : spyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.LRR
     *
     * @return the value of QG_ZTRY_JBXX.LRR
     *
     * @mbggenerated
     */
    public String getLrr() {
        return lrr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.LRR
     *
     * @param lrr the value for QG_ZTRY_JBXX.LRR
     *
     * @mbggenerated
     */
    public void setLrr(String lrr) {
        this.lrr = lrr == null ? null : lrr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.XGR
     *
     * @return the value of QG_ZTRY_JBXX.XGR
     *
     * @mbggenerated
     */
    public String getXgr() {
        return xgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.XGR
     *
     * @param xgr the value for QG_ZTRY_JBXX.XGR
     *
     * @mbggenerated
     */
    public void setXgr(String xgr) {
        this.xgr = xgr == null ? null : xgr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SC_DWDM
     *
     * @return the value of QG_ZTRY_JBXX.SC_DWDM
     *
     * @mbggenerated
     */
    public String getScDwdm() {
        return scDwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SC_DWDM
     *
     * @param scDwdm the value for QG_ZTRY_JBXX.SC_DWDM
     *
     * @mbggenerated
     */
    public void setScDwdm(String scDwdm) {
        this.scDwdm = scDwdm == null ? null : scDwdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SCR
     *
     * @return the value of QG_ZTRY_JBXX.SCR
     *
     * @mbggenerated
     */
    public String getScr() {
        return scr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SCR
     *
     * @param scr the value for QG_ZTRY_JBXX.SCR
     *
     * @mbggenerated
     */
    public void setScr(String scr) {
        this.scr = scr == null ? null : scr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.ZKBZ
     *
     * @return the value of QG_ZTRY_JBXX.ZKBZ
     *
     * @mbggenerated
     */
    public String getZkbz() {
        return zkbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.ZKBZ
     *
     * @param zkbz the value for QG_ZTRY_JBXX.ZKBZ
     *
     * @mbggenerated
     */
    public void setZkbz(String zkbz) {
        this.zkbz = zkbz == null ? null : zkbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.SG
     *
     * @return the value of QG_ZTRY_JBXX.SG
     *
     * @mbggenerated
     */
    public Long getSg() {
        return sg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.SG
     *
     * @param sg the value for QG_ZTRY_JBXX.SG
     *
     * @mbggenerated
     */
    public void setSg(Long sg) {
        this.sg = sg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QG_ZTRY_JBXX.JJ
     *
     * @return the value of QG_ZTRY_JBXX.JJ
     *
     * @mbggenerated
     */
    public Long getJj() {
        return jj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QG_ZTRY_JBXX.JJ
     *
     * @param jj the value for QG_ZTRY_JBXX.JJ
     *
     * @mbggenerated
     */
    public void setJj(Long jj) {
        this.jj = jj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QG_ZTRY_JBXX
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QgZtryJbxx other = (QgZtryJbxx) that;
        return (this.getCsrqSx() == null ? other.getCsrqSx() == null : this.getCsrqSx().equals(other.getCsrqSx()))
            && (this.getCsrqXx() == null ? other.getCsrqXx() == null : this.getCsrqXx().equals(other.getCsrqXx()))
            && (this.getSfzh() == null ? other.getSfzh() == null : this.getSfzh().equals(other.getSfzh()))
            && (this.getTprq() == null ? other.getTprq() == null : this.getTprq().equals(other.getTprq()))
            && (this.getLasj() == null ? other.getLasj() == null : this.getLasj().equals(other.getLasj()))
            && (this.getDjRq() == null ? other.getDjRq() == null : this.getDjRq().equals(other.getDjRq()))
            && (this.getLrsj() == null ? other.getLrsj() == null : this.getLrsj().equals(other.getLrsj()))
            && (this.getXgsj() == null ? other.getXgsj() == null : this.getXgsj().equals(other.getXgsj()))
            && (this.getScsj() == null ? other.getScsj() == null : this.getScsj().equals(other.getScsj()))
            && (this.getRbksjDj() == null ? other.getRbksjDj() == null : this.getRbksjDj().equals(other.getRbksjDj()))
            && (this.getRbksjCx() == null ? other.getRbksjCx() == null : this.getRbksjCx().equals(other.getRbksjCx()))
            && (this.getRbksjSc() == null ? other.getRbksjSc() == null : this.getRbksjSc().equals(other.getRbksjSc()))
            && (this.getSbsj() == null ? other.getSbsj() == null : this.getSbsj().equals(other.getSbsj()))
            && (this.getJrybh() == null ? other.getJrybh() == null : this.getJrybh().equals(other.getJrybh()))
            && (this.getXbDm() == null ? other.getXbDm() == null : this.getXbDm().equals(other.getXbDm()))
            && (this.getMzDm() == null ? other.getMzDm() == null : this.getMzDm().equals(other.getMzDm()))
            && (this.getJgQh() == null ? other.getJgQh() == null : this.getJgQh().equals(other.getJgQh()))
            && (this.getZwbh() == null ? other.getZwbh() == null : this.getZwbh().equals(other.getZwbh()))
            && (this.getTpfxQh() == null ? other.getTpfxQh() == null : this.getTpfxQh().equals(other.getTpfxQh()))
            && (this.getLaDwqh() == null ? other.getLaDwqh() == null : this.getLaDwqh().equals(other.getLaDwqh()))
            && (this.getLaDwdm() == null ? other.getLaDwdm() == null : this.getLaDwdm().equals(other.getLaDwdm()))
            && (this.getLaDwxtDm() == null ? other.getLaDwxtDm() == null : this.getLaDwxtDm().equals(other.getLaDwxtDm()))
            && (this.getZbDwqh() == null ? other.getZbDwqh() == null : this.getZbDwqh().equals(other.getZbDwqh()))
            && (this.getZbDwdm() == null ? other.getZbDwdm() == null : this.getZbDwdm().equals(other.getZbDwdm()))
            && (this.getDbjbDm() == null ? other.getDbjbDm() == null : this.getDbjbDm().equals(other.getDbjbDm()))
            && (this.getBlyy() == null ? other.getBlyy() == null : this.getBlyy().equals(other.getBlyy()))
            && (this.getBlbs() == null ? other.getBlbs() == null : this.getBlbs().equals(other.getBlbs()))
            && (this.getSp() == null ? other.getSp() == null : this.getSp().equals(other.getSp()))
            && (this.getLrDwdm() == null ? other.getLrDwdm() == null : this.getLrDwdm().equals(other.getLrDwdm()))
            && (this.getXgDwdm() == null ? other.getXgDwdm() == null : this.getXgDwdm().equals(other.getXgDwdm()))
            && (this.getScDwxc() == null ? other.getScDwxc() == null : this.getScDwxc().equals(other.getScDwxc()))
            && (this.getScDwxtDm() == null ? other.getScDwxtDm() == null : this.getScDwxtDm().equals(other.getScDwxtDm()))
            && (this.getScSpr() == null ? other.getScSpr() == null : this.getScSpr().equals(other.getScSpr()))
            && (this.getSyDwdm() == null ? other.getSyDwdm() == null : this.getSyDwdm().equals(other.getSyDwdm()))
            && (this.getRyid() == null ? other.getRyid() == null : this.getRyid().equals(other.getRyid()))
            && (this.getRybh() == null ? other.getRybh() == null : this.getRybh().equals(other.getRybh()))
            && (this.getXm() == null ? other.getXm() == null : this.getXm().equals(other.getXm()))
            && (this.getKyDm() == null ? other.getKyDm() == null : this.getKyDm().equals(other.getKyDm()))
            && (this.getZyDm() == null ? other.getZyDm() == null : this.getZyDm().equals(other.getZyDm()))
            && (this.getHjdQh() == null ? other.getHjdQh() == null : this.getHjdQh().equals(other.getHjdQh()))
            && (this.getHjdXz() == null ? other.getHjdXz() == null : this.getHjdXz().equals(other.getHjdXz()))
            && (this.getXzdQh() == null ? other.getXzdQh() == null : this.getXzdQh().equals(other.getXzdQh()))
            && (this.getXzdXz() == null ? other.getXzdXz() == null : this.getXzdXz().equals(other.getXzdXz()))
            && (this.getJgXz() == null ? other.getJgXz() == null : this.getJgXz().equals(other.getJgXz()))
            && (this.getDna() == null ? other.getDna() == null : this.getDna().equals(other.getDna()))
            && (this.getRyfjxx() == null ? other.getRyfjxx() == null : this.getRyfjxx().equals(other.getRyfjxx()))
            && (this.getAjbh() == null ? other.getAjbh() == null : this.getAjbh().equals(other.getAjbh()))
            && (this.getAjlbDm() == null ? other.getAjlbDm() == null : this.getAjlbDm().equals(other.getAjlbDm()))
            && (this.getZtlxDm() == null ? other.getZtlxDm() == null : this.getZtlxDm().equals(other.getZtlxDm()))
            && (this.getJyaq() == null ? other.getJyaq() == null : this.getJyaq().equals(other.getJyaq()))
            && (this.getLaDwxc() == null ? other.getLaDwxc() == null : this.getLaDwxc().equals(other.getLaDwxc()))
            && (this.getZbDwxc() == null ? other.getZbDwxc() == null : this.getZbDwxc().equals(other.getZbDwxc()))
            && (this.getZbLxr() == null ? other.getZbLxr() == null : this.getZbLxr().equals(other.getZbLxr()))
            && (this.getZbLxfs() == null ? other.getZbLxfs() == null : this.getZbLxfs().equals(other.getZbLxfs()))
            && (this.getDjTbr() == null ? other.getDjTbr() == null : this.getDjTbr().equals(other.getDjTbr()))
            && (this.getDjSpr() == null ? other.getDjSpr() == null : this.getDjSpr().equals(other.getDjSpr()))
            && (this.getTjlbh() == null ? other.getTjlbh() == null : this.getTjlbh().equals(other.getTjlbh()))
            && (this.getSpyy() == null ? other.getSpyy() == null : this.getSpyy().equals(other.getSpyy()))
            && (this.getLrr() == null ? other.getLrr() == null : this.getLrr().equals(other.getLrr()))
            && (this.getXgr() == null ? other.getXgr() == null : this.getXgr().equals(other.getXgr()))
            && (this.getScDwdm() == null ? other.getScDwdm() == null : this.getScDwdm().equals(other.getScDwdm()))
            && (this.getScr() == null ? other.getScr() == null : this.getScr().equals(other.getScr()))
            && (this.getZkbz() == null ? other.getZkbz() == null : this.getZkbz().equals(other.getZkbz()))
            && (this.getSg() == null ? other.getSg() == null : this.getSg().equals(other.getSg()))
            && (this.getJj() == null ? other.getJj() == null : this.getJj().equals(other.getJj()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QG_ZTRY_JBXX
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCsrqSx() == null) ? 0 : getCsrqSx().hashCode());
        result = prime * result + ((getCsrqXx() == null) ? 0 : getCsrqXx().hashCode());
        result = prime * result + ((getSfzh() == null) ? 0 : getSfzh().hashCode());
        result = prime * result + ((getTprq() == null) ? 0 : getTprq().hashCode());
        result = prime * result + ((getLasj() == null) ? 0 : getLasj().hashCode());
        result = prime * result + ((getDjRq() == null) ? 0 : getDjRq().hashCode());
        result = prime * result + ((getLrsj() == null) ? 0 : getLrsj().hashCode());
        result = prime * result + ((getXgsj() == null) ? 0 : getXgsj().hashCode());
        result = prime * result + ((getScsj() == null) ? 0 : getScsj().hashCode());
        result = prime * result + ((getRbksjDj() == null) ? 0 : getRbksjDj().hashCode());
        result = prime * result + ((getRbksjCx() == null) ? 0 : getRbksjCx().hashCode());
        result = prime * result + ((getRbksjSc() == null) ? 0 : getRbksjSc().hashCode());
        result = prime * result + ((getSbsj() == null) ? 0 : getSbsj().hashCode());
        result = prime * result + ((getJrybh() == null) ? 0 : getJrybh().hashCode());
        result = prime * result + ((getXbDm() == null) ? 0 : getXbDm().hashCode());
        result = prime * result + ((getMzDm() == null) ? 0 : getMzDm().hashCode());
        result = prime * result + ((getJgQh() == null) ? 0 : getJgQh().hashCode());
        result = prime * result + ((getZwbh() == null) ? 0 : getZwbh().hashCode());
        result = prime * result + ((getTpfxQh() == null) ? 0 : getTpfxQh().hashCode());
        result = prime * result + ((getLaDwqh() == null) ? 0 : getLaDwqh().hashCode());
        result = prime * result + ((getLaDwdm() == null) ? 0 : getLaDwdm().hashCode());
        result = prime * result + ((getLaDwxtDm() == null) ? 0 : getLaDwxtDm().hashCode());
        result = prime * result + ((getZbDwqh() == null) ? 0 : getZbDwqh().hashCode());
        result = prime * result + ((getZbDwdm() == null) ? 0 : getZbDwdm().hashCode());
        result = prime * result + ((getDbjbDm() == null) ? 0 : getDbjbDm().hashCode());
        result = prime * result + ((getBlyy() == null) ? 0 : getBlyy().hashCode());
        result = prime * result + ((getBlbs() == null) ? 0 : getBlbs().hashCode());
        result = prime * result + ((getSp() == null) ? 0 : getSp().hashCode());
        result = prime * result + ((getLrDwdm() == null) ? 0 : getLrDwdm().hashCode());
        result = prime * result + ((getXgDwdm() == null) ? 0 : getXgDwdm().hashCode());
        result = prime * result + ((getScDwxc() == null) ? 0 : getScDwxc().hashCode());
        result = prime * result + ((getScDwxtDm() == null) ? 0 : getScDwxtDm().hashCode());
        result = prime * result + ((getScSpr() == null) ? 0 : getScSpr().hashCode());
        result = prime * result + ((getSyDwdm() == null) ? 0 : getSyDwdm().hashCode());
        result = prime * result + ((getRyid() == null) ? 0 : getRyid().hashCode());
        result = prime * result + ((getRybh() == null) ? 0 : getRybh().hashCode());
        result = prime * result + ((getXm() == null) ? 0 : getXm().hashCode());
        result = prime * result + ((getKyDm() == null) ? 0 : getKyDm().hashCode());
        result = prime * result + ((getZyDm() == null) ? 0 : getZyDm().hashCode());
        result = prime * result + ((getHjdQh() == null) ? 0 : getHjdQh().hashCode());
        result = prime * result + ((getHjdXz() == null) ? 0 : getHjdXz().hashCode());
        result = prime * result + ((getXzdQh() == null) ? 0 : getXzdQh().hashCode());
        result = prime * result + ((getXzdXz() == null) ? 0 : getXzdXz().hashCode());
        result = prime * result + ((getJgXz() == null) ? 0 : getJgXz().hashCode());
        result = prime * result + ((getDna() == null) ? 0 : getDna().hashCode());
        result = prime * result + ((getRyfjxx() == null) ? 0 : getRyfjxx().hashCode());
        result = prime * result + ((getAjbh() == null) ? 0 : getAjbh().hashCode());
        result = prime * result + ((getAjlbDm() == null) ? 0 : getAjlbDm().hashCode());
        result = prime * result + ((getZtlxDm() == null) ? 0 : getZtlxDm().hashCode());
        result = prime * result + ((getJyaq() == null) ? 0 : getJyaq().hashCode());
        result = prime * result + ((getLaDwxc() == null) ? 0 : getLaDwxc().hashCode());
        result = prime * result + ((getZbDwxc() == null) ? 0 : getZbDwxc().hashCode());
        result = prime * result + ((getZbLxr() == null) ? 0 : getZbLxr().hashCode());
        result = prime * result + ((getZbLxfs() == null) ? 0 : getZbLxfs().hashCode());
        result = prime * result + ((getDjTbr() == null) ? 0 : getDjTbr().hashCode());
        result = prime * result + ((getDjSpr() == null) ? 0 : getDjSpr().hashCode());
        result = prime * result + ((getTjlbh() == null) ? 0 : getTjlbh().hashCode());
        result = prime * result + ((getSpyy() == null) ? 0 : getSpyy().hashCode());
        result = prime * result + ((getLrr() == null) ? 0 : getLrr().hashCode());
        result = prime * result + ((getXgr() == null) ? 0 : getXgr().hashCode());
        result = prime * result + ((getScDwdm() == null) ? 0 : getScDwdm().hashCode());
        result = prime * result + ((getScr() == null) ? 0 : getScr().hashCode());
        result = prime * result + ((getZkbz() == null) ? 0 : getZkbz().hashCode());
        result = prime * result + ((getSg() == null) ? 0 : getSg().hashCode());
        result = prime * result + ((getJj() == null) ? 0 : getJj().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QG_ZTRY_JBXX
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", csrqSx=").append(csrqSx);
        sb.append(", csrqXx=").append(csrqXx);
        sb.append(", sfzh=").append(sfzh);
        sb.append(", tprq=").append(tprq);
        sb.append(", lasj=").append(lasj);
        sb.append(", djRq=").append(djRq);
        sb.append(", lrsj=").append(lrsj);
        sb.append(", xgsj=").append(xgsj);
        sb.append(", scsj=").append(scsj);
        sb.append(", rbksjDj=").append(rbksjDj);
        sb.append(", rbksjCx=").append(rbksjCx);
        sb.append(", rbksjSc=").append(rbksjSc);
        sb.append(", sbsj=").append(sbsj);
        sb.append(", jrybh=").append(jrybh);
        sb.append(", xbDm=").append(xbDm);
        sb.append(", mzDm=").append(mzDm);
        sb.append(", jgQh=").append(jgQh);
        sb.append(", zwbh=").append(zwbh);
        sb.append(", tpfxQh=").append(tpfxQh);
        sb.append(", laDwqh=").append(laDwqh);
        sb.append(", laDwdm=").append(laDwdm);
        sb.append(", laDwxtDm=").append(laDwxtDm);
        sb.append(", zbDwqh=").append(zbDwqh);
        sb.append(", zbDwdm=").append(zbDwdm);
        sb.append(", dbjbDm=").append(dbjbDm);
        sb.append(", blyy=").append(blyy);
        sb.append(", blbs=").append(blbs);
        sb.append(", sp=").append(sp);
        sb.append(", lrDwdm=").append(lrDwdm);
        sb.append(", xgDwdm=").append(xgDwdm);
        sb.append(", scDwxc=").append(scDwxc);
        sb.append(", scDwxtDm=").append(scDwxtDm);
        sb.append(", scSpr=").append(scSpr);
        sb.append(", syDwdm=").append(syDwdm);
        sb.append(", ryid=").append(ryid);
        sb.append(", rybh=").append(rybh);
        sb.append(", xm=").append(xm);
        sb.append(", kyDm=").append(kyDm);
        sb.append(", zyDm=").append(zyDm);
        sb.append(", hjdQh=").append(hjdQh);
        sb.append(", hjdXz=").append(hjdXz);
        sb.append(", xzdQh=").append(xzdQh);
        sb.append(", xzdXz=").append(xzdXz);
        sb.append(", jgXz=").append(jgXz);
        sb.append(", dna=").append(dna);
        sb.append(", ryfjxx=").append(ryfjxx);
        sb.append(", ajbh=").append(ajbh);
        sb.append(", ajlbDm=").append(ajlbDm);
        sb.append(", ztlxDm=").append(ztlxDm);
        sb.append(", jyaq=").append(jyaq);
        sb.append(", laDwxc=").append(laDwxc);
        sb.append(", zbDwxc=").append(zbDwxc);
        sb.append(", zbLxr=").append(zbLxr);
        sb.append(", zbLxfs=").append(zbLxfs);
        sb.append(", djTbr=").append(djTbr);
        sb.append(", djSpr=").append(djSpr);
        sb.append(", tjlbh=").append(tjlbh);
        sb.append(", spyy=").append(spyy);
        sb.append(", lrr=").append(lrr);
        sb.append(", xgr=").append(xgr);
        sb.append(", scDwdm=").append(scDwdm);
        sb.append(", scr=").append(scr);
        sb.append(", zkbz=").append(zkbz);
        sb.append(", sg=").append(sg);
        sb.append(", jj=").append(jj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}