package com.zhixin.rd.rkjc.web.entity.qk;

import java.util.ArrayList;
import java.util.List;

public class SftSfqzjdszcrymdExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    public SftSfqzjdszcrymdExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andXhIsNull() {
            addCriterion("XH is null");
            return (Criteria) this;
        }

        public Criteria andXhIsNotNull() {
            addCriterion("XH is not null");
            return (Criteria) this;
        }

        public Criteria andXhEqualTo(String value) {
            addCriterion("XH =", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotEqualTo(String value) {
            addCriterion("XH <>", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhGreaterThan(String value) {
            addCriterion("XH >", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhGreaterThanOrEqualTo(String value) {
            addCriterion("XH >=", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhLessThan(String value) {
            addCriterion("XH <", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhLessThanOrEqualTo(String value) {
            addCriterion("XH <=", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhLike(String value) {
            addCriterion("XH like", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotLike(String value) {
            addCriterion("XH not like", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhIn(List<String> values) {
            addCriterion("XH in", values, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotIn(List<String> values) {
            addCriterion("XH not in", values, "xh");
            return (Criteria) this;
        }

        public Criteria andXhBetween(String value1, String value2) {
            addCriterion("XH between", value1, value2, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotBetween(String value1, String value2) {
            addCriterion("XH not between", value1, value2, "xh");
            return (Criteria) this;
        }

        public Criteria andXmIsNull() {
            addCriterion("XM is null");
            return (Criteria) this;
        }

        public Criteria andXmIsNotNull() {
            addCriterion("XM is not null");
            return (Criteria) this;
        }

        public Criteria andXmEqualTo(String value) {
            addCriterion("XM =", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotEqualTo(String value) {
            addCriterion("XM <>", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmGreaterThan(String value) {
            addCriterion("XM >", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmGreaterThanOrEqualTo(String value) {
            addCriterion("XM >=", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLessThan(String value) {
            addCriterion("XM <", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLessThanOrEqualTo(String value) {
            addCriterion("XM <=", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLike(String value) {
            addCriterion("XM like", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotLike(String value) {
            addCriterion("XM not like", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmIn(List<String> values) {
            addCriterion("XM in", values, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotIn(List<String> values) {
            addCriterion("XM not in", values, "xm");
            return (Criteria) this;
        }

        public Criteria andXmBetween(String value1, String value2) {
            addCriterion("XM between", value1, value2, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotBetween(String value1, String value2) {
            addCriterion("XM not between", value1, value2, "xm");
            return (Criteria) this;
        }

        public Criteria andSfzhIsNull() {
            addCriterion("SFZH is null");
            return (Criteria) this;
        }

        public Criteria andSfzhIsNotNull() {
            addCriterion("SFZH is not null");
            return (Criteria) this;
        }

        public Criteria andSfzhEqualTo(String value) {
            addCriterion("SFZH =", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotEqualTo(String value) {
            addCriterion("SFZH <>", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhGreaterThan(String value) {
            addCriterion("SFZH >", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhGreaterThanOrEqualTo(String value) {
            addCriterion("SFZH >=", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhLessThan(String value) {
            addCriterion("SFZH <", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhLessThanOrEqualTo(String value) {
            addCriterion("SFZH <=", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhLike(String value) {
            addCriterion("SFZH like", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotLike(String value) {
            addCriterion("SFZH not like", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhIn(List<String> values) {
            addCriterion("SFZH in", values, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotIn(List<String> values) {
            addCriterion("SFZH not in", values, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhBetween(String value1, String value2) {
            addCriterion("SFZH between", value1, value2, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotBetween(String value1, String value2) {
            addCriterion("SFZH not between", value1, value2, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgIsNull() {
            addCriterion("SFQZGLJDJG is null");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgIsNotNull() {
            addCriterion("SFQZGLJDJG is not null");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgEqualTo(String value) {
            addCriterion("SFQZGLJDJG =", value, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgNotEqualTo(String value) {
            addCriterion("SFQZGLJDJG <>", value, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgGreaterThan(String value) {
            addCriterion("SFQZGLJDJG >", value, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgGreaterThanOrEqualTo(String value) {
            addCriterion("SFQZGLJDJG >=", value, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgLessThan(String value) {
            addCriterion("SFQZGLJDJG <", value, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgLessThanOrEqualTo(String value) {
            addCriterion("SFQZGLJDJG <=", value, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgLike(String value) {
            addCriterion("SFQZGLJDJG like", value, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgNotLike(String value) {
            addCriterion("SFQZGLJDJG not like", value, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgIn(List<String> values) {
            addCriterion("SFQZGLJDJG in", values, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgNotIn(List<String> values) {
            addCriterion("SFQZGLJDJG not in", values, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgBetween(String value1, String value2) {
            addCriterion("SFQZGLJDJG between", value1, value2, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andSfqzgljdjgNotBetween(String value1, String value2) {
            addCriterion("SFQZGLJDJG not between", value1, value2, "sfqzgljdjg");
            return (Criteria) this;
        }

        public Criteria andJddwIsNull() {
            addCriterion("JDDW is null");
            return (Criteria) this;
        }

        public Criteria andJddwIsNotNull() {
            addCriterion("JDDW is not null");
            return (Criteria) this;
        }

        public Criteria andJddwEqualTo(String value) {
            addCriterion("JDDW =", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwNotEqualTo(String value) {
            addCriterion("JDDW <>", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwGreaterThan(String value) {
            addCriterion("JDDW >", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwGreaterThanOrEqualTo(String value) {
            addCriterion("JDDW >=", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwLessThan(String value) {
            addCriterion("JDDW <", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwLessThanOrEqualTo(String value) {
            addCriterion("JDDW <=", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwLike(String value) {
            addCriterion("JDDW like", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwNotLike(String value) {
            addCriterion("JDDW not like", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwIn(List<String> values) {
            addCriterion("JDDW in", values, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwNotIn(List<String> values) {
            addCriterion("JDDW not in", values, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwBetween(String value1, String value2) {
            addCriterion("JDDW between", value1, value2, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwNotBetween(String value1, String value2) {
            addCriterion("JDDW not between", value1, value2, "jddw");
            return (Criteria) this;
        }

        public Criteria andJdsjIsNull() {
            addCriterion("JDSJ is null");
            return (Criteria) this;
        }

        public Criteria andJdsjIsNotNull() {
            addCriterion("JDSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJdsjEqualTo(String value) {
            addCriterion("JDSJ =", value, "jdsj");
            return (Criteria) this;
        }

        public Criteria andJdsjNotEqualTo(String value) {
            addCriterion("JDSJ <>", value, "jdsj");
            return (Criteria) this;
        }

        public Criteria andJdsjGreaterThan(String value) {
            addCriterion("JDSJ >", value, "jdsj");
            return (Criteria) this;
        }

        public Criteria andJdsjGreaterThanOrEqualTo(String value) {
            addCriterion("JDSJ >=", value, "jdsj");
            return (Criteria) this;
        }

        public Criteria andJdsjLessThan(String value) {
            addCriterion("JDSJ <", value, "jdsj");
            return (Criteria) this;
        }

        public Criteria andJdsjLessThanOrEqualTo(String value) {
            addCriterion("JDSJ <=", value, "jdsj");
            return (Criteria) this;
        }

        public Criteria andJdsjLike(String value) {
            addCriterion("JDSJ like", value, "jdsj");
            return (Criteria) this;
        }

        public Criteria andJdsjNotLike(String value) {
            addCriterion("JDSJ not like", value, "jdsj");
            return (Criteria) this;
        }

        public Criteria andJdsjIn(List<String> values) {
            addCriterion("JDSJ in", values, "jdsj");
            return (Criteria) this;
        }

        public Criteria andJdsjNotIn(List<String> values) {
            addCriterion("JDSJ not in", values, "jdsj");
            return (Criteria) this;
        }

        public Criteria andJdsjBetween(String value1, String value2) {
            addCriterion("JDSJ between", value1, value2, "jdsj");
            return (Criteria) this;
        }

        public Criteria andJdsjNotBetween(String value1, String value2) {
            addCriterion("JDSJ not between", value1, value2, "jdsj");
            return (Criteria) this;
        }

        public Criteria andRssjIsNull() {
            addCriterion("RSSJ is null");
            return (Criteria) this;
        }

        public Criteria andRssjIsNotNull() {
            addCriterion("RSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andRssjEqualTo(String value) {
            addCriterion("RSSJ =", value, "rssj");
            return (Criteria) this;
        }

        public Criteria andRssjNotEqualTo(String value) {
            addCriterion("RSSJ <>", value, "rssj");
            return (Criteria) this;
        }

        public Criteria andRssjGreaterThan(String value) {
            addCriterion("RSSJ >", value, "rssj");
            return (Criteria) this;
        }

        public Criteria andRssjGreaterThanOrEqualTo(String value) {
            addCriterion("RSSJ >=", value, "rssj");
            return (Criteria) this;
        }

        public Criteria andRssjLessThan(String value) {
            addCriterion("RSSJ <", value, "rssj");
            return (Criteria) this;
        }

        public Criteria andRssjLessThanOrEqualTo(String value) {
            addCriterion("RSSJ <=", value, "rssj");
            return (Criteria) this;
        }

        public Criteria andRssjLike(String value) {
            addCriterion("RSSJ like", value, "rssj");
            return (Criteria) this;
        }

        public Criteria andRssjNotLike(String value) {
            addCriterion("RSSJ not like", value, "rssj");
            return (Criteria) this;
        }

        public Criteria andRssjIn(List<String> values) {
            addCriterion("RSSJ in", values, "rssj");
            return (Criteria) this;
        }

        public Criteria andRssjNotIn(List<String> values) {
            addCriterion("RSSJ not in", values, "rssj");
            return (Criteria) this;
        }

        public Criteria andRssjBetween(String value1, String value2) {
            addCriterion("RSSJ between", value1, value2, "rssj");
            return (Criteria) this;
        }

        public Criteria andRssjNotBetween(String value1, String value2) {
            addCriterion("RSSJ not between", value1, value2, "rssj");
            return (Criteria) this;
        }

        public Criteria andNrssjIsNull() {
            addCriterion("NRSSJ is null");
            return (Criteria) this;
        }

        public Criteria andNrssjIsNotNull() {
            addCriterion("NRSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andNrssjEqualTo(String value) {
            addCriterion("NRSSJ =", value, "nrssj");
            return (Criteria) this;
        }

        public Criteria andNrssjNotEqualTo(String value) {
            addCriterion("NRSSJ <>", value, "nrssj");
            return (Criteria) this;
        }

        public Criteria andNrssjGreaterThan(String value) {
            addCriterion("NRSSJ >", value, "nrssj");
            return (Criteria) this;
        }

        public Criteria andNrssjGreaterThanOrEqualTo(String value) {
            addCriterion("NRSSJ >=", value, "nrssj");
            return (Criteria) this;
        }

        public Criteria andNrssjLessThan(String value) {
            addCriterion("NRSSJ <", value, "nrssj");
            return (Criteria) this;
        }

        public Criteria andNrssjLessThanOrEqualTo(String value) {
            addCriterion("NRSSJ <=", value, "nrssj");
            return (Criteria) this;
        }

        public Criteria andNrssjLike(String value) {
            addCriterion("NRSSJ like", value, "nrssj");
            return (Criteria) this;
        }

        public Criteria andNrssjNotLike(String value) {
            addCriterion("NRSSJ not like", value, "nrssj");
            return (Criteria) this;
        }

        public Criteria andNrssjIn(List<String> values) {
            addCriterion("NRSSJ in", values, "nrssj");
            return (Criteria) this;
        }

        public Criteria andNrssjNotIn(List<String> values) {
            addCriterion("NRSSJ not in", values, "nrssj");
            return (Criteria) this;
        }

        public Criteria andNrssjBetween(String value1, String value2) {
            addCriterion("NRSSJ between", value1, value2, "nrssj");
            return (Criteria) this;
        }

        public Criteria andNrssjNotBetween(String value1, String value2) {
            addCriterion("NRSSJ not between", value1, value2, "nrssj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}