package com.zhixin.rd.rkjc.web.entity.qk;

import java.io.Serializable;

public class SftSfqzjdszcrymd implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_SFQZJDSZCRYMD.XH
     *
     * @mbggenerated
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_SFQZJDSZCRYMD.XM
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_SFQZJDSZCRYMD.SFZH
     *
     * @mbggenerated
     */
    private String sfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_SFQZJDSZCRYMD.SFQZGLJDJG
     *
     * @mbggenerated
     */
    private String sfqzgljdjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_SFQZJDSZCRYMD.JDDW
     *
     * @mbggenerated
     */
    private String jddw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_SFQZJDSZCRYMD.JDSJ
     *
     * @mbggenerated
     */
    private String jdsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_SFQZJDSZCRYMD.RSSJ
     *
     * @mbggenerated
     */
    private String rssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_SFQZJDSZCRYMD.NRSSJ
     *
     * @mbggenerated
     */
    private String nrssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_SFQZJDSZCRYMD.XH
     *
     * @return the value of SFT_SFQZJDSZCRYMD.XH
     *
     * @mbggenerated
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_SFQZJDSZCRYMD.XH
     *
     * @param xh the value for SFT_SFQZJDSZCRYMD.XH
     *
     * @mbggenerated
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_SFQZJDSZCRYMD.XM
     *
     * @return the value of SFT_SFQZJDSZCRYMD.XM
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_SFQZJDSZCRYMD.XM
     *
     * @param xm the value for SFT_SFQZJDSZCRYMD.XM
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_SFQZJDSZCRYMD.SFZH
     *
     * @return the value of SFT_SFQZJDSZCRYMD.SFZH
     *
     * @mbggenerated
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_SFQZJDSZCRYMD.SFZH
     *
     * @param sfzh the value for SFT_SFQZJDSZCRYMD.SFZH
     *
     * @mbggenerated
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_SFQZJDSZCRYMD.SFQZGLJDJG
     *
     * @return the value of SFT_SFQZJDSZCRYMD.SFQZGLJDJG
     *
     * @mbggenerated
     */
    public String getSfqzgljdjg() {
        return sfqzgljdjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_SFQZJDSZCRYMD.SFQZGLJDJG
     *
     * @param sfqzgljdjg the value for SFT_SFQZJDSZCRYMD.SFQZGLJDJG
     *
     * @mbggenerated
     */
    public void setSfqzgljdjg(String sfqzgljdjg) {
        this.sfqzgljdjg = sfqzgljdjg == null ? null : sfqzgljdjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_SFQZJDSZCRYMD.JDDW
     *
     * @return the value of SFT_SFQZJDSZCRYMD.JDDW
     *
     * @mbggenerated
     */
    public String getJddw() {
        return jddw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_SFQZJDSZCRYMD.JDDW
     *
     * @param jddw the value for SFT_SFQZJDSZCRYMD.JDDW
     *
     * @mbggenerated
     */
    public void setJddw(String jddw) {
        this.jddw = jddw == null ? null : jddw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_SFQZJDSZCRYMD.JDSJ
     *
     * @return the value of SFT_SFQZJDSZCRYMD.JDSJ
     *
     * @mbggenerated
     */
    public String getJdsj() {
        return jdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_SFQZJDSZCRYMD.JDSJ
     *
     * @param jdsj the value for SFT_SFQZJDSZCRYMD.JDSJ
     *
     * @mbggenerated
     */
    public void setJdsj(String jdsj) {
        this.jdsj = jdsj == null ? null : jdsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_SFQZJDSZCRYMD.RSSJ
     *
     * @return the value of SFT_SFQZJDSZCRYMD.RSSJ
     *
     * @mbggenerated
     */
    public String getRssj() {
        return rssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_SFQZJDSZCRYMD.RSSJ
     *
     * @param rssj the value for SFT_SFQZJDSZCRYMD.RSSJ
     *
     * @mbggenerated
     */
    public void setRssj(String rssj) {
        this.rssj = rssj == null ? null : rssj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_SFQZJDSZCRYMD.NRSSJ
     *
     * @return the value of SFT_SFQZJDSZCRYMD.NRSSJ
     *
     * @mbggenerated
     */
    public String getNrssj() {
        return nrssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_SFQZJDSZCRYMD.NRSSJ
     *
     * @param nrssj the value for SFT_SFQZJDSZCRYMD.NRSSJ
     *
     * @mbggenerated
     */
    public void setNrssj(String nrssj) {
        this.nrssj = nrssj == null ? null : nrssj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SftSfqzjdszcrymd other = (SftSfqzjdszcrymd) that;
        return (this.getXh() == null ? other.getXh() == null : this.getXh().equals(other.getXh()))
            && (this.getXm() == null ? other.getXm() == null : this.getXm().equals(other.getXm()))
            && (this.getSfzh() == null ? other.getSfzh() == null : this.getSfzh().equals(other.getSfzh()))
            && (this.getSfqzgljdjg() == null ? other.getSfqzgljdjg() == null : this.getSfqzgljdjg().equals(other.getSfqzgljdjg()))
            && (this.getJddw() == null ? other.getJddw() == null : this.getJddw().equals(other.getJddw()))
            && (this.getJdsj() == null ? other.getJdsj() == null : this.getJdsj().equals(other.getJdsj()))
            && (this.getRssj() == null ? other.getRssj() == null : this.getRssj().equals(other.getRssj()))
            && (this.getNrssj() == null ? other.getNrssj() == null : this.getNrssj().equals(other.getNrssj()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getXh() == null) ? 0 : getXh().hashCode());
        result = prime * result + ((getXm() == null) ? 0 : getXm().hashCode());
        result = prime * result + ((getSfzh() == null) ? 0 : getSfzh().hashCode());
        result = prime * result + ((getSfqzgljdjg() == null) ? 0 : getSfqzgljdjg().hashCode());
        result = prime * result + ((getJddw() == null) ? 0 : getJddw().hashCode());
        result = prime * result + ((getJdsj() == null) ? 0 : getJdsj().hashCode());
        result = prime * result + ((getRssj() == null) ? 0 : getRssj().hashCode());
        result = prime * result + ((getNrssj() == null) ? 0 : getNrssj().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_SFQZJDSZCRYMD
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xh=").append(xh);
        sb.append(", xm=").append(xm);
        sb.append(", sfzh=").append(sfzh);
        sb.append(", sfqzgljdjg=").append(sfqzgljdjg);
        sb.append(", jddw=").append(jddw);
        sb.append(", jdsj=").append(jdsj);
        sb.append(", rssj=").append(rssj);
        sb.append(", nrssj=").append(nrssj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}