package com.zhixin.rd.rkjc.web.entity.qk;

import java.io.Serializable;

public class SftXmsfry implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.XM
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.CYM
     *
     * @mbggenerated
     */
    private String cym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.XB
     *
     * @mbggenerated
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SFZH
     *
     * @mbggenerated
     */
    private String sfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.CSRQ
     *
     * @mbggenerated
     */
    private String csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.MZ
     *
     * @mbggenerated
     */
    private String mz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.WHSP
     *
     * @mbggenerated
     */
    private String whsp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SFNCJ
     *
     * @mbggenerated
     */
    private String sfncj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.HJDZ
     *
     * @mbggenerated
     */
    private String hjdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SFTQSF
     *
     * @mbggenerated
     */
    private String sftqsf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SFSJ
     *
     * @mbggenerated
     */
    private String sfsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.ZM
     *
     * @mbggenerated
     */
    private String zm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.XQ
     *
     * @mbggenerated
     */
    private String xq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.FJX
     *
     * @mbggenerated
     */
    private String fjx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SFLF
     *
     * @mbggenerated
     */
    private String sflf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.XDS
     *
     * @mbggenerated
     */
    private String xds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SFCJZYJNPX
     *
     * @mbggenerated
     */
    private String sfcjzyjnpx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SFHDZYJNZS
     *
     * @mbggenerated
     */
    private String sfhdzyjnzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SFXLJK
     *
     * @mbggenerated
     */
    private String sfxljk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.JTLXQK
     *
     * @mbggenerated
     */
    private String jtlxqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SFSWRY
     *
     * @mbggenerated
     */
    private String sfswry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.WXXPG
     *
     * @mbggenerated
     */
    private String wxxpg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.GZBX
     *
     * @mbggenerated
     */
    private String gzbx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.RZTD
     *
     * @mbggenerated
     */
    private String rztd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.FXQJTSQKBZ
     *
     * @mbggenerated
     */
    private String fxqjtsqkbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.JXTQSFSM
     *
     * @mbggenerated
     */
    private String jxtqsfsm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.HCZT
     *
     * @mbggenerated
     */
    private String hczt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SFYHZ
     *
     * @mbggenerated
     */
    private String sfyhz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SZJS
     *
     * @mbggenerated
     */
    private String szjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.SFYZP
     *
     * @mbggenerated
     */
    private String sfyzp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.LRSJ
     *
     * @mbggenerated
     */
    private String lrsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SFT_XMSFRY.HCSJ
     *
     * @mbggenerated
     */
    private String hcsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SFT_XMSFRY
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.XM
     *
     * @return the value of SFT_XMSFRY.XM
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.XM
     *
     * @param xm the value for SFT_XMSFRY.XM
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.CYM
     *
     * @return the value of SFT_XMSFRY.CYM
     *
     * @mbggenerated
     */
    public String getCym() {
        return cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.CYM
     *
     * @param cym the value for SFT_XMSFRY.CYM
     *
     * @mbggenerated
     */
    public void setCym(String cym) {
        this.cym = cym == null ? null : cym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.XB
     *
     * @return the value of SFT_XMSFRY.XB
     *
     * @mbggenerated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.XB
     *
     * @param xb the value for SFT_XMSFRY.XB
     *
     * @mbggenerated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SFZH
     *
     * @return the value of SFT_XMSFRY.SFZH
     *
     * @mbggenerated
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SFZH
     *
     * @param sfzh the value for SFT_XMSFRY.SFZH
     *
     * @mbggenerated
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.CSRQ
     *
     * @return the value of SFT_XMSFRY.CSRQ
     *
     * @mbggenerated
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.CSRQ
     *
     * @param csrq the value for SFT_XMSFRY.CSRQ
     *
     * @mbggenerated
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq == null ? null : csrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.MZ
     *
     * @return the value of SFT_XMSFRY.MZ
     *
     * @mbggenerated
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.MZ
     *
     * @param mz the value for SFT_XMSFRY.MZ
     *
     * @mbggenerated
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.WHSP
     *
     * @return the value of SFT_XMSFRY.WHSP
     *
     * @mbggenerated
     */
    public String getWhsp() {
        return whsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.WHSP
     *
     * @param whsp the value for SFT_XMSFRY.WHSP
     *
     * @mbggenerated
     */
    public void setWhsp(String whsp) {
        this.whsp = whsp == null ? null : whsp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SFNCJ
     *
     * @return the value of SFT_XMSFRY.SFNCJ
     *
     * @mbggenerated
     */
    public String getSfncj() {
        return sfncj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SFNCJ
     *
     * @param sfncj the value for SFT_XMSFRY.SFNCJ
     *
     * @mbggenerated
     */
    public void setSfncj(String sfncj) {
        this.sfncj = sfncj == null ? null : sfncj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.HJDZ
     *
     * @return the value of SFT_XMSFRY.HJDZ
     *
     * @mbggenerated
     */
    public String getHjdz() {
        return hjdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.HJDZ
     *
     * @param hjdz the value for SFT_XMSFRY.HJDZ
     *
     * @mbggenerated
     */
    public void setHjdz(String hjdz) {
        this.hjdz = hjdz == null ? null : hjdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SFTQSF
     *
     * @return the value of SFT_XMSFRY.SFTQSF
     *
     * @mbggenerated
     */
    public String getSftqsf() {
        return sftqsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SFTQSF
     *
     * @param sftqsf the value for SFT_XMSFRY.SFTQSF
     *
     * @mbggenerated
     */
    public void setSftqsf(String sftqsf) {
        this.sftqsf = sftqsf == null ? null : sftqsf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SFSJ
     *
     * @return the value of SFT_XMSFRY.SFSJ
     *
     * @mbggenerated
     */
    public String getSfsj() {
        return sfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SFSJ
     *
     * @param sfsj the value for SFT_XMSFRY.SFSJ
     *
     * @mbggenerated
     */
    public void setSfsj(String sfsj) {
        this.sfsj = sfsj == null ? null : sfsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.ZM
     *
     * @return the value of SFT_XMSFRY.ZM
     *
     * @mbggenerated
     */
    public String getZm() {
        return zm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.ZM
     *
     * @param zm the value for SFT_XMSFRY.ZM
     *
     * @mbggenerated
     */
    public void setZm(String zm) {
        this.zm = zm == null ? null : zm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.XQ
     *
     * @return the value of SFT_XMSFRY.XQ
     *
     * @mbggenerated
     */
    public String getXq() {
        return xq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.XQ
     *
     * @param xq the value for SFT_XMSFRY.XQ
     *
     * @mbggenerated
     */
    public void setXq(String xq) {
        this.xq = xq == null ? null : xq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.FJX
     *
     * @return the value of SFT_XMSFRY.FJX
     *
     * @mbggenerated
     */
    public String getFjx() {
        return fjx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.FJX
     *
     * @param fjx the value for SFT_XMSFRY.FJX
     *
     * @mbggenerated
     */
    public void setFjx(String fjx) {
        this.fjx = fjx == null ? null : fjx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SFLF
     *
     * @return the value of SFT_XMSFRY.SFLF
     *
     * @mbggenerated
     */
    public String getSflf() {
        return sflf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SFLF
     *
     * @param sflf the value for SFT_XMSFRY.SFLF
     *
     * @mbggenerated
     */
    public void setSflf(String sflf) {
        this.sflf = sflf == null ? null : sflf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.XDS
     *
     * @return the value of SFT_XMSFRY.XDS
     *
     * @mbggenerated
     */
    public String getXds() {
        return xds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.XDS
     *
     * @param xds the value for SFT_XMSFRY.XDS
     *
     * @mbggenerated
     */
    public void setXds(String xds) {
        this.xds = xds == null ? null : xds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SFCJZYJNPX
     *
     * @return the value of SFT_XMSFRY.SFCJZYJNPX
     *
     * @mbggenerated
     */
    public String getSfcjzyjnpx() {
        return sfcjzyjnpx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SFCJZYJNPX
     *
     * @param sfcjzyjnpx the value for SFT_XMSFRY.SFCJZYJNPX
     *
     * @mbggenerated
     */
    public void setSfcjzyjnpx(String sfcjzyjnpx) {
        this.sfcjzyjnpx = sfcjzyjnpx == null ? null : sfcjzyjnpx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SFHDZYJNZS
     *
     * @return the value of SFT_XMSFRY.SFHDZYJNZS
     *
     * @mbggenerated
     */
    public String getSfhdzyjnzs() {
        return sfhdzyjnzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SFHDZYJNZS
     *
     * @param sfhdzyjnzs the value for SFT_XMSFRY.SFHDZYJNZS
     *
     * @mbggenerated
     */
    public void setSfhdzyjnzs(String sfhdzyjnzs) {
        this.sfhdzyjnzs = sfhdzyjnzs == null ? null : sfhdzyjnzs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SFXLJK
     *
     * @return the value of SFT_XMSFRY.SFXLJK
     *
     * @mbggenerated
     */
    public String getSfxljk() {
        return sfxljk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SFXLJK
     *
     * @param sfxljk the value for SFT_XMSFRY.SFXLJK
     *
     * @mbggenerated
     */
    public void setSfxljk(String sfxljk) {
        this.sfxljk = sfxljk == null ? null : sfxljk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.JTLXQK
     *
     * @return the value of SFT_XMSFRY.JTLXQK
     *
     * @mbggenerated
     */
    public String getJtlxqk() {
        return jtlxqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.JTLXQK
     *
     * @param jtlxqk the value for SFT_XMSFRY.JTLXQK
     *
     * @mbggenerated
     */
    public void setJtlxqk(String jtlxqk) {
        this.jtlxqk = jtlxqk == null ? null : jtlxqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SFSWRY
     *
     * @return the value of SFT_XMSFRY.SFSWRY
     *
     * @mbggenerated
     */
    public String getSfswry() {
        return sfswry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SFSWRY
     *
     * @param sfswry the value for SFT_XMSFRY.SFSWRY
     *
     * @mbggenerated
     */
    public void setSfswry(String sfswry) {
        this.sfswry = sfswry == null ? null : sfswry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.WXXPG
     *
     * @return the value of SFT_XMSFRY.WXXPG
     *
     * @mbggenerated
     */
    public String getWxxpg() {
        return wxxpg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.WXXPG
     *
     * @param wxxpg the value for SFT_XMSFRY.WXXPG
     *
     * @mbggenerated
     */
    public void setWxxpg(String wxxpg) {
        this.wxxpg = wxxpg == null ? null : wxxpg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.GZBX
     *
     * @return the value of SFT_XMSFRY.GZBX
     *
     * @mbggenerated
     */
    public String getGzbx() {
        return gzbx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.GZBX
     *
     * @param gzbx the value for SFT_XMSFRY.GZBX
     *
     * @mbggenerated
     */
    public void setGzbx(String gzbx) {
        this.gzbx = gzbx == null ? null : gzbx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.RZTD
     *
     * @return the value of SFT_XMSFRY.RZTD
     *
     * @mbggenerated
     */
    public String getRztd() {
        return rztd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.RZTD
     *
     * @param rztd the value for SFT_XMSFRY.RZTD
     *
     * @mbggenerated
     */
    public void setRztd(String rztd) {
        this.rztd = rztd == null ? null : rztd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.FXQJTSQKBZ
     *
     * @return the value of SFT_XMSFRY.FXQJTSQKBZ
     *
     * @mbggenerated
     */
    public String getFxqjtsqkbz() {
        return fxqjtsqkbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.FXQJTSQKBZ
     *
     * @param fxqjtsqkbz the value for SFT_XMSFRY.FXQJTSQKBZ
     *
     * @mbggenerated
     */
    public void setFxqjtsqkbz(String fxqjtsqkbz) {
        this.fxqjtsqkbz = fxqjtsqkbz == null ? null : fxqjtsqkbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.JXTQSFSM
     *
     * @return the value of SFT_XMSFRY.JXTQSFSM
     *
     * @mbggenerated
     */
    public String getJxtqsfsm() {
        return jxtqsfsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.JXTQSFSM
     *
     * @param jxtqsfsm the value for SFT_XMSFRY.JXTQSFSM
     *
     * @mbggenerated
     */
    public void setJxtqsfsm(String jxtqsfsm) {
        this.jxtqsfsm = jxtqsfsm == null ? null : jxtqsfsm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.HCZT
     *
     * @return the value of SFT_XMSFRY.HCZT
     *
     * @mbggenerated
     */
    public String getHczt() {
        return hczt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.HCZT
     *
     * @param hczt the value for SFT_XMSFRY.HCZT
     *
     * @mbggenerated
     */
    public void setHczt(String hczt) {
        this.hczt = hczt == null ? null : hczt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.BZ
     *
     * @return the value of SFT_XMSFRY.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.BZ
     *
     * @param bz the value for SFT_XMSFRY.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SFYHZ
     *
     * @return the value of SFT_XMSFRY.SFYHZ
     *
     * @mbggenerated
     */
    public String getSfyhz() {
        return sfyhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SFYHZ
     *
     * @param sfyhz the value for SFT_XMSFRY.SFYHZ
     *
     * @mbggenerated
     */
    public void setSfyhz(String sfyhz) {
        this.sfyhz = sfyhz == null ? null : sfyhz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SZJS
     *
     * @return the value of SFT_XMSFRY.SZJS
     *
     * @mbggenerated
     */
    public String getSzjs() {
        return szjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SZJS
     *
     * @param szjs the value for SFT_XMSFRY.SZJS
     *
     * @mbggenerated
     */
    public void setSzjs(String szjs) {
        this.szjs = szjs == null ? null : szjs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.SFYZP
     *
     * @return the value of SFT_XMSFRY.SFYZP
     *
     * @mbggenerated
     */
    public String getSfyzp() {
        return sfyzp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.SFYZP
     *
     * @param sfyzp the value for SFT_XMSFRY.SFYZP
     *
     * @mbggenerated
     */
    public void setSfyzp(String sfyzp) {
        this.sfyzp = sfyzp == null ? null : sfyzp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.LRSJ
     *
     * @return the value of SFT_XMSFRY.LRSJ
     *
     * @mbggenerated
     */
    public String getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.LRSJ
     *
     * @param lrsj the value for SFT_XMSFRY.LRSJ
     *
     * @mbggenerated
     */
    public void setLrsj(String lrsj) {
        this.lrsj = lrsj == null ? null : lrsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SFT_XMSFRY.HCSJ
     *
     * @return the value of SFT_XMSFRY.HCSJ
     *
     * @mbggenerated
     */
    public String getHcsj() {
        return hcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SFT_XMSFRY.HCSJ
     *
     * @param hcsj the value for SFT_XMSFRY.HCSJ
     *
     * @mbggenerated
     */
    public void setHcsj(String hcsj) {
        this.hcsj = hcsj == null ? null : hcsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_XMSFRY
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SftXmsfry other = (SftXmsfry) that;
        return (this.getXm() == null ? other.getXm() == null : this.getXm().equals(other.getXm()))
            && (this.getCym() == null ? other.getCym() == null : this.getCym().equals(other.getCym()))
            && (this.getXb() == null ? other.getXb() == null : this.getXb().equals(other.getXb()))
            && (this.getSfzh() == null ? other.getSfzh() == null : this.getSfzh().equals(other.getSfzh()))
            && (this.getCsrq() == null ? other.getCsrq() == null : this.getCsrq().equals(other.getCsrq()))
            && (this.getMz() == null ? other.getMz() == null : this.getMz().equals(other.getMz()))
            && (this.getWhsp() == null ? other.getWhsp() == null : this.getWhsp().equals(other.getWhsp()))
            && (this.getSfncj() == null ? other.getSfncj() == null : this.getSfncj().equals(other.getSfncj()))
            && (this.getHjdz() == null ? other.getHjdz() == null : this.getHjdz().equals(other.getHjdz()))
            && (this.getSftqsf() == null ? other.getSftqsf() == null : this.getSftqsf().equals(other.getSftqsf()))
            && (this.getSfsj() == null ? other.getSfsj() == null : this.getSfsj().equals(other.getSfsj()))
            && (this.getZm() == null ? other.getZm() == null : this.getZm().equals(other.getZm()))
            && (this.getXq() == null ? other.getXq() == null : this.getXq().equals(other.getXq()))
            && (this.getFjx() == null ? other.getFjx() == null : this.getFjx().equals(other.getFjx()))
            && (this.getSflf() == null ? other.getSflf() == null : this.getSflf().equals(other.getSflf()))
            && (this.getXds() == null ? other.getXds() == null : this.getXds().equals(other.getXds()))
            && (this.getSfcjzyjnpx() == null ? other.getSfcjzyjnpx() == null : this.getSfcjzyjnpx().equals(other.getSfcjzyjnpx()))
            && (this.getSfhdzyjnzs() == null ? other.getSfhdzyjnzs() == null : this.getSfhdzyjnzs().equals(other.getSfhdzyjnzs()))
            && (this.getSfxljk() == null ? other.getSfxljk() == null : this.getSfxljk().equals(other.getSfxljk()))
            && (this.getJtlxqk() == null ? other.getJtlxqk() == null : this.getJtlxqk().equals(other.getJtlxqk()))
            && (this.getSfswry() == null ? other.getSfswry() == null : this.getSfswry().equals(other.getSfswry()))
            && (this.getWxxpg() == null ? other.getWxxpg() == null : this.getWxxpg().equals(other.getWxxpg()))
            && (this.getGzbx() == null ? other.getGzbx() == null : this.getGzbx().equals(other.getGzbx()))
            && (this.getRztd() == null ? other.getRztd() == null : this.getRztd().equals(other.getRztd()))
            && (this.getFxqjtsqkbz() == null ? other.getFxqjtsqkbz() == null : this.getFxqjtsqkbz().equals(other.getFxqjtsqkbz()))
            && (this.getJxtqsfsm() == null ? other.getJxtqsfsm() == null : this.getJxtqsfsm().equals(other.getJxtqsfsm()))
            && (this.getHczt() == null ? other.getHczt() == null : this.getHczt().equals(other.getHczt()))
            && (this.getBz() == null ? other.getBz() == null : this.getBz().equals(other.getBz()))
            && (this.getSfyhz() == null ? other.getSfyhz() == null : this.getSfyhz().equals(other.getSfyhz()))
            && (this.getSzjs() == null ? other.getSzjs() == null : this.getSzjs().equals(other.getSzjs()))
            && (this.getSfyzp() == null ? other.getSfyzp() == null : this.getSfyzp().equals(other.getSfyzp()))
            && (this.getLrsj() == null ? other.getLrsj() == null : this.getLrsj().equals(other.getLrsj()))
            && (this.getHcsj() == null ? other.getHcsj() == null : this.getHcsj().equals(other.getHcsj()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_XMSFRY
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getXm() == null) ? 0 : getXm().hashCode());
        result = prime * result + ((getCym() == null) ? 0 : getCym().hashCode());
        result = prime * result + ((getXb() == null) ? 0 : getXb().hashCode());
        result = prime * result + ((getSfzh() == null) ? 0 : getSfzh().hashCode());
        result = prime * result + ((getCsrq() == null) ? 0 : getCsrq().hashCode());
        result = prime * result + ((getMz() == null) ? 0 : getMz().hashCode());
        result = prime * result + ((getWhsp() == null) ? 0 : getWhsp().hashCode());
        result = prime * result + ((getSfncj() == null) ? 0 : getSfncj().hashCode());
        result = prime * result + ((getHjdz() == null) ? 0 : getHjdz().hashCode());
        result = prime * result + ((getSftqsf() == null) ? 0 : getSftqsf().hashCode());
        result = prime * result + ((getSfsj() == null) ? 0 : getSfsj().hashCode());
        result = prime * result + ((getZm() == null) ? 0 : getZm().hashCode());
        result = prime * result + ((getXq() == null) ? 0 : getXq().hashCode());
        result = prime * result + ((getFjx() == null) ? 0 : getFjx().hashCode());
        result = prime * result + ((getSflf() == null) ? 0 : getSflf().hashCode());
        result = prime * result + ((getXds() == null) ? 0 : getXds().hashCode());
        result = prime * result + ((getSfcjzyjnpx() == null) ? 0 : getSfcjzyjnpx().hashCode());
        result = prime * result + ((getSfhdzyjnzs() == null) ? 0 : getSfhdzyjnzs().hashCode());
        result = prime * result + ((getSfxljk() == null) ? 0 : getSfxljk().hashCode());
        result = prime * result + ((getJtlxqk() == null) ? 0 : getJtlxqk().hashCode());
        result = prime * result + ((getSfswry() == null) ? 0 : getSfswry().hashCode());
        result = prime * result + ((getWxxpg() == null) ? 0 : getWxxpg().hashCode());
        result = prime * result + ((getGzbx() == null) ? 0 : getGzbx().hashCode());
        result = prime * result + ((getRztd() == null) ? 0 : getRztd().hashCode());
        result = prime * result + ((getFxqjtsqkbz() == null) ? 0 : getFxqjtsqkbz().hashCode());
        result = prime * result + ((getJxtqsfsm() == null) ? 0 : getJxtqsfsm().hashCode());
        result = prime * result + ((getHczt() == null) ? 0 : getHczt().hashCode());
        result = prime * result + ((getBz() == null) ? 0 : getBz().hashCode());
        result = prime * result + ((getSfyhz() == null) ? 0 : getSfyhz().hashCode());
        result = prime * result + ((getSzjs() == null) ? 0 : getSzjs().hashCode());
        result = prime * result + ((getSfyzp() == null) ? 0 : getSfyzp().hashCode());
        result = prime * result + ((getLrsj() == null) ? 0 : getLrsj().hashCode());
        result = prime * result + ((getHcsj() == null) ? 0 : getHcsj().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SFT_XMSFRY
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xm=").append(xm);
        sb.append(", cym=").append(cym);
        sb.append(", xb=").append(xb);
        sb.append(", sfzh=").append(sfzh);
        sb.append(", csrq=").append(csrq);
        sb.append(", mz=").append(mz);
        sb.append(", whsp=").append(whsp);
        sb.append(", sfncj=").append(sfncj);
        sb.append(", hjdz=").append(hjdz);
        sb.append(", sftqsf=").append(sftqsf);
        sb.append(", sfsj=").append(sfsj);
        sb.append(", zm=").append(zm);
        sb.append(", xq=").append(xq);
        sb.append(", fjx=").append(fjx);
        sb.append(", sflf=").append(sflf);
        sb.append(", xds=").append(xds);
        sb.append(", sfcjzyjnpx=").append(sfcjzyjnpx);
        sb.append(", sfhdzyjnzs=").append(sfhdzyjnzs);
        sb.append(", sfxljk=").append(sfxljk);
        sb.append(", jtlxqk=").append(jtlxqk);
        sb.append(", sfswry=").append(sfswry);
        sb.append(", wxxpg=").append(wxxpg);
        sb.append(", gzbx=").append(gzbx);
        sb.append(", rztd=").append(rztd);
        sb.append(", fxqjtsqkbz=").append(fxqjtsqkbz);
        sb.append(", jxtqsfsm=").append(jxtqsfsm);
        sb.append(", hczt=").append(hczt);
        sb.append(", bz=").append(bz);
        sb.append(", sfyhz=").append(sfyhz);
        sb.append(", szjs=").append(szjs);
        sb.append(", sfyzp=").append(sfyzp);
        sb.append(", lrsj=").append(lrsj);
        sb.append(", hcsj=").append(hcsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}