package com.zhixin.rd.rkjc.web.entity.qk;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbleCaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    public TbleCaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andECaseIdIsNull() {
            addCriterion("E_CASE_ID is null");
            return (Criteria) this;
        }

        public Criteria andECaseIdIsNotNull() {
            addCriterion("E_CASE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andECaseIdEqualTo(BigDecimal value) {
            addCriterion("E_CASE_ID =", value, "eCaseId");
            return (Criteria) this;
        }

        public Criteria andECaseIdNotEqualTo(BigDecimal value) {
            addCriterion("E_CASE_ID <>", value, "eCaseId");
            return (Criteria) this;
        }

        public Criteria andECaseIdGreaterThan(BigDecimal value) {
            addCriterion("E_CASE_ID >", value, "eCaseId");
            return (Criteria) this;
        }

        public Criteria andECaseIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("E_CASE_ID >=", value, "eCaseId");
            return (Criteria) this;
        }

        public Criteria andECaseIdLessThan(BigDecimal value) {
            addCriterion("E_CASE_ID <", value, "eCaseId");
            return (Criteria) this;
        }

        public Criteria andECaseIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("E_CASE_ID <=", value, "eCaseId");
            return (Criteria) this;
        }

        public Criteria andECaseIdIn(List<BigDecimal> values) {
            addCriterion("E_CASE_ID in", values, "eCaseId");
            return (Criteria) this;
        }

        public Criteria andECaseIdNotIn(List<BigDecimal> values) {
            addCriterion("E_CASE_ID not in", values, "eCaseId");
            return (Criteria) this;
        }

        public Criteria andECaseIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("E_CASE_ID between", value1, value2, "eCaseId");
            return (Criteria) this;
        }

        public Criteria andECaseIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("E_CASE_ID not between", value1, value2, "eCaseId");
            return (Criteria) this;
        }

        public Criteria andECaseCodeIsNull() {
            addCriterion("E_CASE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andECaseCodeIsNotNull() {
            addCriterion("E_CASE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andECaseCodeEqualTo(String value) {
            addCriterion("E_CASE_CODE =", value, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andECaseCodeNotEqualTo(String value) {
            addCriterion("E_CASE_CODE <>", value, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andECaseCodeGreaterThan(String value) {
            addCriterion("E_CASE_CODE >", value, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andECaseCodeGreaterThanOrEqualTo(String value) {
            addCriterion("E_CASE_CODE >=", value, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andECaseCodeLessThan(String value) {
            addCriterion("E_CASE_CODE <", value, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andECaseCodeLessThanOrEqualTo(String value) {
            addCriterion("E_CASE_CODE <=", value, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andECaseCodeLike(String value) {
            addCriterion("E_CASE_CODE like", value, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andECaseCodeNotLike(String value) {
            addCriterion("E_CASE_CODE not like", value, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andECaseCodeIn(List<String> values) {
            addCriterion("E_CASE_CODE in", values, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andECaseCodeNotIn(List<String> values) {
            addCriterion("E_CASE_CODE not in", values, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andECaseCodeBetween(String value1, String value2) {
            addCriterion("E_CASE_CODE between", value1, value2, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andECaseCodeNotBetween(String value1, String value2) {
            addCriterion("E_CASE_CODE not between", value1, value2, "eCaseCode");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdIsNull() {
            addCriterion("E_CASE_LEVEL_ID is null");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdIsNotNull() {
            addCriterion("E_CASE_LEVEL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdEqualTo(Short value) {
            addCriterion("E_CASE_LEVEL_ID =", value, "eCaseLevelId");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdNotEqualTo(Short value) {
            addCriterion("E_CASE_LEVEL_ID <>", value, "eCaseLevelId");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdGreaterThan(Short value) {
            addCriterion("E_CASE_LEVEL_ID >", value, "eCaseLevelId");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdGreaterThanOrEqualTo(Short value) {
            addCriterion("E_CASE_LEVEL_ID >=", value, "eCaseLevelId");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdLessThan(Short value) {
            addCriterion("E_CASE_LEVEL_ID <", value, "eCaseLevelId");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdLessThanOrEqualTo(Short value) {
            addCriterion("E_CASE_LEVEL_ID <=", value, "eCaseLevelId");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdIn(List<Short> values) {
            addCriterion("E_CASE_LEVEL_ID in", values, "eCaseLevelId");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdNotIn(List<Short> values) {
            addCriterion("E_CASE_LEVEL_ID not in", values, "eCaseLevelId");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdBetween(Short value1, Short value2) {
            addCriterion("E_CASE_LEVEL_ID between", value1, value2, "eCaseLevelId");
            return (Criteria) this;
        }

        public Criteria andECaseLevelIdNotBetween(Short value1, Short value2) {
            addCriterion("E_CASE_LEVEL_ID not between", value1, value2, "eCaseLevelId");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdIsNull() {
            addCriterion("E_CASE_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdIsNotNull() {
            addCriterion("E_CASE_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdEqualTo(Short value) {
            addCriterion("E_CASE_TYPE_ID =", value, "eCaseTypeId");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdNotEqualTo(Short value) {
            addCriterion("E_CASE_TYPE_ID <>", value, "eCaseTypeId");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdGreaterThan(Short value) {
            addCriterion("E_CASE_TYPE_ID >", value, "eCaseTypeId");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdGreaterThanOrEqualTo(Short value) {
            addCriterion("E_CASE_TYPE_ID >=", value, "eCaseTypeId");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdLessThan(Short value) {
            addCriterion("E_CASE_TYPE_ID <", value, "eCaseTypeId");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdLessThanOrEqualTo(Short value) {
            addCriterion("E_CASE_TYPE_ID <=", value, "eCaseTypeId");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdIn(List<Short> values) {
            addCriterion("E_CASE_TYPE_ID in", values, "eCaseTypeId");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdNotIn(List<Short> values) {
            addCriterion("E_CASE_TYPE_ID not in", values, "eCaseTypeId");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdBetween(Short value1, Short value2) {
            addCriterion("E_CASE_TYPE_ID between", value1, value2, "eCaseTypeId");
            return (Criteria) this;
        }

        public Criteria andECaseTypeIdNotBetween(Short value1, Short value2) {
            addCriterion("E_CASE_TYPE_ID not between", value1, value2, "eCaseTypeId");
            return (Criteria) this;
        }

        public Criteria andHdAddressIsNull() {
            addCriterion("HD_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andHdAddressIsNotNull() {
            addCriterion("HD_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andHdAddressEqualTo(String value) {
            addCriterion("HD_ADDRESS =", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressNotEqualTo(String value) {
            addCriterion("HD_ADDRESS <>", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressGreaterThan(String value) {
            addCriterion("HD_ADDRESS >", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressGreaterThanOrEqualTo(String value) {
            addCriterion("HD_ADDRESS >=", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressLessThan(String value) {
            addCriterion("HD_ADDRESS <", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressLessThanOrEqualTo(String value) {
            addCriterion("HD_ADDRESS <=", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressLike(String value) {
            addCriterion("HD_ADDRESS like", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressNotLike(String value) {
            addCriterion("HD_ADDRESS not like", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressIn(List<String> values) {
            addCriterion("HD_ADDRESS in", values, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressNotIn(List<String> values) {
            addCriterion("HD_ADDRESS not in", values, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressBetween(String value1, String value2) {
            addCriterion("HD_ADDRESS between", value1, value2, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressNotBetween(String value1, String value2) {
            addCriterion("HD_ADDRESS not between", value1, value2, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdDateIsNull() {
            addCriterion("HD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andHdDateIsNotNull() {
            addCriterion("HD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andHdDateEqualTo(Date value) {
            addCriterion("HD_DATE =", value, "hdDate");
            return (Criteria) this;
        }

        public Criteria andHdDateNotEqualTo(Date value) {
            addCriterion("HD_DATE <>", value, "hdDate");
            return (Criteria) this;
        }

        public Criteria andHdDateGreaterThan(Date value) {
            addCriterion("HD_DATE >", value, "hdDate");
            return (Criteria) this;
        }

        public Criteria andHdDateGreaterThanOrEqualTo(Date value) {
            addCriterion("HD_DATE >=", value, "hdDate");
            return (Criteria) this;
        }

        public Criteria andHdDateLessThan(Date value) {
            addCriterion("HD_DATE <", value, "hdDate");
            return (Criteria) this;
        }

        public Criteria andHdDateLessThanOrEqualTo(Date value) {
            addCriterion("HD_DATE <=", value, "hdDate");
            return (Criteria) this;
        }

        public Criteria andHdDateIn(List<Date> values) {
            addCriterion("HD_DATE in", values, "hdDate");
            return (Criteria) this;
        }

        public Criteria andHdDateNotIn(List<Date> values) {
            addCriterion("HD_DATE not in", values, "hdDate");
            return (Criteria) this;
        }

        public Criteria andHdDateBetween(Date value1, Date value2) {
            addCriterion("HD_DATE between", value1, value2, "hdDate");
            return (Criteria) this;
        }

        public Criteria andHdDateNotBetween(Date value1, Date value2) {
            addCriterion("HD_DATE not between", value1, value2, "hdDate");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdIsNull() {
            addCriterion("E_CASE_CD_ID is null");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdIsNotNull() {
            addCriterion("E_CASE_CD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdEqualTo(Short value) {
            addCriterion("E_CASE_CD_ID =", value, "eCaseCdId");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdNotEqualTo(Short value) {
            addCriterion("E_CASE_CD_ID <>", value, "eCaseCdId");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdGreaterThan(Short value) {
            addCriterion("E_CASE_CD_ID >", value, "eCaseCdId");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdGreaterThanOrEqualTo(Short value) {
            addCriterion("E_CASE_CD_ID >=", value, "eCaseCdId");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdLessThan(Short value) {
            addCriterion("E_CASE_CD_ID <", value, "eCaseCdId");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdLessThanOrEqualTo(Short value) {
            addCriterion("E_CASE_CD_ID <=", value, "eCaseCdId");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdIn(List<Short> values) {
            addCriterion("E_CASE_CD_ID in", values, "eCaseCdId");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdNotIn(List<Short> values) {
            addCriterion("E_CASE_CD_ID not in", values, "eCaseCdId");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdBetween(Short value1, Short value2) {
            addCriterion("E_CASE_CD_ID between", value1, value2, "eCaseCdId");
            return (Criteria) this;
        }

        public Criteria andECaseCdIdNotBetween(Short value1, Short value2) {
            addCriterion("E_CASE_CD_ID not between", value1, value2, "eCaseCdId");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdIsNull() {
            addCriterion("E_CASE_BEHAVIOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdIsNotNull() {
            addCriterion("E_CASE_BEHAVIOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdEqualTo(Short value) {
            addCriterion("E_CASE_BEHAVIOR_ID =", value, "eCaseBehaviorId");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdNotEqualTo(Short value) {
            addCriterion("E_CASE_BEHAVIOR_ID <>", value, "eCaseBehaviorId");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdGreaterThan(Short value) {
            addCriterion("E_CASE_BEHAVIOR_ID >", value, "eCaseBehaviorId");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdGreaterThanOrEqualTo(Short value) {
            addCriterion("E_CASE_BEHAVIOR_ID >=", value, "eCaseBehaviorId");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdLessThan(Short value) {
            addCriterion("E_CASE_BEHAVIOR_ID <", value, "eCaseBehaviorId");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdLessThanOrEqualTo(Short value) {
            addCriterion("E_CASE_BEHAVIOR_ID <=", value, "eCaseBehaviorId");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdIn(List<Short> values) {
            addCriterion("E_CASE_BEHAVIOR_ID in", values, "eCaseBehaviorId");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdNotIn(List<Short> values) {
            addCriterion("E_CASE_BEHAVIOR_ID not in", values, "eCaseBehaviorId");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdBetween(Short value1, Short value2) {
            addCriterion("E_CASE_BEHAVIOR_ID between", value1, value2, "eCaseBehaviorId");
            return (Criteria) this;
        }

        public Criteria andECaseBehaviorIdNotBetween(Short value1, Short value2) {
            addCriterion("E_CASE_BEHAVIOR_ID not between", value1, value2, "eCaseBehaviorId");
            return (Criteria) this;
        }

        public Criteria andPersonNumIsNull() {
            addCriterion("PERSON_NUM is null");
            return (Criteria) this;
        }

        public Criteria andPersonNumIsNotNull() {
            addCriterion("PERSON_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andPersonNumEqualTo(Short value) {
            addCriterion("PERSON_NUM =", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumNotEqualTo(Short value) {
            addCriterion("PERSON_NUM <>", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumGreaterThan(Short value) {
            addCriterion("PERSON_NUM >", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumGreaterThanOrEqualTo(Short value) {
            addCriterion("PERSON_NUM >=", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumLessThan(Short value) {
            addCriterion("PERSON_NUM <", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumLessThanOrEqualTo(Short value) {
            addCriterion("PERSON_NUM <=", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumIn(List<Short> values) {
            addCriterion("PERSON_NUM in", values, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumNotIn(List<Short> values) {
            addCriterion("PERSON_NUM not in", values, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumBetween(Short value1, Short value2) {
            addCriterion("PERSON_NUM between", value1, value2, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumNotBetween(Short value1, Short value2) {
            addCriterion("PERSON_NUM not between", value1, value2, "personNum");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameIsNull() {
            addCriterion("SPONSOR_PERSON_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameIsNotNull() {
            addCriterion("SPONSOR_PERSON_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_NAME =", value, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameNotEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_NAME <>", value, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameGreaterThan(String value) {
            addCriterion("SPONSOR_PERSON_NAME >", value, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameGreaterThanOrEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_NAME >=", value, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameLessThan(String value) {
            addCriterion("SPONSOR_PERSON_NAME <", value, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameLessThanOrEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_NAME <=", value, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameLike(String value) {
            addCriterion("SPONSOR_PERSON_NAME like", value, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameNotLike(String value) {
            addCriterion("SPONSOR_PERSON_NAME not like", value, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameIn(List<String> values) {
            addCriterion("SPONSOR_PERSON_NAME in", values, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameNotIn(List<String> values) {
            addCriterion("SPONSOR_PERSON_NAME not in", values, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameBetween(String value1, String value2) {
            addCriterion("SPONSOR_PERSON_NAME between", value1, value2, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonNameNotBetween(String value1, String value2) {
            addCriterion("SPONSOR_PERSON_NAME not between", value1, value2, "sponsorPersonName");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelIsNull() {
            addCriterion("SPONSOR_PERSON_TEL is null");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelIsNotNull() {
            addCriterion("SPONSOR_PERSON_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_TEL =", value, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelNotEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_TEL <>", value, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelGreaterThan(String value) {
            addCriterion("SPONSOR_PERSON_TEL >", value, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelGreaterThanOrEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_TEL >=", value, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelLessThan(String value) {
            addCriterion("SPONSOR_PERSON_TEL <", value, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelLessThanOrEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_TEL <=", value, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelLike(String value) {
            addCriterion("SPONSOR_PERSON_TEL like", value, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelNotLike(String value) {
            addCriterion("SPONSOR_PERSON_TEL not like", value, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelIn(List<String> values) {
            addCriterion("SPONSOR_PERSON_TEL in", values, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelNotIn(List<String> values) {
            addCriterion("SPONSOR_PERSON_TEL not in", values, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelBetween(String value1, String value2) {
            addCriterion("SPONSOR_PERSON_TEL between", value1, value2, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonTelNotBetween(String value1, String value2) {
            addCriterion("SPONSOR_PERSON_TEL not between", value1, value2, "sponsorPersonTel");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressIsNull() {
            addCriterion("SPONSOR_PERSON_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressIsNotNull() {
            addCriterion("SPONSOR_PERSON_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_ADDRESS =", value, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressNotEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_ADDRESS <>", value, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressGreaterThan(String value) {
            addCriterion("SPONSOR_PERSON_ADDRESS >", value, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressGreaterThanOrEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_ADDRESS >=", value, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressLessThan(String value) {
            addCriterion("SPONSOR_PERSON_ADDRESS <", value, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressLessThanOrEqualTo(String value) {
            addCriterion("SPONSOR_PERSON_ADDRESS <=", value, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressLike(String value) {
            addCriterion("SPONSOR_PERSON_ADDRESS like", value, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressNotLike(String value) {
            addCriterion("SPONSOR_PERSON_ADDRESS not like", value, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressIn(List<String> values) {
            addCriterion("SPONSOR_PERSON_ADDRESS in", values, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressNotIn(List<String> values) {
            addCriterion("SPONSOR_PERSON_ADDRESS not in", values, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressBetween(String value1, String value2) {
            addCriterion("SPONSOR_PERSON_ADDRESS between", value1, value2, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andSponsorPersonAddressNotBetween(String value1, String value2) {
            addCriterion("SPONSOR_PERSON_ADDRESS not between", value1, value2, "sponsorPersonAddress");
            return (Criteria) this;
        }

        public Criteria andCoordinateXIsNull() {
            addCriterion("COORDINATE_X is null");
            return (Criteria) this;
        }

        public Criteria andCoordinateXIsNotNull() {
            addCriterion("COORDINATE_X is not null");
            return (Criteria) this;
        }

        public Criteria andCoordinateXEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_X =", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXNotEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_X <>", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXGreaterThan(BigDecimal value) {
            addCriterion("COORDINATE_X >", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_X >=", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXLessThan(BigDecimal value) {
            addCriterion("COORDINATE_X <", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_X <=", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXIn(List<BigDecimal> values) {
            addCriterion("COORDINATE_X in", values, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXNotIn(List<BigDecimal> values) {
            addCriterion("COORDINATE_X not in", values, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COORDINATE_X between", value1, value2, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COORDINATE_X not between", value1, value2, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateYIsNull() {
            addCriterion("COORDINATE_Y is null");
            return (Criteria) this;
        }

        public Criteria andCoordinateYIsNotNull() {
            addCriterion("COORDINATE_Y is not null");
            return (Criteria) this;
        }

        public Criteria andCoordinateYEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_Y =", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYNotEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_Y <>", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYGreaterThan(BigDecimal value) {
            addCriterion("COORDINATE_Y >", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_Y >=", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYLessThan(BigDecimal value) {
            addCriterion("COORDINATE_Y <", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_Y <=", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYIn(List<BigDecimal> values) {
            addCriterion("COORDINATE_Y in", values, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYNotIn(List<BigDecimal> values) {
            addCriterion("COORDINATE_Y not in", values, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COORDINATE_Y between", value1, value2, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COORDINATE_Y not between", value1, value2, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsIsNull() {
            addCriterion("INS_YMDHMS is null");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsIsNotNull() {
            addCriterion("INS_YMDHMS is not null");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsEqualTo(Date value) {
            addCriterion("INS_YMDHMS =", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsNotEqualTo(Date value) {
            addCriterion("INS_YMDHMS <>", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsGreaterThan(Date value) {
            addCriterion("INS_YMDHMS >", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsGreaterThanOrEqualTo(Date value) {
            addCriterion("INS_YMDHMS >=", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsLessThan(Date value) {
            addCriterion("INS_YMDHMS <", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsLessThanOrEqualTo(Date value) {
            addCriterion("INS_YMDHMS <=", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsIn(List<Date> values) {
            addCriterion("INS_YMDHMS in", values, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsNotIn(List<Date> values) {
            addCriterion("INS_YMDHMS not in", values, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsBetween(Date value1, Date value2) {
            addCriterion("INS_YMDHMS between", value1, value2, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsNotBetween(Date value1, Date value2) {
            addCriterion("INS_YMDHMS not between", value1, value2, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsIdIsNull() {
            addCriterion("INS_ID is null");
            return (Criteria) this;
        }

        public Criteria andInsIdIsNotNull() {
            addCriterion("INS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInsIdEqualTo(String value) {
            addCriterion("INS_ID =", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdNotEqualTo(String value) {
            addCriterion("INS_ID <>", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdGreaterThan(String value) {
            addCriterion("INS_ID >", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdGreaterThanOrEqualTo(String value) {
            addCriterion("INS_ID >=", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdLessThan(String value) {
            addCriterion("INS_ID <", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdLessThanOrEqualTo(String value) {
            addCriterion("INS_ID <=", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdLike(String value) {
            addCriterion("INS_ID like", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdNotLike(String value) {
            addCriterion("INS_ID not like", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdIn(List<String> values) {
            addCriterion("INS_ID in", values, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdNotIn(List<String> values) {
            addCriterion("INS_ID not in", values, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdBetween(String value1, String value2) {
            addCriterion("INS_ID between", value1, value2, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdNotBetween(String value1, String value2) {
            addCriterion("INS_ID not between", value1, value2, "insId");
            return (Criteria) this;
        }

        public Criteria andUpdEacIsNull() {
            addCriterion("UPD_EAC is null");
            return (Criteria) this;
        }

        public Criteria andUpdEacIsNotNull() {
            addCriterion("UPD_EAC is not null");
            return (Criteria) this;
        }

        public Criteria andUpdEacEqualTo(Integer value) {
            addCriterion("UPD_EAC =", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacNotEqualTo(Integer value) {
            addCriterion("UPD_EAC <>", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacGreaterThan(Integer value) {
            addCriterion("UPD_EAC >", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacGreaterThanOrEqualTo(Integer value) {
            addCriterion("UPD_EAC >=", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacLessThan(Integer value) {
            addCriterion("UPD_EAC <", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacLessThanOrEqualTo(Integer value) {
            addCriterion("UPD_EAC <=", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacIn(List<Integer> values) {
            addCriterion("UPD_EAC in", values, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacNotIn(List<Integer> values) {
            addCriterion("UPD_EAC not in", values, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacBetween(Integer value1, Integer value2) {
            addCriterion("UPD_EAC between", value1, value2, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacNotBetween(Integer value1, Integer value2) {
            addCriterion("UPD_EAC not between", value1, value2, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsIsNull() {
            addCriterion("UPD_YMDHMS is null");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsIsNotNull() {
            addCriterion("UPD_YMDHMS is not null");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsEqualTo(Date value) {
            addCriterion("UPD_YMDHMS =", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsNotEqualTo(Date value) {
            addCriterion("UPD_YMDHMS <>", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsGreaterThan(Date value) {
            addCriterion("UPD_YMDHMS >", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_YMDHMS >=", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsLessThan(Date value) {
            addCriterion("UPD_YMDHMS <", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsLessThanOrEqualTo(Date value) {
            addCriterion("UPD_YMDHMS <=", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsIn(List<Date> values) {
            addCriterion("UPD_YMDHMS in", values, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsNotIn(List<Date> values) {
            addCriterion("UPD_YMDHMS not in", values, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsBetween(Date value1, Date value2) {
            addCriterion("UPD_YMDHMS between", value1, value2, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsNotBetween(Date value1, Date value2) {
            addCriterion("UPD_YMDHMS not between", value1, value2, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdIdIsNull() {
            addCriterion("UPD_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdIdIsNotNull() {
            addCriterion("UPD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdIdEqualTo(String value) {
            addCriterion("UPD_ID =", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdNotEqualTo(String value) {
            addCriterion("UPD_ID <>", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdGreaterThan(String value) {
            addCriterion("UPD_ID >", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPD_ID >=", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdLessThan(String value) {
            addCriterion("UPD_ID <", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdLessThanOrEqualTo(String value) {
            addCriterion("UPD_ID <=", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdLike(String value) {
            addCriterion("UPD_ID like", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdNotLike(String value) {
            addCriterion("UPD_ID not like", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdIn(List<String> values) {
            addCriterion("UPD_ID in", values, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdNotIn(List<String> values) {
            addCriterion("UPD_ID not in", values, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdBetween(String value1, String value2) {
            addCriterion("UPD_ID between", value1, value2, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdNotBetween(String value1, String value2) {
            addCriterion("UPD_ID not between", value1, value2, "updId");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(String value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(String value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(String value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(String value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(String value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLike(String value) {
            addCriterion("DEL_FLAG like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotLike(String value) {
            addCriterion("DEL_FLAG not like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<String> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<String> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(String value1, String value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(String value1, String value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeIsNull() {
            addCriterion("GLOBAL_UNIT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeIsNotNull() {
            addCriterion("GLOBAL_UNIT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeEqualTo(String value) {
            addCriterion("GLOBAL_UNIT_CODE =", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeNotEqualTo(String value) {
            addCriterion("GLOBAL_UNIT_CODE <>", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeGreaterThan(String value) {
            addCriterion("GLOBAL_UNIT_CODE >", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeGreaterThanOrEqualTo(String value) {
            addCriterion("GLOBAL_UNIT_CODE >=", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeLessThan(String value) {
            addCriterion("GLOBAL_UNIT_CODE <", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeLessThanOrEqualTo(String value) {
            addCriterion("GLOBAL_UNIT_CODE <=", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeLike(String value) {
            addCriterion("GLOBAL_UNIT_CODE like", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeNotLike(String value) {
            addCriterion("GLOBAL_UNIT_CODE not like", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeIn(List<String> values) {
            addCriterion("GLOBAL_UNIT_CODE in", values, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeNotIn(List<String> values) {
            addCriterion("GLOBAL_UNIT_CODE not in", values, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeBetween(String value1, String value2) {
            addCriterion("GLOBAL_UNIT_CODE between", value1, value2, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeNotBetween(String value1, String value2) {
            addCriterion("GLOBAL_UNIT_CODE not between", value1, value2, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andExtFlagIsNull() {
            addCriterion("EXT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andExtFlagIsNotNull() {
            addCriterion("EXT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andExtFlagEqualTo(String value) {
            addCriterion("EXT_FLAG =", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagNotEqualTo(String value) {
            addCriterion("EXT_FLAG <>", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagGreaterThan(String value) {
            addCriterion("EXT_FLAG >", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagGreaterThanOrEqualTo(String value) {
            addCriterion("EXT_FLAG >=", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagLessThan(String value) {
            addCriterion("EXT_FLAG <", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagLessThanOrEqualTo(String value) {
            addCriterion("EXT_FLAG <=", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagLike(String value) {
            addCriterion("EXT_FLAG like", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagNotLike(String value) {
            addCriterion("EXT_FLAG not like", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagIn(List<String> values) {
            addCriterion("EXT_FLAG in", values, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagNotIn(List<String> values) {
            addCriterion("EXT_FLAG not in", values, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagBetween(String value1, String value2) {
            addCriterion("EXT_FLAG between", value1, value2, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagNotBetween(String value1, String value2) {
            addCriterion("EXT_FLAG not between", value1, value2, "extFlag");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkIsNull() {
            addCriterion("E_CASE_ID_SMX_PK is null");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkIsNotNull() {
            addCriterion("E_CASE_ID_SMX_PK is not null");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkEqualTo(String value) {
            addCriterion("E_CASE_ID_SMX_PK =", value, "eCaseIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkNotEqualTo(String value) {
            addCriterion("E_CASE_ID_SMX_PK <>", value, "eCaseIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkGreaterThan(String value) {
            addCriterion("E_CASE_ID_SMX_PK >", value, "eCaseIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkGreaterThanOrEqualTo(String value) {
            addCriterion("E_CASE_ID_SMX_PK >=", value, "eCaseIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkLessThan(String value) {
            addCriterion("E_CASE_ID_SMX_PK <", value, "eCaseIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkLessThanOrEqualTo(String value) {
            addCriterion("E_CASE_ID_SMX_PK <=", value, "eCaseIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkLike(String value) {
            addCriterion("E_CASE_ID_SMX_PK like", value, "eCaseIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkNotLike(String value) {
            addCriterion("E_CASE_ID_SMX_PK not like", value, "eCaseIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkIn(List<String> values) {
            addCriterion("E_CASE_ID_SMX_PK in", values, "eCaseIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkNotIn(List<String> values) {
            addCriterion("E_CASE_ID_SMX_PK not in", values, "eCaseIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkBetween(String value1, String value2) {
            addCriterion("E_CASE_ID_SMX_PK between", value1, value2, "eCaseIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andECaseIdSmxPkNotBetween(String value1, String value2) {
            addCriterion("E_CASE_ID_SMX_PK not between", value1, value2, "eCaseIdSmxPk");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}