package com.zhixin.rd.rkjc.web.entity.qk;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbleOrgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    public TbleOrgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEOrgIdIsNull() {
            addCriterion("E_ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andEOrgIdIsNotNull() {
            addCriterion("E_ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEOrgIdEqualTo(BigDecimal value) {
            addCriterion("E_ORG_ID =", value, "eOrgId");
            return (Criteria) this;
        }

        public Criteria andEOrgIdNotEqualTo(BigDecimal value) {
            addCriterion("E_ORG_ID <>", value, "eOrgId");
            return (Criteria) this;
        }

        public Criteria andEOrgIdGreaterThan(BigDecimal value) {
            addCriterion("E_ORG_ID >", value, "eOrgId");
            return (Criteria) this;
        }

        public Criteria andEOrgIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("E_ORG_ID >=", value, "eOrgId");
            return (Criteria) this;
        }

        public Criteria andEOrgIdLessThan(BigDecimal value) {
            addCriterion("E_ORG_ID <", value, "eOrgId");
            return (Criteria) this;
        }

        public Criteria andEOrgIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("E_ORG_ID <=", value, "eOrgId");
            return (Criteria) this;
        }

        public Criteria andEOrgIdIn(List<BigDecimal> values) {
            addCriterion("E_ORG_ID in", values, "eOrgId");
            return (Criteria) this;
        }

        public Criteria andEOrgIdNotIn(List<BigDecimal> values) {
            addCriterion("E_ORG_ID not in", values, "eOrgId");
            return (Criteria) this;
        }

        public Criteria andEOrgIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("E_ORG_ID between", value1, value2, "eOrgId");
            return (Criteria) this;
        }

        public Criteria andEOrgIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("E_ORG_ID not between", value1, value2, "eOrgId");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeIsNull() {
            addCriterion("E_ORG_CODE is null");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeIsNotNull() {
            addCriterion("E_ORG_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeEqualTo(String value) {
            addCriterion("E_ORG_CODE =", value, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeNotEqualTo(String value) {
            addCriterion("E_ORG_CODE <>", value, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeGreaterThan(String value) {
            addCriterion("E_ORG_CODE >", value, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("E_ORG_CODE >=", value, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeLessThan(String value) {
            addCriterion("E_ORG_CODE <", value, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("E_ORG_CODE <=", value, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeLike(String value) {
            addCriterion("E_ORG_CODE like", value, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeNotLike(String value) {
            addCriterion("E_ORG_CODE not like", value, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeIn(List<String> values) {
            addCriterion("E_ORG_CODE in", values, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeNotIn(List<String> values) {
            addCriterion("E_ORG_CODE not in", values, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeBetween(String value1, String value2) {
            addCriterion("E_ORG_CODE between", value1, value2, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andEOrgCodeNotBetween(String value1, String value2) {
            addCriterion("E_ORG_CODE not between", value1, value2, "eOrgCode");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAboutIsNull() {
            addCriterion("ABOUT is null");
            return (Criteria) this;
        }

        public Criteria andAboutIsNotNull() {
            addCriterion("ABOUT is not null");
            return (Criteria) this;
        }

        public Criteria andAboutEqualTo(String value) {
            addCriterion("ABOUT =", value, "about");
            return (Criteria) this;
        }

        public Criteria andAboutNotEqualTo(String value) {
            addCriterion("ABOUT <>", value, "about");
            return (Criteria) this;
        }

        public Criteria andAboutGreaterThan(String value) {
            addCriterion("ABOUT >", value, "about");
            return (Criteria) this;
        }

        public Criteria andAboutGreaterThanOrEqualTo(String value) {
            addCriterion("ABOUT >=", value, "about");
            return (Criteria) this;
        }

        public Criteria andAboutLessThan(String value) {
            addCriterion("ABOUT <", value, "about");
            return (Criteria) this;
        }

        public Criteria andAboutLessThanOrEqualTo(String value) {
            addCriterion("ABOUT <=", value, "about");
            return (Criteria) this;
        }

        public Criteria andAboutLike(String value) {
            addCriterion("ABOUT like", value, "about");
            return (Criteria) this;
        }

        public Criteria andAboutNotLike(String value) {
            addCriterion("ABOUT not like", value, "about");
            return (Criteria) this;
        }

        public Criteria andAboutIn(List<String> values) {
            addCriterion("ABOUT in", values, "about");
            return (Criteria) this;
        }

        public Criteria andAboutNotIn(List<String> values) {
            addCriterion("ABOUT not in", values, "about");
            return (Criteria) this;
        }

        public Criteria andAboutBetween(String value1, String value2) {
            addCriterion("ABOUT between", value1, value2, "about");
            return (Criteria) this;
        }

        public Criteria andAboutNotBetween(String value1, String value2) {
            addCriterion("ABOUT not between", value1, value2, "about");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdIsNull() {
            addCriterion("E_ORG_LEVEL_ID is null");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdIsNotNull() {
            addCriterion("E_ORG_LEVEL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdEqualTo(Short value) {
            addCriterion("E_ORG_LEVEL_ID =", value, "eOrgLevelId");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdNotEqualTo(Short value) {
            addCriterion("E_ORG_LEVEL_ID <>", value, "eOrgLevelId");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdGreaterThan(Short value) {
            addCriterion("E_ORG_LEVEL_ID >", value, "eOrgLevelId");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdGreaterThanOrEqualTo(Short value) {
            addCriterion("E_ORG_LEVEL_ID >=", value, "eOrgLevelId");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdLessThan(Short value) {
            addCriterion("E_ORG_LEVEL_ID <", value, "eOrgLevelId");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdLessThanOrEqualTo(Short value) {
            addCriterion("E_ORG_LEVEL_ID <=", value, "eOrgLevelId");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdIn(List<Short> values) {
            addCriterion("E_ORG_LEVEL_ID in", values, "eOrgLevelId");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdNotIn(List<Short> values) {
            addCriterion("E_ORG_LEVEL_ID not in", values, "eOrgLevelId");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdBetween(Short value1, Short value2) {
            addCriterion("E_ORG_LEVEL_ID between", value1, value2, "eOrgLevelId");
            return (Criteria) this;
        }

        public Criteria andEOrgLevelIdNotBetween(Short value1, Short value2) {
            addCriterion("E_ORG_LEVEL_ID not between", value1, value2, "eOrgLevelId");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdIsNull() {
            addCriterion("E_ORG_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdIsNotNull() {
            addCriterion("E_ORG_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdEqualTo(Short value) {
            addCriterion("E_ORG_TYPE_ID =", value, "eOrgTypeId");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdNotEqualTo(Short value) {
            addCriterion("E_ORG_TYPE_ID <>", value, "eOrgTypeId");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdGreaterThan(Short value) {
            addCriterion("E_ORG_TYPE_ID >", value, "eOrgTypeId");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdGreaterThanOrEqualTo(Short value) {
            addCriterion("E_ORG_TYPE_ID >=", value, "eOrgTypeId");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdLessThan(Short value) {
            addCriterion("E_ORG_TYPE_ID <", value, "eOrgTypeId");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdLessThanOrEqualTo(Short value) {
            addCriterion("E_ORG_TYPE_ID <=", value, "eOrgTypeId");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdIn(List<Short> values) {
            addCriterion("E_ORG_TYPE_ID in", values, "eOrgTypeId");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdNotIn(List<Short> values) {
            addCriterion("E_ORG_TYPE_ID not in", values, "eOrgTypeId");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdBetween(Short value1, Short value2) {
            addCriterion("E_ORG_TYPE_ID between", value1, value2, "eOrgTypeId");
            return (Criteria) this;
        }

        public Criteria andEOrgTypeIdNotBetween(Short value1, Short value2) {
            addCriterion("E_ORG_TYPE_ID not between", value1, value2, "eOrgTypeId");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdIsNull() {
            addCriterion("E_ORG_TYPE2_ID is null");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdIsNotNull() {
            addCriterion("E_ORG_TYPE2_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdEqualTo(Short value) {
            addCriterion("E_ORG_TYPE2_ID =", value, "eOrgType2Id");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdNotEqualTo(Short value) {
            addCriterion("E_ORG_TYPE2_ID <>", value, "eOrgType2Id");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdGreaterThan(Short value) {
            addCriterion("E_ORG_TYPE2_ID >", value, "eOrgType2Id");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdGreaterThanOrEqualTo(Short value) {
            addCriterion("E_ORG_TYPE2_ID >=", value, "eOrgType2Id");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdLessThan(Short value) {
            addCriterion("E_ORG_TYPE2_ID <", value, "eOrgType2Id");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdLessThanOrEqualTo(Short value) {
            addCriterion("E_ORG_TYPE2_ID <=", value, "eOrgType2Id");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdIn(List<Short> values) {
            addCriterion("E_ORG_TYPE2_ID in", values, "eOrgType2Id");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdNotIn(List<Short> values) {
            addCriterion("E_ORG_TYPE2_ID not in", values, "eOrgType2Id");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdBetween(Short value1, Short value2) {
            addCriterion("E_ORG_TYPE2_ID between", value1, value2, "eOrgType2Id");
            return (Criteria) this;
        }

        public Criteria andEOrgType2IdNotBetween(Short value1, Short value2) {
            addCriterion("E_ORG_TYPE2_ID not between", value1, value2, "eOrgType2Id");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterion("START_DATE =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterion("START_DATE <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterion("START_DATE >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("START_DATE >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterion("START_DATE <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterion("START_DATE <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterion("START_DATE in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterion("START_DATE not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterion("START_DATE between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterion("START_DATE not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andHdAddressIsNull() {
            addCriterion("HD_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andHdAddressIsNotNull() {
            addCriterion("HD_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andHdAddressEqualTo(String value) {
            addCriterion("HD_ADDRESS =", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressNotEqualTo(String value) {
            addCriterion("HD_ADDRESS <>", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressGreaterThan(String value) {
            addCriterion("HD_ADDRESS >", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressGreaterThanOrEqualTo(String value) {
            addCriterion("HD_ADDRESS >=", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressLessThan(String value) {
            addCriterion("HD_ADDRESS <", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressLessThanOrEqualTo(String value) {
            addCriterion("HD_ADDRESS <=", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressLike(String value) {
            addCriterion("HD_ADDRESS like", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressNotLike(String value) {
            addCriterion("HD_ADDRESS not like", value, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressIn(List<String> values) {
            addCriterion("HD_ADDRESS in", values, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressNotIn(List<String> values) {
            addCriterion("HD_ADDRESS not in", values, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressBetween(String value1, String value2) {
            addCriterion("HD_ADDRESS between", value1, value2, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andHdAddressNotBetween(String value1, String value2) {
            addCriterion("HD_ADDRESS not between", value1, value2, "hdAddress");
            return (Criteria) this;
        }

        public Criteria andPersonNumIsNull() {
            addCriterion("PERSON_NUM is null");
            return (Criteria) this;
        }

        public Criteria andPersonNumIsNotNull() {
            addCriterion("PERSON_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andPersonNumEqualTo(Short value) {
            addCriterion("PERSON_NUM =", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumNotEqualTo(Short value) {
            addCriterion("PERSON_NUM <>", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumGreaterThan(Short value) {
            addCriterion("PERSON_NUM >", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumGreaterThanOrEqualTo(Short value) {
            addCriterion("PERSON_NUM >=", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumLessThan(Short value) {
            addCriterion("PERSON_NUM <", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumLessThanOrEqualTo(Short value) {
            addCriterion("PERSON_NUM <=", value, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumIn(List<Short> values) {
            addCriterion("PERSON_NUM in", values, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumNotIn(List<Short> values) {
            addCriterion("PERSON_NUM not in", values, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumBetween(Short value1, Short value2) {
            addCriterion("PERSON_NUM between", value1, value2, "personNum");
            return (Criteria) this;
        }

        public Criteria andPersonNumNotBetween(Short value1, Short value2) {
            addCriterion("PERSON_NUM not between", value1, value2, "personNum");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameIsNull() {
            addCriterion("CHARGE_PERSON_NAME is null");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameIsNotNull() {
            addCriterion("CHARGE_PERSON_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameEqualTo(String value) {
            addCriterion("CHARGE_PERSON_NAME =", value, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameNotEqualTo(String value) {
            addCriterion("CHARGE_PERSON_NAME <>", value, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameGreaterThan(String value) {
            addCriterion("CHARGE_PERSON_NAME >", value, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameGreaterThanOrEqualTo(String value) {
            addCriterion("CHARGE_PERSON_NAME >=", value, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameLessThan(String value) {
            addCriterion("CHARGE_PERSON_NAME <", value, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameLessThanOrEqualTo(String value) {
            addCriterion("CHARGE_PERSON_NAME <=", value, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameLike(String value) {
            addCriterion("CHARGE_PERSON_NAME like", value, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameNotLike(String value) {
            addCriterion("CHARGE_PERSON_NAME not like", value, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameIn(List<String> values) {
            addCriterion("CHARGE_PERSON_NAME in", values, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameNotIn(List<String> values) {
            addCriterion("CHARGE_PERSON_NAME not in", values, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameBetween(String value1, String value2) {
            addCriterion("CHARGE_PERSON_NAME between", value1, value2, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonNameNotBetween(String value1, String value2) {
            addCriterion("CHARGE_PERSON_NAME not between", value1, value2, "chargePersonName");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelIsNull() {
            addCriterion("CHARGE_PERSON_TEL is null");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelIsNotNull() {
            addCriterion("CHARGE_PERSON_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelEqualTo(String value) {
            addCriterion("CHARGE_PERSON_TEL =", value, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelNotEqualTo(String value) {
            addCriterion("CHARGE_PERSON_TEL <>", value, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelGreaterThan(String value) {
            addCriterion("CHARGE_PERSON_TEL >", value, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelGreaterThanOrEqualTo(String value) {
            addCriterion("CHARGE_PERSON_TEL >=", value, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelLessThan(String value) {
            addCriterion("CHARGE_PERSON_TEL <", value, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelLessThanOrEqualTo(String value) {
            addCriterion("CHARGE_PERSON_TEL <=", value, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelLike(String value) {
            addCriterion("CHARGE_PERSON_TEL like", value, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelNotLike(String value) {
            addCriterion("CHARGE_PERSON_TEL not like", value, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelIn(List<String> values) {
            addCriterion("CHARGE_PERSON_TEL in", values, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelNotIn(List<String> values) {
            addCriterion("CHARGE_PERSON_TEL not in", values, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelBetween(String value1, String value2) {
            addCriterion("CHARGE_PERSON_TEL between", value1, value2, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonTelNotBetween(String value1, String value2) {
            addCriterion("CHARGE_PERSON_TEL not between", value1, value2, "chargePersonTel");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressIsNull() {
            addCriterion("CHARGE_PERSON_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressIsNotNull() {
            addCriterion("CHARGE_PERSON_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressEqualTo(String value) {
            addCriterion("CHARGE_PERSON_ADDRESS =", value, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressNotEqualTo(String value) {
            addCriterion("CHARGE_PERSON_ADDRESS <>", value, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressGreaterThan(String value) {
            addCriterion("CHARGE_PERSON_ADDRESS >", value, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressGreaterThanOrEqualTo(String value) {
            addCriterion("CHARGE_PERSON_ADDRESS >=", value, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressLessThan(String value) {
            addCriterion("CHARGE_PERSON_ADDRESS <", value, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressLessThanOrEqualTo(String value) {
            addCriterion("CHARGE_PERSON_ADDRESS <=", value, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressLike(String value) {
            addCriterion("CHARGE_PERSON_ADDRESS like", value, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressNotLike(String value) {
            addCriterion("CHARGE_PERSON_ADDRESS not like", value, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressIn(List<String> values) {
            addCriterion("CHARGE_PERSON_ADDRESS in", values, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressNotIn(List<String> values) {
            addCriterion("CHARGE_PERSON_ADDRESS not in", values, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressBetween(String value1, String value2) {
            addCriterion("CHARGE_PERSON_ADDRESS between", value1, value2, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andChargePersonAddressNotBetween(String value1, String value2) {
            addCriterion("CHARGE_PERSON_ADDRESS not between", value1, value2, "chargePersonAddress");
            return (Criteria) this;
        }

        public Criteria andCoordinateXIsNull() {
            addCriterion("COORDINATE_X is null");
            return (Criteria) this;
        }

        public Criteria andCoordinateXIsNotNull() {
            addCriterion("COORDINATE_X is not null");
            return (Criteria) this;
        }

        public Criteria andCoordinateXEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_X =", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXNotEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_X <>", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXGreaterThan(BigDecimal value) {
            addCriterion("COORDINATE_X >", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_X >=", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXLessThan(BigDecimal value) {
            addCriterion("COORDINATE_X <", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_X <=", value, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXIn(List<BigDecimal> values) {
            addCriterion("COORDINATE_X in", values, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXNotIn(List<BigDecimal> values) {
            addCriterion("COORDINATE_X not in", values, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COORDINATE_X between", value1, value2, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateXNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COORDINATE_X not between", value1, value2, "coordinateX");
            return (Criteria) this;
        }

        public Criteria andCoordinateYIsNull() {
            addCriterion("COORDINATE_Y is null");
            return (Criteria) this;
        }

        public Criteria andCoordinateYIsNotNull() {
            addCriterion("COORDINATE_Y is not null");
            return (Criteria) this;
        }

        public Criteria andCoordinateYEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_Y =", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYNotEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_Y <>", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYGreaterThan(BigDecimal value) {
            addCriterion("COORDINATE_Y >", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_Y >=", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYLessThan(BigDecimal value) {
            addCriterion("COORDINATE_Y <", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COORDINATE_Y <=", value, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYIn(List<BigDecimal> values) {
            addCriterion("COORDINATE_Y in", values, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYNotIn(List<BigDecimal> values) {
            addCriterion("COORDINATE_Y not in", values, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COORDINATE_Y between", value1, value2, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andCoordinateYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COORDINATE_Y not between", value1, value2, "coordinateY");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsIsNull() {
            addCriterion("INS_YMDHMS is null");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsIsNotNull() {
            addCriterion("INS_YMDHMS is not null");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsEqualTo(Date value) {
            addCriterion("INS_YMDHMS =", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsNotEqualTo(Date value) {
            addCriterion("INS_YMDHMS <>", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsGreaterThan(Date value) {
            addCriterion("INS_YMDHMS >", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsGreaterThanOrEqualTo(Date value) {
            addCriterion("INS_YMDHMS >=", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsLessThan(Date value) {
            addCriterion("INS_YMDHMS <", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsLessThanOrEqualTo(Date value) {
            addCriterion("INS_YMDHMS <=", value, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsIn(List<Date> values) {
            addCriterion("INS_YMDHMS in", values, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsNotIn(List<Date> values) {
            addCriterion("INS_YMDHMS not in", values, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsBetween(Date value1, Date value2) {
            addCriterion("INS_YMDHMS between", value1, value2, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsYmdhmsNotBetween(Date value1, Date value2) {
            addCriterion("INS_YMDHMS not between", value1, value2, "insYmdhms");
            return (Criteria) this;
        }

        public Criteria andInsIdIsNull() {
            addCriterion("INS_ID is null");
            return (Criteria) this;
        }

        public Criteria andInsIdIsNotNull() {
            addCriterion("INS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInsIdEqualTo(String value) {
            addCriterion("INS_ID =", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdNotEqualTo(String value) {
            addCriterion("INS_ID <>", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdGreaterThan(String value) {
            addCriterion("INS_ID >", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdGreaterThanOrEqualTo(String value) {
            addCriterion("INS_ID >=", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdLessThan(String value) {
            addCriterion("INS_ID <", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdLessThanOrEqualTo(String value) {
            addCriterion("INS_ID <=", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdLike(String value) {
            addCriterion("INS_ID like", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdNotLike(String value) {
            addCriterion("INS_ID not like", value, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdIn(List<String> values) {
            addCriterion("INS_ID in", values, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdNotIn(List<String> values) {
            addCriterion("INS_ID not in", values, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdBetween(String value1, String value2) {
            addCriterion("INS_ID between", value1, value2, "insId");
            return (Criteria) this;
        }

        public Criteria andInsIdNotBetween(String value1, String value2) {
            addCriterion("INS_ID not between", value1, value2, "insId");
            return (Criteria) this;
        }

        public Criteria andUpdEacIsNull() {
            addCriterion("UPD_EAC is null");
            return (Criteria) this;
        }

        public Criteria andUpdEacIsNotNull() {
            addCriterion("UPD_EAC is not null");
            return (Criteria) this;
        }

        public Criteria andUpdEacEqualTo(Integer value) {
            addCriterion("UPD_EAC =", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacNotEqualTo(Integer value) {
            addCriterion("UPD_EAC <>", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacGreaterThan(Integer value) {
            addCriterion("UPD_EAC >", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacGreaterThanOrEqualTo(Integer value) {
            addCriterion("UPD_EAC >=", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacLessThan(Integer value) {
            addCriterion("UPD_EAC <", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacLessThanOrEqualTo(Integer value) {
            addCriterion("UPD_EAC <=", value, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacIn(List<Integer> values) {
            addCriterion("UPD_EAC in", values, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacNotIn(List<Integer> values) {
            addCriterion("UPD_EAC not in", values, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacBetween(Integer value1, Integer value2) {
            addCriterion("UPD_EAC between", value1, value2, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdEacNotBetween(Integer value1, Integer value2) {
            addCriterion("UPD_EAC not between", value1, value2, "updEac");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsIsNull() {
            addCriterion("UPD_YMDHMS is null");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsIsNotNull() {
            addCriterion("UPD_YMDHMS is not null");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsEqualTo(Date value) {
            addCriterion("UPD_YMDHMS =", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsNotEqualTo(Date value) {
            addCriterion("UPD_YMDHMS <>", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsGreaterThan(Date value) {
            addCriterion("UPD_YMDHMS >", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_YMDHMS >=", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsLessThan(Date value) {
            addCriterion("UPD_YMDHMS <", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsLessThanOrEqualTo(Date value) {
            addCriterion("UPD_YMDHMS <=", value, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsIn(List<Date> values) {
            addCriterion("UPD_YMDHMS in", values, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsNotIn(List<Date> values) {
            addCriterion("UPD_YMDHMS not in", values, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsBetween(Date value1, Date value2) {
            addCriterion("UPD_YMDHMS between", value1, value2, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdYmdhmsNotBetween(Date value1, Date value2) {
            addCriterion("UPD_YMDHMS not between", value1, value2, "updYmdhms");
            return (Criteria) this;
        }

        public Criteria andUpdIdIsNull() {
            addCriterion("UPD_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdIdIsNotNull() {
            addCriterion("UPD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdIdEqualTo(String value) {
            addCriterion("UPD_ID =", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdNotEqualTo(String value) {
            addCriterion("UPD_ID <>", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdGreaterThan(String value) {
            addCriterion("UPD_ID >", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPD_ID >=", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdLessThan(String value) {
            addCriterion("UPD_ID <", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdLessThanOrEqualTo(String value) {
            addCriterion("UPD_ID <=", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdLike(String value) {
            addCriterion("UPD_ID like", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdNotLike(String value) {
            addCriterion("UPD_ID not like", value, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdIn(List<String> values) {
            addCriterion("UPD_ID in", values, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdNotIn(List<String> values) {
            addCriterion("UPD_ID not in", values, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdBetween(String value1, String value2) {
            addCriterion("UPD_ID between", value1, value2, "updId");
            return (Criteria) this;
        }

        public Criteria andUpdIdNotBetween(String value1, String value2) {
            addCriterion("UPD_ID not between", value1, value2, "updId");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(String value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(String value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(String value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(String value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(String value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLike(String value) {
            addCriterion("DEL_FLAG like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotLike(String value) {
            addCriterion("DEL_FLAG not like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<String> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<String> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(String value1, String value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(String value1, String value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeIsNull() {
            addCriterion("GLOBAL_UNIT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeIsNotNull() {
            addCriterion("GLOBAL_UNIT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeEqualTo(String value) {
            addCriterion("GLOBAL_UNIT_CODE =", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeNotEqualTo(String value) {
            addCriterion("GLOBAL_UNIT_CODE <>", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeGreaterThan(String value) {
            addCriterion("GLOBAL_UNIT_CODE >", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeGreaterThanOrEqualTo(String value) {
            addCriterion("GLOBAL_UNIT_CODE >=", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeLessThan(String value) {
            addCriterion("GLOBAL_UNIT_CODE <", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeLessThanOrEqualTo(String value) {
            addCriterion("GLOBAL_UNIT_CODE <=", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeLike(String value) {
            addCriterion("GLOBAL_UNIT_CODE like", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeNotLike(String value) {
            addCriterion("GLOBAL_UNIT_CODE not like", value, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeIn(List<String> values) {
            addCriterion("GLOBAL_UNIT_CODE in", values, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeNotIn(List<String> values) {
            addCriterion("GLOBAL_UNIT_CODE not in", values, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeBetween(String value1, String value2) {
            addCriterion("GLOBAL_UNIT_CODE between", value1, value2, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andGlobalUnitCodeNotBetween(String value1, String value2) {
            addCriterion("GLOBAL_UNIT_CODE not between", value1, value2, "globalUnitCode");
            return (Criteria) this;
        }

        public Criteria andExtFlagIsNull() {
            addCriterion("EXT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andExtFlagIsNotNull() {
            addCriterion("EXT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andExtFlagEqualTo(String value) {
            addCriterion("EXT_FLAG =", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagNotEqualTo(String value) {
            addCriterion("EXT_FLAG <>", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagGreaterThan(String value) {
            addCriterion("EXT_FLAG >", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagGreaterThanOrEqualTo(String value) {
            addCriterion("EXT_FLAG >=", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagLessThan(String value) {
            addCriterion("EXT_FLAG <", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagLessThanOrEqualTo(String value) {
            addCriterion("EXT_FLAG <=", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagLike(String value) {
            addCriterion("EXT_FLAG like", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagNotLike(String value) {
            addCriterion("EXT_FLAG not like", value, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagIn(List<String> values) {
            addCriterion("EXT_FLAG in", values, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagNotIn(List<String> values) {
            addCriterion("EXT_FLAG not in", values, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagBetween(String value1, String value2) {
            addCriterion("EXT_FLAG between", value1, value2, "extFlag");
            return (Criteria) this;
        }

        public Criteria andExtFlagNotBetween(String value1, String value2) {
            addCriterion("EXT_FLAG not between", value1, value2, "extFlag");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardIsNull() {
            addCriterion("CHARGE_PERSON_IDCARD is null");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardIsNotNull() {
            addCriterion("CHARGE_PERSON_IDCARD is not null");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardEqualTo(String value) {
            addCriterion("CHARGE_PERSON_IDCARD =", value, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardNotEqualTo(String value) {
            addCriterion("CHARGE_PERSON_IDCARD <>", value, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardGreaterThan(String value) {
            addCriterion("CHARGE_PERSON_IDCARD >", value, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("CHARGE_PERSON_IDCARD >=", value, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardLessThan(String value) {
            addCriterion("CHARGE_PERSON_IDCARD <", value, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardLessThanOrEqualTo(String value) {
            addCriterion("CHARGE_PERSON_IDCARD <=", value, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardLike(String value) {
            addCriterion("CHARGE_PERSON_IDCARD like", value, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardNotLike(String value) {
            addCriterion("CHARGE_PERSON_IDCARD not like", value, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardIn(List<String> values) {
            addCriterion("CHARGE_PERSON_IDCARD in", values, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardNotIn(List<String> values) {
            addCriterion("CHARGE_PERSON_IDCARD not in", values, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardBetween(String value1, String value2) {
            addCriterion("CHARGE_PERSON_IDCARD between", value1, value2, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andChargePersonIdcardNotBetween(String value1, String value2) {
            addCriterion("CHARGE_PERSON_IDCARD not between", value1, value2, "chargePersonIdcard");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkIsNull() {
            addCriterion("E_ORG_ID_SMX_PK is null");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkIsNotNull() {
            addCriterion("E_ORG_ID_SMX_PK is not null");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkEqualTo(String value) {
            addCriterion("E_ORG_ID_SMX_PK =", value, "eOrgIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkNotEqualTo(String value) {
            addCriterion("E_ORG_ID_SMX_PK <>", value, "eOrgIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkGreaterThan(String value) {
            addCriterion("E_ORG_ID_SMX_PK >", value, "eOrgIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkGreaterThanOrEqualTo(String value) {
            addCriterion("E_ORG_ID_SMX_PK >=", value, "eOrgIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkLessThan(String value) {
            addCriterion("E_ORG_ID_SMX_PK <", value, "eOrgIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkLessThanOrEqualTo(String value) {
            addCriterion("E_ORG_ID_SMX_PK <=", value, "eOrgIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkLike(String value) {
            addCriterion("E_ORG_ID_SMX_PK like", value, "eOrgIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkNotLike(String value) {
            addCriterion("E_ORG_ID_SMX_PK not like", value, "eOrgIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkIn(List<String> values) {
            addCriterion("E_ORG_ID_SMX_PK in", values, "eOrgIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkNotIn(List<String> values) {
            addCriterion("E_ORG_ID_SMX_PK not in", values, "eOrgIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkBetween(String value1, String value2) {
            addCriterion("E_ORG_ID_SMX_PK between", value1, value2, "eOrgIdSmxPk");
            return (Criteria) this;
        }

        public Criteria andEOrgIdSmxPkNotBetween(String value1, String value2) {
            addCriterion("E_ORG_ID_SMX_PK not between", value1, value2, "eOrgIdSmxPk");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}