package com.zhixin.rd.rkjc.web.entity.qk;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TbleCase implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.E_CASE_ID
     *
     * @mbggenerated
     */
    private BigDecimal eCaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.E_CASE_CODE
     *
     * @mbggenerated
     */
    private String eCaseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.E_CASE_LEVEL_ID
     *
     * @mbggenerated
     */
    private Short eCaseLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.E_CASE_TYPE_ID
     *
     * @mbggenerated
     */
    private Short eCaseTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.HD_ADDRESS
     *
     * @mbggenerated
     */
    private String hdAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.HD_DATE
     *
     * @mbggenerated
     */
    private Date hdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.E_CASE_CD_ID
     *
     * @mbggenerated
     */
    private Short eCaseCdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.E_CASE_BEHAVIOR_ID
     *
     * @mbggenerated
     */
    private Short eCaseBehaviorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.PERSON_NUM
     *
     * @mbggenerated
     */
    private Short personNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.SPONSOR_PERSON_NAME
     *
     * @mbggenerated
     */
    private String sponsorPersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.SPONSOR_PERSON_TEL
     *
     * @mbggenerated
     */
    private String sponsorPersonTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.SPONSOR_PERSON_ADDRESS
     *
     * @mbggenerated
     */
    private String sponsorPersonAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.COORDINATE_X
     *
     * @mbggenerated
     */
    private BigDecimal coordinateX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.COORDINATE_Y
     *
     * @mbggenerated
     */
    private BigDecimal coordinateY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.INS_YMDHMS
     *
     * @mbggenerated
     */
    private Date insYmdhms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.INS_ID
     *
     * @mbggenerated
     */
    private String insId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.UPD_EAC
     *
     * @mbggenerated
     */
    private Integer updEac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.UPD_YMDHMS
     *
     * @mbggenerated
     */
    private Date updYmdhms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.UPD_ID
     *
     * @mbggenerated
     */
    private String updId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.DEL_FLAG
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.GLOBAL_UNIT_CODE
     *
     * @mbggenerated
     */
    private String globalUnitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.EXT_FLAG
     *
     * @mbggenerated
     */
    private String extFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_CASE.E_CASE_ID_SMX_PK
     *
     * @mbggenerated
     */
    private String eCaseIdSmxPk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.E_CASE_ID
     *
     * @return the value of TBL_E_CASE.E_CASE_ID
     *
     * @mbggenerated
     */
    public BigDecimal geteCaseId() {
        return eCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.E_CASE_ID
     *
     * @param eCaseId the value for TBL_E_CASE.E_CASE_ID
     *
     * @mbggenerated
     */
    public void seteCaseId(BigDecimal eCaseId) {
        this.eCaseId = eCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.E_CASE_CODE
     *
     * @return the value of TBL_E_CASE.E_CASE_CODE
     *
     * @mbggenerated
     */
    public String geteCaseCode() {
        return eCaseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.E_CASE_CODE
     *
     * @param eCaseCode the value for TBL_E_CASE.E_CASE_CODE
     *
     * @mbggenerated
     */
    public void seteCaseCode(String eCaseCode) {
        this.eCaseCode = eCaseCode == null ? null : eCaseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.NAME
     *
     * @return the value of TBL_E_CASE.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.NAME
     *
     * @param name the value for TBL_E_CASE.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.E_CASE_LEVEL_ID
     *
     * @return the value of TBL_E_CASE.E_CASE_LEVEL_ID
     *
     * @mbggenerated
     */
    public Short geteCaseLevelId() {
        return eCaseLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.E_CASE_LEVEL_ID
     *
     * @param eCaseLevelId the value for TBL_E_CASE.E_CASE_LEVEL_ID
     *
     * @mbggenerated
     */
    public void seteCaseLevelId(Short eCaseLevelId) {
        this.eCaseLevelId = eCaseLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.E_CASE_TYPE_ID
     *
     * @return the value of TBL_E_CASE.E_CASE_TYPE_ID
     *
     * @mbggenerated
     */
    public Short geteCaseTypeId() {
        return eCaseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.E_CASE_TYPE_ID
     *
     * @param eCaseTypeId the value for TBL_E_CASE.E_CASE_TYPE_ID
     *
     * @mbggenerated
     */
    public void seteCaseTypeId(Short eCaseTypeId) {
        this.eCaseTypeId = eCaseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.HD_ADDRESS
     *
     * @return the value of TBL_E_CASE.HD_ADDRESS
     *
     * @mbggenerated
     */
    public String getHdAddress() {
        return hdAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.HD_ADDRESS
     *
     * @param hdAddress the value for TBL_E_CASE.HD_ADDRESS
     *
     * @mbggenerated
     */
    public void setHdAddress(String hdAddress) {
        this.hdAddress = hdAddress == null ? null : hdAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.HD_DATE
     *
     * @return the value of TBL_E_CASE.HD_DATE
     *
     * @mbggenerated
     */
    public Date getHdDate() {
        return hdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.HD_DATE
     *
     * @param hdDate the value for TBL_E_CASE.HD_DATE
     *
     * @mbggenerated
     */
    public void setHdDate(Date hdDate) {
        this.hdDate = hdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.E_CASE_CD_ID
     *
     * @return the value of TBL_E_CASE.E_CASE_CD_ID
     *
     * @mbggenerated
     */
    public Short geteCaseCdId() {
        return eCaseCdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.E_CASE_CD_ID
     *
     * @param eCaseCdId the value for TBL_E_CASE.E_CASE_CD_ID
     *
     * @mbggenerated
     */
    public void seteCaseCdId(Short eCaseCdId) {
        this.eCaseCdId = eCaseCdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.E_CASE_BEHAVIOR_ID
     *
     * @return the value of TBL_E_CASE.E_CASE_BEHAVIOR_ID
     *
     * @mbggenerated
     */
    public Short geteCaseBehaviorId() {
        return eCaseBehaviorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.E_CASE_BEHAVIOR_ID
     *
     * @param eCaseBehaviorId the value for TBL_E_CASE.E_CASE_BEHAVIOR_ID
     *
     * @mbggenerated
     */
    public void seteCaseBehaviorId(Short eCaseBehaviorId) {
        this.eCaseBehaviorId = eCaseBehaviorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.PERSON_NUM
     *
     * @return the value of TBL_E_CASE.PERSON_NUM
     *
     * @mbggenerated
     */
    public Short getPersonNum() {
        return personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.PERSON_NUM
     *
     * @param personNum the value for TBL_E_CASE.PERSON_NUM
     *
     * @mbggenerated
     */
    public void setPersonNum(Short personNum) {
        this.personNum = personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.SPONSOR_PERSON_NAME
     *
     * @return the value of TBL_E_CASE.SPONSOR_PERSON_NAME
     *
     * @mbggenerated
     */
    public String getSponsorPersonName() {
        return sponsorPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.SPONSOR_PERSON_NAME
     *
     * @param sponsorPersonName the value for TBL_E_CASE.SPONSOR_PERSON_NAME
     *
     * @mbggenerated
     */
    public void setSponsorPersonName(String sponsorPersonName) {
        this.sponsorPersonName = sponsorPersonName == null ? null : sponsorPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.SPONSOR_PERSON_TEL
     *
     * @return the value of TBL_E_CASE.SPONSOR_PERSON_TEL
     *
     * @mbggenerated
     */
    public String getSponsorPersonTel() {
        return sponsorPersonTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.SPONSOR_PERSON_TEL
     *
     * @param sponsorPersonTel the value for TBL_E_CASE.SPONSOR_PERSON_TEL
     *
     * @mbggenerated
     */
    public void setSponsorPersonTel(String sponsorPersonTel) {
        this.sponsorPersonTel = sponsorPersonTel == null ? null : sponsorPersonTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.SPONSOR_PERSON_ADDRESS
     *
     * @return the value of TBL_E_CASE.SPONSOR_PERSON_ADDRESS
     *
     * @mbggenerated
     */
    public String getSponsorPersonAddress() {
        return sponsorPersonAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.SPONSOR_PERSON_ADDRESS
     *
     * @param sponsorPersonAddress the value for TBL_E_CASE.SPONSOR_PERSON_ADDRESS
     *
     * @mbggenerated
     */
    public void setSponsorPersonAddress(String sponsorPersonAddress) {
        this.sponsorPersonAddress = sponsorPersonAddress == null ? null : sponsorPersonAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.COORDINATE_X
     *
     * @return the value of TBL_E_CASE.COORDINATE_X
     *
     * @mbggenerated
     */
    public BigDecimal getCoordinateX() {
        return coordinateX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.COORDINATE_X
     *
     * @param coordinateX the value for TBL_E_CASE.COORDINATE_X
     *
     * @mbggenerated
     */
    public void setCoordinateX(BigDecimal coordinateX) {
        this.coordinateX = coordinateX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.COORDINATE_Y
     *
     * @return the value of TBL_E_CASE.COORDINATE_Y
     *
     * @mbggenerated
     */
    public BigDecimal getCoordinateY() {
        return coordinateY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.COORDINATE_Y
     *
     * @param coordinateY the value for TBL_E_CASE.COORDINATE_Y
     *
     * @mbggenerated
     */
    public void setCoordinateY(BigDecimal coordinateY) {
        this.coordinateY = coordinateY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.INS_YMDHMS
     *
     * @return the value of TBL_E_CASE.INS_YMDHMS
     *
     * @mbggenerated
     */
    public Date getInsYmdhms() {
        return insYmdhms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.INS_YMDHMS
     *
     * @param insYmdhms the value for TBL_E_CASE.INS_YMDHMS
     *
     * @mbggenerated
     */
    public void setInsYmdhms(Date insYmdhms) {
        this.insYmdhms = insYmdhms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.INS_ID
     *
     * @return the value of TBL_E_CASE.INS_ID
     *
     * @mbggenerated
     */
    public String getInsId() {
        return insId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.INS_ID
     *
     * @param insId the value for TBL_E_CASE.INS_ID
     *
     * @mbggenerated
     */
    public void setInsId(String insId) {
        this.insId = insId == null ? null : insId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.UPD_EAC
     *
     * @return the value of TBL_E_CASE.UPD_EAC
     *
     * @mbggenerated
     */
    public Integer getUpdEac() {
        return updEac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.UPD_EAC
     *
     * @param updEac the value for TBL_E_CASE.UPD_EAC
     *
     * @mbggenerated
     */
    public void setUpdEac(Integer updEac) {
        this.updEac = updEac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.UPD_YMDHMS
     *
     * @return the value of TBL_E_CASE.UPD_YMDHMS
     *
     * @mbggenerated
     */
    public Date getUpdYmdhms() {
        return updYmdhms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.UPD_YMDHMS
     *
     * @param updYmdhms the value for TBL_E_CASE.UPD_YMDHMS
     *
     * @mbggenerated
     */
    public void setUpdYmdhms(Date updYmdhms) {
        this.updYmdhms = updYmdhms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.UPD_ID
     *
     * @return the value of TBL_E_CASE.UPD_ID
     *
     * @mbggenerated
     */
    public String getUpdId() {
        return updId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.UPD_ID
     *
     * @param updId the value for TBL_E_CASE.UPD_ID
     *
     * @mbggenerated
     */
    public void setUpdId(String updId) {
        this.updId = updId == null ? null : updId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.DEL_FLAG
     *
     * @return the value of TBL_E_CASE.DEL_FLAG
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.DEL_FLAG
     *
     * @param delFlag the value for TBL_E_CASE.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.GLOBAL_UNIT_CODE
     *
     * @return the value of TBL_E_CASE.GLOBAL_UNIT_CODE
     *
     * @mbggenerated
     */
    public String getGlobalUnitCode() {
        return globalUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.GLOBAL_UNIT_CODE
     *
     * @param globalUnitCode the value for TBL_E_CASE.GLOBAL_UNIT_CODE
     *
     * @mbggenerated
     */
    public void setGlobalUnitCode(String globalUnitCode) {
        this.globalUnitCode = globalUnitCode == null ? null : globalUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.EXT_FLAG
     *
     * @return the value of TBL_E_CASE.EXT_FLAG
     *
     * @mbggenerated
     */
    public String getExtFlag() {
        return extFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.EXT_FLAG
     *
     * @param extFlag the value for TBL_E_CASE.EXT_FLAG
     *
     * @mbggenerated
     */
    public void setExtFlag(String extFlag) {
        this.extFlag = extFlag == null ? null : extFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_CASE.E_CASE_ID_SMX_PK
     *
     * @return the value of TBL_E_CASE.E_CASE_ID_SMX_PK
     *
     * @mbggenerated
     */
    public String geteCaseIdSmxPk() {
        return eCaseIdSmxPk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_CASE.E_CASE_ID_SMX_PK
     *
     * @param eCaseIdSmxPk the value for TBL_E_CASE.E_CASE_ID_SMX_PK
     *
     * @mbggenerated
     */
    public void seteCaseIdSmxPk(String eCaseIdSmxPk) {
        this.eCaseIdSmxPk = eCaseIdSmxPk == null ? null : eCaseIdSmxPk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbleCase other = (TbleCase) that;
        return (this.geteCaseId() == null ? other.geteCaseId() == null : this.geteCaseId().equals(other.geteCaseId()))
            && (this.geteCaseCode() == null ? other.geteCaseCode() == null : this.geteCaseCode().equals(other.geteCaseCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.geteCaseLevelId() == null ? other.geteCaseLevelId() == null : this.geteCaseLevelId().equals(other.geteCaseLevelId()))
            && (this.geteCaseTypeId() == null ? other.geteCaseTypeId() == null : this.geteCaseTypeId().equals(other.geteCaseTypeId()))
            && (this.getHdAddress() == null ? other.getHdAddress() == null : this.getHdAddress().equals(other.getHdAddress()))
            && (this.getHdDate() == null ? other.getHdDate() == null : this.getHdDate().equals(other.getHdDate()))
            && (this.geteCaseCdId() == null ? other.geteCaseCdId() == null : this.geteCaseCdId().equals(other.geteCaseCdId()))
            && (this.geteCaseBehaviorId() == null ? other.geteCaseBehaviorId() == null : this.geteCaseBehaviorId().equals(other.geteCaseBehaviorId()))
            && (this.getPersonNum() == null ? other.getPersonNum() == null : this.getPersonNum().equals(other.getPersonNum()))
            && (this.getSponsorPersonName() == null ? other.getSponsorPersonName() == null : this.getSponsorPersonName().equals(other.getSponsorPersonName()))
            && (this.getSponsorPersonTel() == null ? other.getSponsorPersonTel() == null : this.getSponsorPersonTel().equals(other.getSponsorPersonTel()))
            && (this.getSponsorPersonAddress() == null ? other.getSponsorPersonAddress() == null : this.getSponsorPersonAddress().equals(other.getSponsorPersonAddress()))
            && (this.getCoordinateX() == null ? other.getCoordinateX() == null : this.getCoordinateX().equals(other.getCoordinateX()))
            && (this.getCoordinateY() == null ? other.getCoordinateY() == null : this.getCoordinateY().equals(other.getCoordinateY()))
            && (this.getInsYmdhms() == null ? other.getInsYmdhms() == null : this.getInsYmdhms().equals(other.getInsYmdhms()))
            && (this.getInsId() == null ? other.getInsId() == null : this.getInsId().equals(other.getInsId()))
            && (this.getUpdEac() == null ? other.getUpdEac() == null : this.getUpdEac().equals(other.getUpdEac()))
            && (this.getUpdYmdhms() == null ? other.getUpdYmdhms() == null : this.getUpdYmdhms().equals(other.getUpdYmdhms()))
            && (this.getUpdId() == null ? other.getUpdId() == null : this.getUpdId().equals(other.getUpdId()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getGlobalUnitCode() == null ? other.getGlobalUnitCode() == null : this.getGlobalUnitCode().equals(other.getGlobalUnitCode()))
            && (this.getExtFlag() == null ? other.getExtFlag() == null : this.getExtFlag().equals(other.getExtFlag()))
            && (this.geteCaseIdSmxPk() == null ? other.geteCaseIdSmxPk() == null : this.geteCaseIdSmxPk().equals(other.geteCaseIdSmxPk()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((geteCaseId() == null) ? 0 : geteCaseId().hashCode());
        result = prime * result + ((geteCaseCode() == null) ? 0 : geteCaseCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((geteCaseLevelId() == null) ? 0 : geteCaseLevelId().hashCode());
        result = prime * result + ((geteCaseTypeId() == null) ? 0 : geteCaseTypeId().hashCode());
        result = prime * result + ((getHdAddress() == null) ? 0 : getHdAddress().hashCode());
        result = prime * result + ((getHdDate() == null) ? 0 : getHdDate().hashCode());
        result = prime * result + ((geteCaseCdId() == null) ? 0 : geteCaseCdId().hashCode());
        result = prime * result + ((geteCaseBehaviorId() == null) ? 0 : geteCaseBehaviorId().hashCode());
        result = prime * result + ((getPersonNum() == null) ? 0 : getPersonNum().hashCode());
        result = prime * result + ((getSponsorPersonName() == null) ? 0 : getSponsorPersonName().hashCode());
        result = prime * result + ((getSponsorPersonTel() == null) ? 0 : getSponsorPersonTel().hashCode());
        result = prime * result + ((getSponsorPersonAddress() == null) ? 0 : getSponsorPersonAddress().hashCode());
        result = prime * result + ((getCoordinateX() == null) ? 0 : getCoordinateX().hashCode());
        result = prime * result + ((getCoordinateY() == null) ? 0 : getCoordinateY().hashCode());
        result = prime * result + ((getInsYmdhms() == null) ? 0 : getInsYmdhms().hashCode());
        result = prime * result + ((getInsId() == null) ? 0 : getInsId().hashCode());
        result = prime * result + ((getUpdEac() == null) ? 0 : getUpdEac().hashCode());
        result = prime * result + ((getUpdYmdhms() == null) ? 0 : getUpdYmdhms().hashCode());
        result = prime * result + ((getUpdId() == null) ? 0 : getUpdId().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getGlobalUnitCode() == null) ? 0 : getGlobalUnitCode().hashCode());
        result = prime * result + ((getExtFlag() == null) ? 0 : getExtFlag().hashCode());
        result = prime * result + ((geteCaseIdSmxPk() == null) ? 0 : geteCaseIdSmxPk().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_CASE
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eCaseId=").append(eCaseId);
        sb.append(", eCaseCode=").append(eCaseCode);
        sb.append(", name=").append(name);
        sb.append(", eCaseLevelId=").append(eCaseLevelId);
        sb.append(", eCaseTypeId=").append(eCaseTypeId);
        sb.append(", hdAddress=").append(hdAddress);
        sb.append(", hdDate=").append(hdDate);
        sb.append(", eCaseCdId=").append(eCaseCdId);
        sb.append(", eCaseBehaviorId=").append(eCaseBehaviorId);
        sb.append(", personNum=").append(personNum);
        sb.append(", sponsorPersonName=").append(sponsorPersonName);
        sb.append(", sponsorPersonTel=").append(sponsorPersonTel);
        sb.append(", sponsorPersonAddress=").append(sponsorPersonAddress);
        sb.append(", coordinateX=").append(coordinateX);
        sb.append(", coordinateY=").append(coordinateY);
        sb.append(", insYmdhms=").append(insYmdhms);
        sb.append(", insId=").append(insId);
        sb.append(", updEac=").append(updEac);
        sb.append(", updYmdhms=").append(updYmdhms);
        sb.append(", updId=").append(updId);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", globalUnitCode=").append(globalUnitCode);
        sb.append(", extFlag=").append(extFlag);
        sb.append(", eCaseIdSmxPk=").append(eCaseIdSmxPk);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}