package com.zhixin.rd.rkjc.web.entity.qk;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TbleOrg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.E_ORG_ID
     *
     * @mbggenerated
     */
    private BigDecimal eOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.E_ORG_CODE
     *
     * @mbggenerated
     */
    private String eOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.ABOUT
     *
     * @mbggenerated
     */
    private String about;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.E_ORG_LEVEL_ID
     *
     * @mbggenerated
     */
    private Short eOrgLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.E_ORG_TYPE_ID
     *
     * @mbggenerated
     */
    private Short eOrgTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.E_ORG_TYPE2_ID
     *
     * @mbggenerated
     */
    private Short eOrgType2Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.START_DATE
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.HD_ADDRESS
     *
     * @mbggenerated
     */
    private String hdAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.PERSON_NUM
     *
     * @mbggenerated
     */
    private Short personNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.CHARGE_PERSON_NAME
     *
     * @mbggenerated
     */
    private String chargePersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.CHARGE_PERSON_TEL
     *
     * @mbggenerated
     */
    private String chargePersonTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.CHARGE_PERSON_ADDRESS
     *
     * @mbggenerated
     */
    private String chargePersonAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.COORDINATE_X
     *
     * @mbggenerated
     */
    private BigDecimal coordinateX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.COORDINATE_Y
     *
     * @mbggenerated
     */
    private BigDecimal coordinateY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.INS_YMDHMS
     *
     * @mbggenerated
     */
    private Date insYmdhms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.INS_ID
     *
     * @mbggenerated
     */
    private String insId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.UPD_EAC
     *
     * @mbggenerated
     */
    private Integer updEac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.UPD_YMDHMS
     *
     * @mbggenerated
     */
    private Date updYmdhms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.UPD_ID
     *
     * @mbggenerated
     */
    private String updId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.DEL_FLAG
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.GLOBAL_UNIT_CODE
     *
     * @mbggenerated
     */
    private String globalUnitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.EXT_FLAG
     *
     * @mbggenerated
     */
    private String extFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.CHARGE_PERSON_IDCARD
     *
     * @mbggenerated
     */
    private String chargePersonIdcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_E_ORG.E_ORG_ID_SMX_PK
     *
     * @mbggenerated
     */
    private String eOrgIdSmxPk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.E_ORG_ID
     *
     * @return the value of TBL_E_ORG.E_ORG_ID
     *
     * @mbggenerated
     */
    public BigDecimal geteOrgId() {
        return eOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.E_ORG_ID
     *
     * @param eOrgId the value for TBL_E_ORG.E_ORG_ID
     *
     * @mbggenerated
     */
    public void seteOrgId(BigDecimal eOrgId) {
        this.eOrgId = eOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.E_ORG_CODE
     *
     * @return the value of TBL_E_ORG.E_ORG_CODE
     *
     * @mbggenerated
     */
    public String geteOrgCode() {
        return eOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.E_ORG_CODE
     *
     * @param eOrgCode the value for TBL_E_ORG.E_ORG_CODE
     *
     * @mbggenerated
     */
    public void seteOrgCode(String eOrgCode) {
        this.eOrgCode = eOrgCode == null ? null : eOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.NAME
     *
     * @return the value of TBL_E_ORG.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.NAME
     *
     * @param name the value for TBL_E_ORG.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.ABOUT
     *
     * @return the value of TBL_E_ORG.ABOUT
     *
     * @mbggenerated
     */
    public String getAbout() {
        return about;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.ABOUT
     *
     * @param about the value for TBL_E_ORG.ABOUT
     *
     * @mbggenerated
     */
    public void setAbout(String about) {
        this.about = about == null ? null : about.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.E_ORG_LEVEL_ID
     *
     * @return the value of TBL_E_ORG.E_ORG_LEVEL_ID
     *
     * @mbggenerated
     */
    public Short geteOrgLevelId() {
        return eOrgLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.E_ORG_LEVEL_ID
     *
     * @param eOrgLevelId the value for TBL_E_ORG.E_ORG_LEVEL_ID
     *
     * @mbggenerated
     */
    public void seteOrgLevelId(Short eOrgLevelId) {
        this.eOrgLevelId = eOrgLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.E_ORG_TYPE_ID
     *
     * @return the value of TBL_E_ORG.E_ORG_TYPE_ID
     *
     * @mbggenerated
     */
    public Short geteOrgTypeId() {
        return eOrgTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.E_ORG_TYPE_ID
     *
     * @param eOrgTypeId the value for TBL_E_ORG.E_ORG_TYPE_ID
     *
     * @mbggenerated
     */
    public void seteOrgTypeId(Short eOrgTypeId) {
        this.eOrgTypeId = eOrgTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.E_ORG_TYPE2_ID
     *
     * @return the value of TBL_E_ORG.E_ORG_TYPE2_ID
     *
     * @mbggenerated
     */
    public Short geteOrgType2Id() {
        return eOrgType2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.E_ORG_TYPE2_ID
     *
     * @param eOrgType2Id the value for TBL_E_ORG.E_ORG_TYPE2_ID
     *
     * @mbggenerated
     */
    public void seteOrgType2Id(Short eOrgType2Id) {
        this.eOrgType2Id = eOrgType2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.START_DATE
     *
     * @return the value of TBL_E_ORG.START_DATE
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.START_DATE
     *
     * @param startDate the value for TBL_E_ORG.START_DATE
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.HD_ADDRESS
     *
     * @return the value of TBL_E_ORG.HD_ADDRESS
     *
     * @mbggenerated
     */
    public String getHdAddress() {
        return hdAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.HD_ADDRESS
     *
     * @param hdAddress the value for TBL_E_ORG.HD_ADDRESS
     *
     * @mbggenerated
     */
    public void setHdAddress(String hdAddress) {
        this.hdAddress = hdAddress == null ? null : hdAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.PERSON_NUM
     *
     * @return the value of TBL_E_ORG.PERSON_NUM
     *
     * @mbggenerated
     */
    public Short getPersonNum() {
        return personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.PERSON_NUM
     *
     * @param personNum the value for TBL_E_ORG.PERSON_NUM
     *
     * @mbggenerated
     */
    public void setPersonNum(Short personNum) {
        this.personNum = personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.CHARGE_PERSON_NAME
     *
     * @return the value of TBL_E_ORG.CHARGE_PERSON_NAME
     *
     * @mbggenerated
     */
    public String getChargePersonName() {
        return chargePersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.CHARGE_PERSON_NAME
     *
     * @param chargePersonName the value for TBL_E_ORG.CHARGE_PERSON_NAME
     *
     * @mbggenerated
     */
    public void setChargePersonName(String chargePersonName) {
        this.chargePersonName = chargePersonName == null ? null : chargePersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.CHARGE_PERSON_TEL
     *
     * @return the value of TBL_E_ORG.CHARGE_PERSON_TEL
     *
     * @mbggenerated
     */
    public String getChargePersonTel() {
        return chargePersonTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.CHARGE_PERSON_TEL
     *
     * @param chargePersonTel the value for TBL_E_ORG.CHARGE_PERSON_TEL
     *
     * @mbggenerated
     */
    public void setChargePersonTel(String chargePersonTel) {
        this.chargePersonTel = chargePersonTel == null ? null : chargePersonTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.CHARGE_PERSON_ADDRESS
     *
     * @return the value of TBL_E_ORG.CHARGE_PERSON_ADDRESS
     *
     * @mbggenerated
     */
    public String getChargePersonAddress() {
        return chargePersonAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.CHARGE_PERSON_ADDRESS
     *
     * @param chargePersonAddress the value for TBL_E_ORG.CHARGE_PERSON_ADDRESS
     *
     * @mbggenerated
     */
    public void setChargePersonAddress(String chargePersonAddress) {
        this.chargePersonAddress = chargePersonAddress == null ? null : chargePersonAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.COORDINATE_X
     *
     * @return the value of TBL_E_ORG.COORDINATE_X
     *
     * @mbggenerated
     */
    public BigDecimal getCoordinateX() {
        return coordinateX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.COORDINATE_X
     *
     * @param coordinateX the value for TBL_E_ORG.COORDINATE_X
     *
     * @mbggenerated
     */
    public void setCoordinateX(BigDecimal coordinateX) {
        this.coordinateX = coordinateX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.COORDINATE_Y
     *
     * @return the value of TBL_E_ORG.COORDINATE_Y
     *
     * @mbggenerated
     */
    public BigDecimal getCoordinateY() {
        return coordinateY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.COORDINATE_Y
     *
     * @param coordinateY the value for TBL_E_ORG.COORDINATE_Y
     *
     * @mbggenerated
     */
    public void setCoordinateY(BigDecimal coordinateY) {
        this.coordinateY = coordinateY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.INS_YMDHMS
     *
     * @return the value of TBL_E_ORG.INS_YMDHMS
     *
     * @mbggenerated
     */
    public Date getInsYmdhms() {
        return insYmdhms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.INS_YMDHMS
     *
     * @param insYmdhms the value for TBL_E_ORG.INS_YMDHMS
     *
     * @mbggenerated
     */
    public void setInsYmdhms(Date insYmdhms) {
        this.insYmdhms = insYmdhms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.INS_ID
     *
     * @return the value of TBL_E_ORG.INS_ID
     *
     * @mbggenerated
     */
    public String getInsId() {
        return insId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.INS_ID
     *
     * @param insId the value for TBL_E_ORG.INS_ID
     *
     * @mbggenerated
     */
    public void setInsId(String insId) {
        this.insId = insId == null ? null : insId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.UPD_EAC
     *
     * @return the value of TBL_E_ORG.UPD_EAC
     *
     * @mbggenerated
     */
    public Integer getUpdEac() {
        return updEac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.UPD_EAC
     *
     * @param updEac the value for TBL_E_ORG.UPD_EAC
     *
     * @mbggenerated
     */
    public void setUpdEac(Integer updEac) {
        this.updEac = updEac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.UPD_YMDHMS
     *
     * @return the value of TBL_E_ORG.UPD_YMDHMS
     *
     * @mbggenerated
     */
    public Date getUpdYmdhms() {
        return updYmdhms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.UPD_YMDHMS
     *
     * @param updYmdhms the value for TBL_E_ORG.UPD_YMDHMS
     *
     * @mbggenerated
     */
    public void setUpdYmdhms(Date updYmdhms) {
        this.updYmdhms = updYmdhms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.UPD_ID
     *
     * @return the value of TBL_E_ORG.UPD_ID
     *
     * @mbggenerated
     */
    public String getUpdId() {
        return updId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.UPD_ID
     *
     * @param updId the value for TBL_E_ORG.UPD_ID
     *
     * @mbggenerated
     */
    public void setUpdId(String updId) {
        this.updId = updId == null ? null : updId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.DEL_FLAG
     *
     * @return the value of TBL_E_ORG.DEL_FLAG
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.DEL_FLAG
     *
     * @param delFlag the value for TBL_E_ORG.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.GLOBAL_UNIT_CODE
     *
     * @return the value of TBL_E_ORG.GLOBAL_UNIT_CODE
     *
     * @mbggenerated
     */
    public String getGlobalUnitCode() {
        return globalUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.GLOBAL_UNIT_CODE
     *
     * @param globalUnitCode the value for TBL_E_ORG.GLOBAL_UNIT_CODE
     *
     * @mbggenerated
     */
    public void setGlobalUnitCode(String globalUnitCode) {
        this.globalUnitCode = globalUnitCode == null ? null : globalUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.EXT_FLAG
     *
     * @return the value of TBL_E_ORG.EXT_FLAG
     *
     * @mbggenerated
     */
    public String getExtFlag() {
        return extFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.EXT_FLAG
     *
     * @param extFlag the value for TBL_E_ORG.EXT_FLAG
     *
     * @mbggenerated
     */
    public void setExtFlag(String extFlag) {
        this.extFlag = extFlag == null ? null : extFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.CHARGE_PERSON_IDCARD
     *
     * @return the value of TBL_E_ORG.CHARGE_PERSON_IDCARD
     *
     * @mbggenerated
     */
    public String getChargePersonIdcard() {
        return chargePersonIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.CHARGE_PERSON_IDCARD
     *
     * @param chargePersonIdcard the value for TBL_E_ORG.CHARGE_PERSON_IDCARD
     *
     * @mbggenerated
     */
    public void setChargePersonIdcard(String chargePersonIdcard) {
        this.chargePersonIdcard = chargePersonIdcard == null ? null : chargePersonIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_E_ORG.E_ORG_ID_SMX_PK
     *
     * @return the value of TBL_E_ORG.E_ORG_ID_SMX_PK
     *
     * @mbggenerated
     */
    public String geteOrgIdSmxPk() {
        return eOrgIdSmxPk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_E_ORG.E_ORG_ID_SMX_PK
     *
     * @param eOrgIdSmxPk the value for TBL_E_ORG.E_ORG_ID_SMX_PK
     *
     * @mbggenerated
     */
    public void seteOrgIdSmxPk(String eOrgIdSmxPk) {
        this.eOrgIdSmxPk = eOrgIdSmxPk == null ? null : eOrgIdSmxPk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbleOrg other = (TbleOrg) that;
        return (this.geteOrgId() == null ? other.geteOrgId() == null : this.geteOrgId().equals(other.geteOrgId()))
            && (this.geteOrgCode() == null ? other.geteOrgCode() == null : this.geteOrgCode().equals(other.geteOrgCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAbout() == null ? other.getAbout() == null : this.getAbout().equals(other.getAbout()))
            && (this.geteOrgLevelId() == null ? other.geteOrgLevelId() == null : this.geteOrgLevelId().equals(other.geteOrgLevelId()))
            && (this.geteOrgTypeId() == null ? other.geteOrgTypeId() == null : this.geteOrgTypeId().equals(other.geteOrgTypeId()))
            && (this.geteOrgType2Id() == null ? other.geteOrgType2Id() == null : this.geteOrgType2Id().equals(other.geteOrgType2Id()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getHdAddress() == null ? other.getHdAddress() == null : this.getHdAddress().equals(other.getHdAddress()))
            && (this.getPersonNum() == null ? other.getPersonNum() == null : this.getPersonNum().equals(other.getPersonNum()))
            && (this.getChargePersonName() == null ? other.getChargePersonName() == null : this.getChargePersonName().equals(other.getChargePersonName()))
            && (this.getChargePersonTel() == null ? other.getChargePersonTel() == null : this.getChargePersonTel().equals(other.getChargePersonTel()))
            && (this.getChargePersonAddress() == null ? other.getChargePersonAddress() == null : this.getChargePersonAddress().equals(other.getChargePersonAddress()))
            && (this.getCoordinateX() == null ? other.getCoordinateX() == null : this.getCoordinateX().equals(other.getCoordinateX()))
            && (this.getCoordinateY() == null ? other.getCoordinateY() == null : this.getCoordinateY().equals(other.getCoordinateY()))
            && (this.getInsYmdhms() == null ? other.getInsYmdhms() == null : this.getInsYmdhms().equals(other.getInsYmdhms()))
            && (this.getInsId() == null ? other.getInsId() == null : this.getInsId().equals(other.getInsId()))
            && (this.getUpdEac() == null ? other.getUpdEac() == null : this.getUpdEac().equals(other.getUpdEac()))
            && (this.getUpdYmdhms() == null ? other.getUpdYmdhms() == null : this.getUpdYmdhms().equals(other.getUpdYmdhms()))
            && (this.getUpdId() == null ? other.getUpdId() == null : this.getUpdId().equals(other.getUpdId()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getGlobalUnitCode() == null ? other.getGlobalUnitCode() == null : this.getGlobalUnitCode().equals(other.getGlobalUnitCode()))
            && (this.getExtFlag() == null ? other.getExtFlag() == null : this.getExtFlag().equals(other.getExtFlag()))
            && (this.getChargePersonIdcard() == null ? other.getChargePersonIdcard() == null : this.getChargePersonIdcard().equals(other.getChargePersonIdcard()))
            && (this.geteOrgIdSmxPk() == null ? other.geteOrgIdSmxPk() == null : this.geteOrgIdSmxPk().equals(other.geteOrgIdSmxPk()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((geteOrgId() == null) ? 0 : geteOrgId().hashCode());
        result = prime * result + ((geteOrgCode() == null) ? 0 : geteOrgCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAbout() == null) ? 0 : getAbout().hashCode());
        result = prime * result + ((geteOrgLevelId() == null) ? 0 : geteOrgLevelId().hashCode());
        result = prime * result + ((geteOrgTypeId() == null) ? 0 : geteOrgTypeId().hashCode());
        result = prime * result + ((geteOrgType2Id() == null) ? 0 : geteOrgType2Id().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getHdAddress() == null) ? 0 : getHdAddress().hashCode());
        result = prime * result + ((getPersonNum() == null) ? 0 : getPersonNum().hashCode());
        result = prime * result + ((getChargePersonName() == null) ? 0 : getChargePersonName().hashCode());
        result = prime * result + ((getChargePersonTel() == null) ? 0 : getChargePersonTel().hashCode());
        result = prime * result + ((getChargePersonAddress() == null) ? 0 : getChargePersonAddress().hashCode());
        result = prime * result + ((getCoordinateX() == null) ? 0 : getCoordinateX().hashCode());
        result = prime * result + ((getCoordinateY() == null) ? 0 : getCoordinateY().hashCode());
        result = prime * result + ((getInsYmdhms() == null) ? 0 : getInsYmdhms().hashCode());
        result = prime * result + ((getInsId() == null) ? 0 : getInsId().hashCode());
        result = prime * result + ((getUpdEac() == null) ? 0 : getUpdEac().hashCode());
        result = prime * result + ((getUpdYmdhms() == null) ? 0 : getUpdYmdhms().hashCode());
        result = prime * result + ((getUpdId() == null) ? 0 : getUpdId().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getGlobalUnitCode() == null) ? 0 : getGlobalUnitCode().hashCode());
        result = prime * result + ((getExtFlag() == null) ? 0 : getExtFlag().hashCode());
        result = prime * result + ((getChargePersonIdcard() == null) ? 0 : getChargePersonIdcard().hashCode());
        result = prime * result + ((geteOrgIdSmxPk() == null) ? 0 : geteOrgIdSmxPk().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_E_ORG
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eOrgId=").append(eOrgId);
        sb.append(", eOrgCode=").append(eOrgCode);
        sb.append(", name=").append(name);
        sb.append(", about=").append(about);
        sb.append(", eOrgLevelId=").append(eOrgLevelId);
        sb.append(", eOrgTypeId=").append(eOrgTypeId);
        sb.append(", eOrgType2Id=").append(eOrgType2Id);
        sb.append(", startDate=").append(startDate);
        sb.append(", hdAddress=").append(hdAddress);
        sb.append(", personNum=").append(personNum);
        sb.append(", chargePersonName=").append(chargePersonName);
        sb.append(", chargePersonTel=").append(chargePersonTel);
        sb.append(", chargePersonAddress=").append(chargePersonAddress);
        sb.append(", coordinateX=").append(coordinateX);
        sb.append(", coordinateY=").append(coordinateY);
        sb.append(", insYmdhms=").append(insYmdhms);
        sb.append(", insId=").append(insId);
        sb.append(", updEac=").append(updEac);
        sb.append(", updYmdhms=").append(updYmdhms);
        sb.append(", updId=").append(updId);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", globalUnitCode=").append(globalUnitCode);
        sb.append(", extFlag=").append(extFlag);
        sb.append(", chargePersonIdcard=").append(chargePersonIdcard);
        sb.append(", eOrgIdSmxPk=").append(eOrgIdSmxPk);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}